import type { Unidad } from "../tipos"

const unidad4: Unidad = {
  id: 4,
  nombre: "Medición",
  descripcion: "Aprende a medir longitud, masa, capacidad, tiempo y más.",
  color: "orange",
  icono: "📏",
  lecciones: [
    {
      id: "3-4-1",
      titulo: "Medición de la longitud con unidades estándar",
      objetivo: "Usar unidades estándar del sistema métrico para medir longitudes.",
      concepto_clave: "1 km = 1.000 m | 1 m = 100 cm | 1 cm = 10 mm",
      explicacion: [
        "El SISTEMA MÉTRICO es el sistema de medida oficial en Colombia y en casi todo el mundo. Sus unidades de longitud son: kilómetro (km), metro (m), centímetro (cm) y milímetro (mm).",
        "Para convertir entre unidades: multiplicamos cuando vamos a unidades más pequeñas y dividimos cuando vamos a unidades más grandes.",
        "Ejemplos de uso: km para distancias entre ciudades, m para habitaciones, cm para objetos pequeños, mm para cosas muy pequeñas.",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 3 km a metros",
          pasos: [
            { texto: "1 km = 1.000 m" },
            { texto: "3 km = 3 × 1.000 m" },
          ],
          resultado: "3 km = 3.000 m",
        },
        {
          enunciado: "Convierte 250 cm a metros",
          pasos: [
            { texto: "100 cm = 1 m" },
            { texto: "250 cm = 250 ÷ 100 m" },
          ],
          resultado: "250 cm = 2,5 m (dos metros y medio)",
        },
        {
          enunciado: "Un lápiz mide 18 cm. ¿Cuántos mm mide?",
          pasos: [
            { texto: "1 cm = 10 mm" },
            { texto: "18 cm = 18 × 10 mm" },
          ],
          resultado: "18 cm = 180 mm",
        },
      ],
      ejercicios: [
        {
          id: "3-4-1-e1",
          enunciado: "Convierte 5 m a centímetros",
          tipo: "numero",
          respuesta: "500",
          pista: "1 m = 100 cm. Multiplica 5 × 100.",
          explicacion: "5 m × 100 = 500 cm.",
        },
        {
          id: "3-4-1-e2",
          enunciado: "¿Cuántos metros son 3.500 cm?",
          tipo: "numero",
          respuesta: "35",
          pista: "Para pasar de cm a m, divide entre 100.",
          explicacion: "3.500 ÷ 100 = 35 m.",
        },
        {
          id: "3-4-1-e3",
          enunciado: "La distancia de Bogotá a Medellín es aproximadamente 415 km. ¿Cuántos metros son?",
          tipo: "numero",
          respuesta: "415000",
          pista: "1 km = 1.000 m. Multiplica 415 × 1.000.",
          explicacion: "415 km × 1.000 = 415.000 m.",
        },
        {
          id: "3-4-1-e4",
          enunciado: "¿Cuál es la unidad más apropiada para medir el ancho de un cuaderno: mm, cm, m o km?",
          tipo: "seleccion",
          opciones: ["mm", "cm", "m", "km"],
          respuesta: "cm",
          pista: "Un cuaderno tiene unos 20-25 cm de ancho.",
          explicacion: "El centímetro es la unidad más adecuada para medir un cuaderno. Los mm son muy pequeños y los m y km son demasiado grandes.",
        },
      ],
    },
    {
      id: "3-4-2",
      titulo: "Perímetro de polígonos",
      objetivo: "Calcular el perímetro de polígonos sumando la longitud de todos sus lados.",
      concepto_clave: "Perímetro = suma de todos los lados de una figura. Es la longitud del contorno.",
      explicacion: [
        "El PERÍMETRO es la distancia que recorremos si caminamos alrededor de una figura. Es como poner una cerca alrededor de un terreno: necesitas saber cuánta malla comprar.",
        "Para calcularlo, simplemente sumamos la longitud de todos los lados de la figura.",
        "Para figuras regulares (todos los lados iguales) hay un atajo: P = número de lados × longitud de cada lado.",
      ],
      ejemplos: [
        {
          enunciado: "Halla el perímetro de un rectángulo de 8 cm × 5 cm",
          pasos: [
            { texto: "Un rectángulo tiene 2 lados de 8 cm y 2 lados de 5 cm" },
            { texto: "P = 8 + 8 + 5 + 5 = 26 cm" },
            { texto: "O también: P = 2 × (8 + 5) = 2 × 13 = 26 cm" },
          ],
          resultado: "El perímetro es 26 cm",
        },
        {
          enunciado: "Un cuadrado tiene lados de 7 cm. ¿Cuál es su perímetro?",
          pasos: [
            { texto: "Un cuadrado tiene 4 lados iguales" },
            { texto: "P = 4 × 7 cm = 28 cm" },
          ],
          resultado: "El perímetro es 28 cm",
        },
      ],
      ejercicios: [
        {
          id: "3-4-2-e1",
          enunciado: "Halla el perímetro de un triángulo con lados de 6 cm, 8 cm y 10 cm",
          tipo: "numero",
          respuesta: "24",
          pista: "Suma los tres lados.",
          explicacion: "P = 6 + 8 + 10 = 24 cm.",
        },
        {
          id: "3-4-2-e2",
          enunciado: "Una cancha cuadrada tiene lados de 25 m. ¿Cuántos metros de malla se necesitan para cercarla?",
          tipo: "numero",
          respuesta: "100",
          pista: "P = 4 × lado.",
          explicacion: "P = 4 × 25 = 100 m de malla.",
        },
        {
          id: "3-4-2-e3",
          enunciado: "Un jardín tiene forma de pentágono regular con lados de 9 m. ¿Cuál es su perímetro?",
          tipo: "numero",
          respuesta: "45",
          pista: "Un pentágono tiene 5 lados iguales.",
          explicacion: "P = 5 × 9 = 45 m.",
        },
        {
          id: "3-4-2-e4",
          enunciado: "Si el perímetro de un cuadrado es 36 cm, ¿cuánto mide cada lado?",
          tipo: "numero",
          respuesta: "9",
          pista: "P = 4 × lado. Si P = 36, entonces lado = 36 ÷ 4.",
          explicacion: "36 ÷ 4 = 9 cm cada lado.",
        },
      ],
    },
    {
      id: "3-4-3",
      titulo: "El centímetro cuadrado",
      objetivo: "Comprender el centímetro cuadrado como unidad de medida de área.",
      concepto_clave: "El cm² es el área de un cuadrado de 1 cm × 1 cm. El área mide la superficie de una figura.",
      explicacion: [
        "El ÁREA mide la cantidad de superficie que ocupa una figura. Es diferente al perímetro: el perímetro es el contorno, el área es el interior.",
        "La unidad básica de área es el centímetro cuadrado (cm²): es el área de un cuadradito de 1 cm por 1 cm.",
        "Para hallar el área de un rectángulo: multiplicamos la base por la altura. A = base × altura.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuál es el área de un rectángulo de 6 cm × 4 cm?",
          pasos: [
            { texto: "A = base × altura" },
            { texto: "A = 6 cm × 4 cm" },
          ],
          resultado: "A = 24 cm²",
        },
        {
          enunciado: "¿Cuántos cuadraditos de 1 cm² caben en un cuadrado de 5 cm de lado?",
          pasos: [
            { texto: "A = lado × lado = 5 × 5 = 25" },
          ],
          resultado: "Caben 25 cuadraditos de 1 cm²",
        },
      ],
      ejercicios: [
        {
          id: "3-4-3-e1",
          enunciado: "¿Cuál es el área de un cuadrado de 7 cm de lado?",
          tipo: "numero",
          respuesta: "49",
          pista: "A = lado × lado = 7 × 7.",
          explicacion: "A = 7 × 7 = 49 cm².",
        },
        {
          id: "3-4-3-e2",
          enunciado: "Un cuaderno mide 28 cm × 20 cm. ¿Cuál es su área?",
          tipo: "numero",
          respuesta: "560",
          pista: "A = base × altura = 28 × 20.",
          explicacion: "A = 28 × 20 = 560 cm².",
        },
        {
          id: "3-4-3-e3",
          enunciado: "¿Cuál tiene más área: un rectángulo de 10 × 3 cm o uno de 7 × 5 cm?",
          tipo: "seleccion",
          opciones: ["10 × 3 cm (30 cm²)", "7 × 5 cm (35 cm²)", "Son iguales"],
          respuesta: "7 × 5 cm (35 cm²)",
          pista: "Calcula el área de cada uno: A = base × altura.",
          explicacion: "10×3=30 cm² y 7×5=35 cm². El segundo tiene más área.",
        },
        {
          id: "3-4-3-e4",
          enunciado: "¿Cuál es la diferencia entre perímetro y área?",
          tipo: "texto",
          respuesta: "El perímetro mide el contorno; el área mide la superficie interior",
          pista: "Piensa en una cancha: el perímetro es la línea del borde y el área es el espacio de juego.",
          explicacion: "El perímetro es la longitud del contorno (borde). El área es la superficie que ocupa la figura por dentro.",
        },
      ],
    },
    {
      id: "3-4-4",
      titulo: "Comparación de áreas con recubrimientos",
      objetivo: "Comparar áreas usando unidades no estándar y recubrimientos.",
      concepto_clave: "Comparar áreas por recubrimiento: ¿cuántas fichas de igual tamaño caben en cada figura?",
      explicacion: [
        "Antes de las unidades estándar, la gente comparaba áreas cubriéndolas con objetos: ¿cuántas fichas de cerámica necesito para cubrir cada piso?",
        "Si necesito más fichas para cubrir una superficie, esa superficie tiene más área.",
        "Esto funciona bien para comparar, pero para medir necesitamos unidades estándar como el cm².",
      ],
      ejemplos: [
        {
          enunciado: "La figura A se cubre con 12 fichas cuadradas. La figura B con 9 fichas iguales. ¿Cuál tiene más área?",
          pasos: [
            { texto: "A necesita 12 fichas" },
            { texto: "B necesita 9 fichas" },
            { texto: "12 > 9" },
          ],
          resultado: "La figura A tiene mayor área",
        },
        {
          enunciado: "Un tablero se cubre con 48 azulejos cuadrados de 20 cm de lado. ¿Cuál es el área total?",
          pasos: [
            { texto: "Área de un azulejo: 20 × 20 = 400 cm²" },
            { texto: "Área total: 48 × 400 cm² = 19.200 cm²" },
          ],
          resultado: "El área total del tablero es 19.200 cm²",
        },
      ],
      ejercicios: [
        {
          id: "3-4-4-e1",
          enunciado: "Para cubrir el piso de un cuarto se necesitan 20 baldosas. Para el de la cocina, 15 baldosas del mismo tamaño. ¿Cuál cuarto es más grande?",
          tipo: "seleccion",
          opciones: ["El cuarto (20 baldosas)", "La cocina (15 baldosas)", "Son iguales"],
          respuesta: "El cuarto (20 baldosas)",
          pista: "Más baldosas = más área.",
          explicacion: "Como las baldosas son del mismo tamaño, el que necesita más (20) tiene mayor área: el cuarto.",
        },
        {
          id: "3-4-4-e2",
          enunciado: "Se usan 6 triángulos iguales para cubrir una figura. Cada triángulo tiene área de 8 cm². ¿Cuál es el área total?",
          tipo: "numero",
          respuesta: "48",
          pista: "Multiplica el número de piezas por el área de cada una.",
          explicacion: "6 × 8 cm² = 48 cm².",
        },
        {
          id: "3-4-4-e3",
          enunciado: "¿Por qué es mejor usar unidades estándar (cm²) en vez de objetos cualquiera para comparar áreas?",
          tipo: "texto",
          respuesta: "Porque todos los cm² son iguales en todo el mundo, mientras que objetos como fichas pueden tener diferentes tamaños",
          pista: "¿Qué pasaría si comparas con fichas y yo con hojas de papel?",
          explicacion: "Las unidades estándar permiten comparar y comunicar medidas de manera universal. Si usas objetos distintos, los resultados no se pueden comparar.",
        },
        {
          id: "3-4-4-e4",
          enunciado: "Una figura se puede cubrir con 15 cuadrados de 2 cm de lado. ¿Cuál es el área de la figura?",
          tipo: "numero",
          respuesta: "60",
          pista: "Primero halla el área de cada cuadradito (2×2), luego multiplica por 15.",
          explicacion: "Área de cada cuadrado: 2×2=4 cm². Área total: 15×4=60 cm².",
        },
      ],
    },
    {
      id: "3-4-5",
      titulo: "Medición de la masa con unidades estándar",
      objetivo: "Usar gramos y kilogramos para medir y comparar masas.",
      concepto_clave: "1 kg = 1.000 g. Para objetos pesados usamos kg; para objetos livianos, g.",
      explicacion: [
        "La MASA nos dice cuánta materia tiene un objeto. La medimos con una balanza o báscula. Las unidades son el gramo (g) y el kilogramo (kg).",
        "1 kilogramo = 1.000 gramos. Un kilogramo es como 1.000 clips de papel juntos.",
        "Ejemplos: una moneda pesa unos 5 g, una manzana pesa unos 200 g, una mochila llena pesa unos 3 kg.",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 4,5 kg a gramos",
          pasos: [
            { texto: "1 kg = 1.000 g" },
            { texto: "4,5 kg = 4,5 × 1.000 g" },
          ],
          resultado: "4,5 kg = 4.500 g",
        },
        {
          enunciado: "Una naranja pesa 180 g y un mango 250 g. ¿Cuánto pesan juntos en kg?",
          pasos: [
            { texto: "Total en gramos: 180 + 250 = 430 g" },
            { texto: "Convertir a kg: 430 ÷ 1.000 = 0,43 kg" },
          ],
          resultado: "Juntos pesan 430 g = 0,43 kg",
        },
      ],
      ejercicios: [
        {
          id: "3-4-5-e1",
          enunciado: "Convierte 3 kg a gramos",
          tipo: "numero",
          respuesta: "3000",
          pista: "1 kg = 1.000 g. Multiplica 3 × 1.000.",
          explicacion: "3 kg = 3 × 1.000 = 3.000 g.",
        },
        {
          id: "3-4-5-e2",
          enunciado: "¿Cuántos kg son 7.500 g?",
          tipo: "seleccion",
          opciones: ["7 kg", "7,5 kg", "75 kg", "0,75 kg"],
          respuesta: "7,5 kg",
          pista: "Divide 7.500 entre 1.000.",
          explicacion: "7.500 ÷ 1.000 = 7,5 kg.",
        },
        {
          id: "3-4-5-e3",
          enunciado: "Una bolsa de arroz pesa 2 kg y una de frijoles 800 g. ¿Cuántos gramos pesan en total?",
          tipo: "numero",
          respuesta: "2800",
          pista: "Convierte 2 kg a gramos primero, luego suma.",
          explicacion: "2 kg = 2.000 g. 2.000 + 800 = 2.800 g.",
        },
        {
          id: "3-4-5-e4",
          enunciado: "¿Qué unidad usarías para pesar un bebé recién nacido?",
          tipo: "seleccion",
          opciones: ["Gramos (g)", "Kilogramos (kg)"],
          respuesta: "Kilogramos (kg)",
          pista: "Un bebé pesa entre 3 y 4 kg aproximadamente.",
          explicacion: "Los bebés pesan entre 2,5 y 4 kg. El kilogramo es la unidad más adecuada.",
        },
      ],
    },
    {
      id: "3-4-6",
      titulo: "Medición de la capacidad con unidades estándar",
      objetivo: "Usar litros y mililitros para medir y comparar capacidades.",
      concepto_clave: "1 litro = 1.000 mililitros. La capacidad mide cuánto líquido puede contener un recipiente.",
      explicacion: [
        "La CAPACIDAD nos dice cuánto líquido puede contener un recipiente. Las unidades son el litro (L) y el mililitro (mL).",
        "1 litro = 1.000 mililitros. Una cucharada tiene unos 15 mL, un vaso tiene unos 250 mL, una botella de agua tiene 500 mL o 1 L.",
        "En Colombia, los líquidos como leche, jugos y aceite se venden por litros y mililitros.",
      ],
      ejemplos: [
        {
          enunciado: "Una receta necesita 500 mL de leche. ¿Cuántos litros es?",
          pasos: [
            { texto: "1.000 mL = 1 L" },
            { texto: "500 mL = 500 ÷ 1.000 L = 0,5 L" },
          ],
          resultado: "500 mL = 0,5 L (medio litro)",
        },
        {
          enunciado: "Un tanque tiene 3,5 L de agua. ¿Cuántos mL es?",
          pasos: [
            { texto: "1 L = 1.000 mL" },
            { texto: "3,5 L = 3,5 × 1.000 = 3.500 mL" },
          ],
          resultado: "3,5 L = 3.500 mL",
        },
      ],
      ejercicios: [
        {
          id: "3-4-6-e1",
          enunciado: "Convierte 2 L a mililitros",
          tipo: "numero",
          respuesta: "2000",
          pista: "1 L = 1.000 mL.",
          explicacion: "2 L × 1.000 = 2.000 mL.",
        },
        {
          id: "3-4-6-e2",
          enunciado: "¿Cuántos vasos de 250 mL caben en 1 L?",
          tipo: "numero",
          respuesta: "4",
          pista: "1 L = 1.000 mL. ¿Cuántas veces cabe 250 en 1.000?",
          explicacion: "1.000 ÷ 250 = 4 vasos.",
        },
        {
          id: "3-4-6-e3",
          enunciado: "Una jarra tiene 1,5 L de limonada. Si se sirven 4 vasos de 250 mL, ¿cuánto queda?",
          tipo: "numero",
          respuesta: "500",
          pista: "1,5 L = 1.500 mL. Cuatro vasos = 4 × 250 mL = 1.000 mL.",
          explicacion: "1.500 mL - (4 × 250 mL) = 1.500 - 1.000 = 500 mL quedan.",
        },
        {
          id: "3-4-6-e4",
          enunciado: "¿Cuál es la unidad correcta para medir la cantidad de agua de un río?",
          tipo: "seleccion",
          opciones: ["mL", "L", "m³ (metros cúbicos)", "kg"],
          respuesta: "m³ (metros cúbicos)",
          pista: "Para cantidades muy grandes de agua se usa una unidad más grande.",
          explicacion: "Para ríos y grandes volúmenes se usan metros cúbicos (m³) o millones de litros. Los mL y L son para cantidades pequeñas.",
        },
      ],
    },
    {
      id: "3-4-7",
      titulo: "Medición del volumen con unidades no estándar",
      objetivo: "Comprender el volumen como espacio que ocupa un cuerpo usando unidades no estándar.",
      concepto_clave: "El volumen es el espacio que ocupa un objeto. Se mide contando cuántas unidades caben en él.",
      explicacion: [
        "El VOLUMEN mide el espacio que ocupa un objeto en tres dimensiones (largo, ancho y alto). Diferente al área que es en 2 dimensiones.",
        "Podemos medir volumen con cubitos: ¿cuántos cubitos de igual tamaño necesito para llenar una caja? Ese número es el volumen.",
        "La unidad estándar de volumen es el centímetro cúbico (cm³): el volumen de un cubito de 1 cm × 1 cm × 1 cm.",
      ],
      ejemplos: [
        {
          enunciado: "Una caja se llena con 24 cubitos de madera iguales. ¿Cuál es su volumen en 'cubitos'?",
          pasos: [
            { texto: "Contamos cuántos cubitos caben" },
            { texto: "Caben 24 cubitos" },
          ],
          resultado: "El volumen de la caja es 24 cubitos",
        },
        {
          enunciado: "Una figura tiene 2 cubitos de largo, 3 de ancho y 2 de alto. ¿Cuántos cubitos son en total?",
          pasos: [
            { texto: "V = largo × ancho × alto" },
            { texto: "V = 2 × 3 × 2 = 12 cubitos" },
          ],
          resultado: "El volumen es 12 cubitos",
        },
      ],
      ejercicios: [
        {
          id: "3-4-7-e1",
          enunciado: "Una caja tiene 3 capas de 8 cubitos cada una. ¿Cuál es el volumen total?",
          tipo: "numero",
          respuesta: "24",
          pista: "Multiplica el número de capas por los cubitos en cada capa.",
          explicacion: "3 capas × 8 cubitos = 24 cubitos de volumen.",
        },
        {
          id: "3-4-7-e2",
          enunciado: "¿En cuántas dimensiones se mide el volumen?",
          tipo: "numero",
          respuesta: "3",
          pista: "Largo, ancho y... ¿qué más?",
          explicacion: "El volumen se mide en 3 dimensiones: largo, ancho y alto.",
        },
        {
          id: "3-4-7-e3",
          enunciado: "¿Qué diferencia hay entre área y volumen?",
          tipo: "texto",
          respuesta: "El área mide superficie (2D); el volumen mide el espacio interior de un cuerpo (3D)",
          pista: "Piensa en la diferencia entre una hoja de papel y una caja.",
          explicacion: "El área mide la superficie de una figura plana (2 dimensiones). El volumen mide el espacio que ocupa un cuerpo (3 dimensiones).",
        },
        {
          id: "3-4-7-e4",
          enunciado: "Un cubo tiene 4 cm de lado. ¿Cuántos cubitos de 1 cm³ necesitas para llenarlo?",
          tipo: "numero",
          respuesta: "64",
          pista: "V = lado × lado × lado = 4 × 4 × 4.",
          explicacion: "V = 4 × 4 × 4 = 64 cm³.",
        },
      ],
    },
    {
      id: "3-4-8",
      titulo: "Horas, minutos y segundos",
      objetivo: "Leer el reloj y convertir entre horas, minutos y segundos.",
      concepto_clave: "1 hora = 60 minutos | 1 minuto = 60 segundos | 1 hora = 3.600 segundos",
      explicacion: [
        "El tiempo se mide con el reloj. Las unidades son: horas (h), minutos (min) y segundos (s).",
        "En el reloj analógico: el manecilla corta marca las horas, la larga los minutos, y la más fina (si hay) los segundos.",
        "Conversiones: 1 hora = 60 minutos. 1 minuto = 60 segundos. 1 hora = 60 × 60 = 3.600 segundos.",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 2 horas y 30 minutos a solo minutos",
          pasos: [
            { texto: "2 horas = 2 × 60 = 120 minutos" },
            { texto: "120 minutos + 30 minutos = 150 minutos" },
          ],
          resultado: "2 h 30 min = 150 minutos",
        },
        {
          enunciado: "Un partido de fútbol duró 90 minutos. ¿Cuántas horas y minutos son?",
          pasos: [
            { texto: "90 ÷ 60 = 1 hora con residuo 30" },
            { texto: "Residuo: 90 - 60 = 30 minutos" },
          ],
          resultado: "90 minutos = 1 hora y 30 minutos",
        },
      ],
      ejercicios: [
        {
          id: "3-4-8-e1",
          enunciado: "¿Cuántos minutos tiene 3 horas?",
          tipo: "numero",
          respuesta: "180",
          pista: "1 hora = 60 min. Multiplica 3 × 60.",
          explicacion: "3 × 60 = 180 minutos.",
        },
        {
          id: "3-4-8-e2",
          enunciado: "¿Cuántas horas son 240 minutos?",
          tipo: "numero",
          respuesta: "4",
          pista: "Divide 240 entre 60.",
          explicacion: "240 ÷ 60 = 4 horas.",
        },
        {
          id: "3-4-8-e3",
          enunciado: "Si son las 3:45 y necesito 30 minutos para llegar, ¿a qué hora llego?",
          tipo: "texto",
          respuesta: "4:15",
          pista: "3:45 + 30 minutos. 45 + 30 = 75 minutos = 1 hora y 15 minutos.",
          explicacion: "3:45 + 30 min = 3:75 = 4:15 (60 min = 1 hora, sobran 15 min).",
        },
        {
          id: "3-4-8-e4",
          enunciado: "¿Cuántos segundos tiene 1 minuto y 30 segundos?",
          tipo: "numero",
          respuesta: "90",
          pista: "1 minuto = 60 segundos. Suma 60 + 30.",
          explicacion: "60 + 30 = 90 segundos.",
        },
      ],
    },
    {
      id: "3-4-9",
      titulo: "Días, semanas y meses",
      objetivo: "Calcular y convertir entre días, semanas y meses en el calendario.",
      concepto_clave: "1 semana = 7 días | 1 mes ≈ 30 días | 1 año = 12 meses = 365 días",
      explicacion: [
        "El calendario nos ayuda a organizar el tiempo a largo plazo. Las unidades son: días, semanas, meses y años.",
        "1 semana = 7 días. Los meses tienen 28, 29, 30 o 31 días (febrero es el único con 28 o 29). 1 año = 12 meses = 365 días (366 en año bisiesto).",
        "Truco para recordar cuántos días tiene cada mes: usa los nudillos de la mano. Los nudillos salientes = 31 días. Los valles = 28/30 días.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuántos días hay en 4 semanas?",
          pasos: [
            { texto: "1 semana = 7 días" },
            { texto: "4 semanas = 4 × 7 días" },
          ],
          resultado: "4 semanas = 28 días",
        },
        {
          enunciado: "Las vacaciones duran 45 días. ¿Cuántas semanas completas son?",
          pasos: [
            { texto: "45 ÷ 7 = 6 semanas con residuo 3" },
            { texto: "6 semanas completas y 3 días más" },
          ],
          resultado: "45 días = 6 semanas y 3 días",
        },
      ],
      ejercicios: [
        {
          id: "3-4-9-e1",
          enunciado: "¿Cuántos días tiene el mes de marzo?",
          tipo: "numero",
          respuesta: "31",
          pista: "Usa el truco de los nudillos: enero (31), febrero (28/29), marzo...",
          explicacion: "Marzo es el tercer mes y tiene 31 días.",
        },
        {
          id: "3-4-9-e2",
          enunciado: "Un proyecto dura 3 semanas y 4 días. ¿Cuántos días son en total?",
          tipo: "numero",
          respuesta: "25",
          pista: "3 semanas = 3 × 7 = 21 días. Suma los 4 días adicionales.",
          explicacion: "3 × 7 = 21 días + 4 días = 25 días en total.",
        },
        {
          id: "3-4-9-e3",
          enunciado: "¿Cuántos meses tienen 30 días? (Enero a diciembre)",
          tipo: "numero",
          respuesta: "4",
          pista: "Los meses con 30 días son: abril, junio, septiembre y noviembre.",
          explicacion: "Abril, junio, septiembre y noviembre tienen 30 días. Son 4 meses.",
        },
        {
          id: "3-4-9-e4",
          enunciado: "Si hoy es 25 de octubre, ¿en cuántos días es el 5 de noviembre?",
          tipo: "numero",
          respuesta: "11",
          pista: "Del 25 al 31 de octubre hay 6 días. Del 1 al 5 de noviembre hay 5 días más.",
          explicacion: "Del 25 al 31 de octubre = 6 días. Del 1 al 5 de noviembre = 5 días. Total: 6 + 5 = 11 días.",
        },
      ],
    },
    {
      id: "3-4-10",
      titulo: "Instrumentos de medida",
      objetivo: "Identificar y usar correctamente los instrumentos de medida apropiados para cada magnitud.",
      concepto_clave: "Cada magnitud tiene su instrumento: regla (longitud), balanza (masa), probeta (capacidad), reloj (tiempo).",
      explicacion: [
        "Para medir cada cosa necesitamos el instrumento correcto. No podemos medir la masa con una regla ni la longitud con una balanza.",
        "Instrumentos comunes: REGLA o METRO (longitud), BALANZA o BÁSCULA (masa), PROBETA o TAZA MEDIDORA (capacidad), RELOJ o CRONÓMETRO (tiempo), TERMÓMETRO (temperatura).",
        "Para usar un instrumento correctamente: hay que leer la escala desde el inicio, mirar de frente (no en ángulo) y respetar las unidades del instrumento.",
      ],
      ejemplos: [
        {
          enunciado: "¿Qué instrumento uso para saber si un bebé tiene fiebre?",
          pasos: [
            { texto: "La fiebre es temperatura alta" },
            { texto: "El instrumento de la temperatura es el termómetro" },
          ],
          resultado: "Uso un TERMÓMETRO para medir la temperatura",
        },
        {
          enunciado: "¿Qué instrumento uso para preparar una receta que pide 200 mL de leche?",
          pasos: [
            { texto: "200 mL es una medida de capacidad" },
            { texto: "Para capacidades pequeñas: taza medidora o probeta" },
          ],
          resultado: "Uso una TAZA MEDIDORA o probeta graduada",
        },
      ],
      ejercicios: [
        {
          id: "3-4-10-e1",
          enunciado: "¿Qué instrumento uso para medir el largo de un cuaderno?",
          tipo: "seleccion",
          opciones: ["Balanza", "Regla", "Termómetro", "Reloj"],
          respuesta: "Regla",
          pista: "El largo es una medida de longitud.",
          explicacion: "La regla mide longitudes como el largo de un cuaderno.",
        },
        {
          id: "3-4-10-e2",
          enunciado: "Para saber cuánto tiempo tardé en correr 100 metros, ¿qué instrumento uso?",
          tipo: "seleccion",
          opciones: ["Balanza", "Metro", "Cronómetro", "Probeta"],
          respuesta: "Cronómetro",
          pista: "Necesito medir tiempo.",
          explicacion: "El cronómetro mide tiempos con precisión de segundos.",
        },
        {
          id: "3-4-10-e3",
          enunciado: "Necesito saber si un paquete de 5 kg de arroz realmente pesa 5 kg. ¿Qué uso?",
          tipo: "seleccion",
          opciones: ["Regla", "Reloj", "Balanza o báscula", "Termómetro"],
          respuesta: "Balanza o báscula",
          pista: "5 kg es una medida de masa.",
          explicacion: "La balanza o báscula mide masa en kg y gramos.",
        },
        {
          id: "3-4-10-e4",
          enunciado: "¿Por qué es importante leer la escala de un instrumento de frente y no en ángulo?",
          tipo: "texto",
          respuesta: "Porque si lees en ángulo ves el marcador en una posición diferente y la lectura es incorrecta",
          pista: "Esto se llama 'error de paralaje'.",
          explicacion: "El error de paralaje ocurre cuando la línea de visión no es perpendicular a la escala, lo que hace que el marcador parezca estar en un valor diferente al real.",
        },
      ],
    },
  ],
}

export default unidad4
