import type { Unidad } from "../tipos"

const unidad1: Unidad = {
  id: 1,
  nombre: "Números grandes y operaciones",
  descripcion: "Aprende a leer, escribir y operar con números hasta los millones.",
  color: "blue",
  icono: "🔢",
  lecciones: [
    {
      id: "3-1-1",
      titulo: "Unidades y decenas de mil",
      objetivo: "Leer, escribir y representar números hasta las decenas de mil.",
      concepto_clave: "Una decena de mil = 10 unidades de mil = 10.000",
      explicacion: [
        "Los números que ya conocemos (unidades, decenas, centenas, unidades de mil) ahora tienen un vecino nuevo: las decenas de mil. Una decena de mil es igual a 10.000.",
        "Para leer un número como 45.320, separamos en grupos: 45 miles y 320 unidades. Lo leemos: cuarenta y cinco mil trescientos veinte.",
        "La tabla de posición nos ayuda a organizar cada cifra en su lugar correcto.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cómo se representa el número 32.450?",
          pasos: [
            { texto: "Identificar decenas de mil", detalle: "3 decenas de mil = 30.000" },
            { texto: "Identificar unidades de mil", detalle: "2 unidades de mil = 2.000" },
            { texto: "Identificar centenas", detalle: "4 centenas = 400" },
            { texto: "Identificar decenas", detalle: "5 decenas = 50" },
            { texto: "Identificar unidades", detalle: "0 unidades = 0" },
          ],
          resultado: "32.450 = 30.000 + 2.000 + 400 + 50 + 0 → Treinta y dos mil cuatrocientos cincuenta",
        },
        {
          enunciado: "Escribe en cifras: veintiún mil setecientos ocho",
          pasos: [
            { texto: "Veintiún mil → 21.000" },
            { texto: "Setecientos → 700" },
            { texto: "Ocho → 8" },
            { texto: "Unimos: 21.000 + 700 + 8" },
          ],
          resultado: "21.708",
        },
        {
          enunciado: "¿Cuál es el valor posicional del 6 en 16.245?",
          pasos: [
            { texto: "Ubico el 6 en la tabla", detalle: "Está en el lugar de las unidades de mil" },
            { texto: "Una unidad de mil = 1.000", detalle: "Entonces 6 × 1.000" },
          ],
          resultado: "El 6 vale 6.000 (seis mil)",
        },
      ],
      ejercicios: [
        {
          id: "3-1-1-e1",
          enunciado: "¿Cuánto vale el dígito 5 en el número 54.200?",
          tipo: "seleccion",
          opciones: ["500", "5.000", "50.000", "50"],
          respuesta: "50.000",
          pista: "Fíjate en qué posición está el 5: ¿unidades de mil o decenas de mil?",
          explicacion: "El 5 está en el lugar de las decenas de mil. 5 × 10.000 = 50.000.",
        },
        {
          id: "3-1-1-e2",
          enunciado: "Escribe en cifras: cuarenta y tres mil ciento veinte",
          tipo: "numero",
          respuesta: "43120",
          pista: "Primero los miles (43.000), luego las centenas (100), luego las decenas (20).",
          explicacion: "43.000 + 100 + 20 = 43.120",
        },
        {
          id: "3-1-1-e3",
          enunciado: "¿Cuál es el número mayor: 28.500 o 30.100?",
          tipo: "seleccion",
          opciones: ["28.500", "30.100", "Son iguales"],
          respuesta: "30.100",
          pista: "Compara primero las decenas de mil: ¿cuál tiene más?",
          explicacion: "30.100 tiene 3 decenas de mil y 28.500 tiene 2. Como 3 > 2, entonces 30.100 es mayor.",
        },
        {
          id: "3-1-1-e4",
          enunciado: "Descompón el número 17.350 como suma de valores posicionales",
          tipo: "texto",
          respuesta: "10000+7000+300+50",
          pista: "Piensa: ¿cuántas decenas de mil? ¿cuántas unidades de mil? ¿centenas? ¿decenas?",
          explicacion: "17.350 = 10.000 + 7.000 + 300 + 50",
        },
      ],
    },
    {
      id: "3-1-2",
      titulo: "Centenas de mil",
      objetivo: "Leer, escribir y representar números hasta las centenas de mil.",
      concepto_clave: "Una centena de mil = 100.000 = 100 unidades de mil",
      explicacion: [
        "Después de las decenas de mil viene un lugar aún más grande: las centenas de mil. Una centena de mil es igual a 100.000 (cien mil).",
        "Un número como 345.670 tiene 3 centenas de mil, 4 decenas de mil, 5 unidades de mil, 6 centenas, 7 decenas y 0 unidades.",
        "Para leer estos números: primero decimos los miles completos (trescientos cuarenta y cinco mil) y luego las unidades (seiscientos setenta).",
      ],
      ejemplos: [
        {
          enunciado: "¿Cómo se lee 205.430?",
          pasos: [
            { texto: "Identifico los miles: 205 miles", detalle: "doscientos cinco mil" },
            { texto: "Identifico las unidades: 430", detalle: "cuatrocientos treinta" },
          ],
          resultado: "Doscientos cinco mil cuatrocientos treinta",
        },
        {
          enunciado: "¿Cuánto vale el 4 en 842.100?",
          pasos: [
            { texto: "Ubico el 4 en la tabla de posición" },
            { texto: "Está en el lugar de las decenas de mil", detalle: "4 × 10.000" },
          ],
          resultado: "El 4 vale 40.000 (cuarenta mil)",
        },
        {
          enunciado: "Escribe en cifras: seiscientos mil noventa y dos",
          pasos: [
            { texto: "Seiscientos mil → 600.000" },
            { texto: "Noventa y dos → 92" },
            { texto: "No hay miles, centenas ni decenas intermedias → ponemos ceros" },
          ],
          resultado: "600.092",
        },
      ],
      ejercicios: [
        {
          id: "3-1-2-e1",
          enunciado: "¿Cuánto vale el dígito 7 en 730.500?",
          tipo: "seleccion",
          opciones: ["7.000", "70.000", "700.000", "700"],
          respuesta: "700.000",
          pista: "El 7 está en la primera posición del número. Es la posición de mayor valor.",
          explicacion: "El 7 está en las centenas de mil: 7 × 100.000 = 700.000",
        },
        {
          id: "3-1-2-e2",
          enunciado: "Escribe en cifras: cuatrocientos veinte mil trescientos cinco",
          tipo: "numero",
          respuesta: "420305",
          pista: "Cuatrocientos veinte mil = 420.000. Trescientos cinco = 305.",
          explicacion: "420.000 + 300 + 5 = 420.305",
        },
        {
          id: "3-1-2-e3",
          enunciado: "Ordena de menor a mayor: 380.000 / 309.000 / 390.500",
          tipo: "texto",
          respuesta: "309000,380000,390500",
          pista: "Compara primero las centenas de mil. Si son iguales, mira las decenas de mil.",
          explicacion: "Todos tienen 3 centenas de mil. Comparamos decenas de mil: 0 < 8 < 9. Orden: 309.000 < 380.000 < 390.500.",
        },
        {
          id: "3-1-2-e4",
          enunciado: "¿Cuántas centenas de mil tiene el número 750.000?",
          tipo: "numero",
          respuesta: "7",
          pista: "Una centena de mil = 100.000. ¿Cuántas veces cabe 100.000 en 750.000?",
          explicacion: "750.000 ÷ 100.000 = 7 centenas de mil (y 50.000 sobrante).",
        },
      ],
    },
    {
      id: "3-1-3",
      titulo: "Los Millones",
      objetivo: "Conocer, leer y escribir el millón como nueva unidad de conteo.",
      concepto_clave: "1 millón = 1.000.000 = 1.000 unidades de mil = 10 centenas de mil",
      explicacion: [
        "Imagina que tienes una caja con 1.000 billetes de $1.000 pesos. ¡Eso sería 1 millón de pesos! El millón es un número enorme: se escribe con 7 cifras.",
        "Para leer un número como 3.250.000 decimos: tres millones doscientos cincuenta mil.",
        "En Colombia, muchos precios, presupuestos y datos de población usan los millones. ¡Por eso es importante conocerlos!",
      ],
      ejemplos: [
        {
          enunciado: "¿Cómo se escribe en cifras: dos millones cuatrocientos mil?",
          pasos: [
            { texto: "Dos millones → 2.000.000" },
            { texto: "Cuatrocientos mil → 400.000" },
            { texto: "Unimos los dos grupos" },
          ],
          resultado: "2.400.000",
        },
        {
          enunciado: "¿Cómo se lee el número 5.030.200?",
          pasos: [
            { texto: "Primero los millones: 5 millones" },
            { texto: "Luego los miles: 030 miles → treinta mil" },
            { texto: "Luego las unidades: 200 → doscientos" },
          ],
          resultado: "Cinco millones treinta mil doscientos",
        },
        {
          enunciado: "Bogotá tiene aproximadamente 8.000.000 de habitantes. ¿Cómo se lee?",
          pasos: [
            { texto: "8 en el lugar de los millones" },
            { texto: "El resto son ceros" },
          ],
          resultado: "Ocho millones de habitantes",
        },
      ],
      ejercicios: [
        {
          id: "3-1-3-e1",
          enunciado: "¿Cuántos ceros tiene el número 1.000.000?",
          tipo: "numero",
          respuesta: "6",
          pista: "Cuenta los ceros después del 1.",
          explicacion: "1.000.000 tiene exactamente 6 ceros. Por eso se dice que el millón tiene 7 cifras.",
        },
        {
          id: "3-1-3-e2",
          enunciado: "Escribe en cifras: un millón trescientos mil",
          tipo: "numero",
          respuesta: "1300000",
          pista: "Un millón = 1.000.000. Trescientos mil = 300.000.",
          explicacion: "1.000.000 + 300.000 = 1.300.000",
        },
        {
          id: "3-1-3-e3",
          enunciado: "¿Cuál de estos números es mayor?",
          tipo: "seleccion",
          opciones: ["980.000", "1.000.000", "999.999"],
          respuesta: "1.000.000",
          pista: "El millón tiene 7 cifras. Los otros tienen solo 6.",
          explicacion: "Un millón (1.000.000) es mayor que cualquier número de 6 cifras.",
        },
        {
          id: "3-1-3-e4",
          enunciado: "Lee este dato: Colombia tiene cerca de 52.000.000 de personas. ¿Cómo se dice?",
          tipo: "texto",
          respuesta: "cincuenta y dos millones",
          pista: "Fíjate en los dos primeros dígitos: 52 millones.",
          explicacion: "52.000.000 se lee cincuenta y dos millones de personas.",
        },
      ],
    },
    {
      id: "3-1-4",
      titulo: "Orden en los números naturales",
      objetivo: "Comparar y ordenar números naturales de mayor a menor y de menor a mayor.",
      concepto_clave: "Para comparar números, empieza por la cifra con mayor valor posicional.",
      explicacion: [
        "Comparar números es como una carrera: gana el que tenga más en el lugar de mayor valor. Primero miramos las centenas de mil, luego las decenas de mil, y así hasta las unidades.",
        "Usamos los símbolos: > (mayor que), < (menor que), = (igual a).",
        "Si dos números tienen diferente cantidad de cifras, el que tiene más cifras es mayor.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuál es mayor: 47.320 o 47.800?",
          pasos: [
            { texto: "Ambos tienen 4 en las decenas de mil ✓ igual" },
            { texto: "Ambos tienen 7 en las unidades de mil ✓ igual" },
            { texto: "Comparamos centenas: 3 vs 8", detalle: "8 > 3" },
          ],
          resultado: "47.800 > 47.320 → el mayor es 47.800",
        },
        {
          enunciado: "Ordena de menor a mayor: 15.200 / 9.800 / 15.020",
          pasos: [
            { texto: "9.800 tiene 4 cifras, los otros tienen 5 → 9.800 es el menor" },
            { texto: "Comparamos 15.200 y 15.020: las primeras dos cifras son iguales (15)" },
            { texto: "Comparamos centenas: 2 vs 0 → 15.020 < 15.200" },
          ],
          resultado: "9.800 < 15.020 < 15.200",
        },
      ],
      ejercicios: [
        {
          id: "3-1-4-e1",
          enunciado: "Coloca el signo correcto: 63.410 ___ 63.401",
          tipo: "seleccion",
          opciones: [">", "<", "="],
          respuesta: ">",
          pista: "Compara cifra por cifra desde la izquierda hasta encontrar una diferencia.",
          explicacion: "63.41(0) vs 63.40(1): en las decenas, 1 > 0. Por eso 63.410 > 63.401.",
        },
        {
          id: "3-1-4-e2",
          enunciado: "¿Cuál es el menor de estos números: 200.000 / 99.999 / 100.001?",
          tipo: "seleccion",
          opciones: ["200.000", "99.999", "100.001"],
          respuesta: "99.999",
          pista: "Cuenta las cifras de cada número.",
          explicacion: "99.999 tiene 5 cifras. Los otros tienen 6 cifras. Con menos cifras = número menor.",
        },
        {
          id: "3-1-4-e3",
          enunciado: "Ordena de mayor a menor: 42.100 / 42.010 / 42.001",
          tipo: "texto",
          respuesta: "42100,42010,42001",
          pista: "Los tres empiezan igual en miles. Compara las centenas.",
          explicacion: "42.100 > 42.010 > 42.001",
        },
        {
          id: "3-1-4-e4",
          enunciado: "¿Cuántos números naturales hay entre 99.998 y 100.001?",
          tipo: "numero",
          respuesta: "2",
          pista: "Lista los números: 99.998, ___, ___, 100.001",
          explicacion: "Entre 99.998 y 100.001 están: 99.999 y 100.000. Son 2 números.",
        },
      ],
    },
    {
      id: "3-1-5",
      titulo: "Adición y sustracción de números naturales",
      objetivo: "Sumar y restar números naturales de hasta 6 cifras con reagrupación.",
      concepto_clave: "Siempre suma o resta columna por columna, de derecha a izquierda.",
      explicacion: [
        "La adición (suma) y la sustracción (resta) funcionan igual con números grandes: organizamos las cifras en columnas según su valor posicional y operamos de derecha a izquierda.",
        "En la suma, cuando el resultado de una columna es 10 o más, 'llevamos' una unidad a la siguiente columna.",
        "En la resta, cuando no alcanza para restar, 'pedimos prestado' a la columna siguiente.",
      ],
      ejemplos: [
        {
          enunciado: "Suma: 34.567 + 28.433",
          pasos: [
            { texto: "Unidades: 7 + 3 = 10 → escribo 0 y llevo 1" },
            { texto: "Decenas: 6 + 3 + 1 (llevado) = 10 → escribo 0 y llevo 1" },
            { texto: "Centenas: 5 + 4 + 1 = 10 → escribo 0 y llevo 1" },
            { texto: "U. de mil: 4 + 8 + 1 = 13 → escribo 3 y llevo 1" },
            { texto: "D. de mil: 3 + 2 + 1 = 6" },
          ],
          resultado: "34.567 + 28.433 = 63.000",
        },
        {
          enunciado: "Resta: 50.000 - 13.475",
          pasos: [
            { texto: "Unidades: no puedo 0 - 5, pido prestado → 10 - 5 = 5" },
            { texto: "Decenas: (0-1 prestado) = -1, pido prestado → 10 - 1 - 7 = 2" },
            { texto: "Centenas: (0-1 prestado) = -1, pido prestado → 10 - 1 - 4 = 5" },
            { texto: "U. de mil: (0-1 prestado) = -1, pido prestado → 10 - 1 - 3 = 6" },
            { texto: "D. de mil: (5-1 prestado) = 4 - 1 = 3" },
          ],
          resultado: "50.000 - 13.475 = 36.525",
        },
      ],
      ejercicios: [
        {
          id: "3-1-5-e1",
          enunciado: "Calcula: 45.230 + 37.480",
          tipo: "numero",
          respuesta: "82710",
          pista: "Suma columna por columna desde las unidades. No olvides llevar cuando el resultado sea 10 o más.",
          explicacion: "45.230 + 37.480 = 82.710",
        },
        {
          id: "3-1-5-e2",
          enunciado: "Calcula: 73.000 - 28.650",
          tipo: "numero",
          respuesta: "44350",
          pista: "Necesitarás pedir prestado varias veces. Empieza por las unidades.",
          explicacion: "73.000 - 28.650 = 44.350",
        },
        {
          id: "3-1-5-e3",
          enunciado: "Una finca tiene 25.400 metros de terreno. Vendió 8.750 metros. ¿Cuántos metros le quedan?",
          tipo: "numero",
          respuesta: "16650",
          pista: "Este es un problema de resta: total - vendido = lo que queda.",
          explicacion: "25.400 - 8.750 = 16.650 metros",
        },
        {
          id: "3-1-5-e4",
          enunciado: "¿Cuál es el número que sumado a 14.325 da 30.000?",
          tipo: "numero",
          respuesta: "15675",
          pista: "Si A + B = 30.000 y A = 14.325, entonces B = 30.000 - 14.325.",
          explicacion: "30.000 - 14.325 = 15.675",
        },
      ],
    },
    {
      id: "3-1-6",
      titulo: "Redondeo y estimación de sumas y diferencias",
      objetivo: "Redondear números y estimar resultados de sumas y restas.",
      concepto_clave: "Para redondear: si el dígito siguiente es 5 o más, subes; si es menos de 5, bajas.",
      explicacion: [
        "Estimar significa calcular un resultado aproximado sin hacer la operación exacta. Es muy útil en la vida diaria cuando queremos saber 'más o menos cuánto' algo vale.",
        "Para estimar, primero redondeamos los números y luego operamos con los números redondeados.",
        "Ejemplo: si una camisa cuesta $28.900 y un pantalón $41.200, podemos estimar que juntos cuestan alrededor de $70.000 (redondeando a decenas de mil).",
      ],
      ejemplos: [
        {
          enunciado: "Redondea 43.672 a la decena de mil más cercana",
          pasos: [
            { texto: "La decena de mil donde está: 40.000" },
            { texto: "La siguiente decena de mil: 50.000" },
            { texto: "El dígito de las unidades de mil es 3 (< 5)", detalle: "Entonces redondeamos hacia abajo" },
          ],
          resultado: "43.672 ≈ 40.000",
        },
        {
          enunciado: "Estima la suma: 27.400 + 31.900",
          pasos: [
            { texto: "Redondeamos a decenas de mil: 27.400 ≈ 30.000" },
            { texto: "Redondeamos: 31.900 ≈ 30.000" },
            { texto: "Estimamos: 30.000 + 30.000 = 60.000" },
          ],
          resultado: "La suma es aproximadamente 60.000 (el resultado exacto es 59.300)",
        },
      ],
      ejercicios: [
        {
          id: "3-1-6-e1",
          enunciado: "Redondea 76.500 a la decena de mil más cercana",
          tipo: "seleccion",
          opciones: ["70.000", "80.000", "75.000", "76.000"],
          respuesta: "80.000",
          pista: "El dígito de las unidades de mil es 6. ¿Es mayor o menor que 5?",
          explicacion: "El dígito de unidades de mil es 6 (≥ 5), así que redondeamos hacia arriba: 80.000.",
        },
        {
          id: "3-1-6-e2",
          enunciado: "Estima la diferencia: 62.800 - 19.300",
          tipo: "seleccion",
          opciones: ["40.000", "50.000", "30.000", "60.000"],
          respuesta: "40.000",
          pista: "Redondea cada número a la decena de mil más cercana antes de restar.",
          explicacion: "62.800 ≈ 60.000 y 19.300 ≈ 20.000. Estimamos: 60.000 - 20.000 = 40.000.",
        },
        {
          id: "3-1-6-e3",
          enunciado: "Un televisor cuesta $1.289.000 y una nevera $1.650.000. Estima cuánto cuestan en total redondeando a la centena de mil.",
          tipo: "numero",
          respuesta: "2900000",
          pista: "Redondea cada precio a la centena de mil más cercana y luego suma.",
          explicacion: "$1.289.000 ≈ $1.300.000 y $1.650.000 ≈ $1.700.000. Estimamos: $1.300.000 + $1.700.000 = $2.900.000.",
        },
        {
          id: "3-1-6-e4",
          enunciado: "¿Es la estimación de 48.700 + 31.200 más cercana a 80.000 o a 90.000?",
          tipo: "seleccion",
          opciones: ["80.000", "90.000"],
          respuesta: "80.000",
          pista: "Redondea: 48.700 ≈ 50.000 y 31.200 ≈ 30.000.",
          explicacion: "50.000 + 30.000 = 80.000. La estimación es más cercana a 80.000.",
        },
      ],
    },
    {
      id: "3-1-7",
      titulo: "Repaso de las tablas de multiplicar",
      objetivo: "Recordar y aplicar con fluidez las tablas de multiplicar del 1 al 10.",
      concepto_clave: "La multiplicación es una suma repetida: 4 × 3 significa sumar 4 tres veces (4+4+4=12).",
      explicacion: [
        "Las tablas de multiplicar son herramientas que usamos toda la vida. Si las sabemos de memoria, podemos resolver problemas más rápido.",
        "Un truco para la tabla del 9: los dedos de las manos. Pon los 10 dedos extendidos. Para 9 × 3: dobla el tercer dedo. A la izquierda quedan 2 dedos (decenas) y a la derecha 7 dedos (unidades) → 27.",
        "Recuerda: el orden no importa en la multiplicación. 6 × 4 = 4 × 6 = 24 (propiedad conmutativa).",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuánto es 7 × 8?",
          pasos: [
            { texto: "Puedo pensarlo como 7 × 8 = 7 × (4 + 4)" },
            { texto: "7 × 4 = 28" },
            { texto: "28 + 28 = 56" },
          ],
          resultado: "7 × 8 = 56",
        },
        {
          enunciado: "En un salón hay 6 filas con 9 pupitres cada una. ¿Cuántos pupitres hay en total?",
          pasos: [
            { texto: "Total = filas × pupitres por fila" },
            { texto: "6 × 9 = 54" },
          ],
          resultado: "Hay 54 pupitres en total",
        },
      ],
      ejercicios: [
        {
          id: "3-1-7-e1",
          enunciado: "¿Cuánto es 8 × 7?",
          tipo: "numero",
          respuesta: "56",
          pista: "8 × 7 es lo mismo que 7 × 8. Piénsalo como 8 grupos de 7.",
          explicacion: "8 × 7 = 56. También puedes pensarlo como 8 × 7 = (8 × 5) + (8 × 2) = 40 + 16 = 56.",
        },
        {
          id: "3-1-7-e2",
          enunciado: "¿Cuánto es 9 × 6?",
          tipo: "numero",
          respuesta: "54",
          pista: "Usa el truco de los dedos para la tabla del 9: dobla el 6to dedo.",
          explicacion: "9 × 6 = 54. Al doblar el 6to dedo: 5 a la izquierda, 4 a la derecha → 54.",
        },
        {
          id: "3-1-7-e3",
          enunciado: "Una caja tiene 7 pisos y cada piso tiene 8 botellas. ¿Cuántas botellas hay?",
          tipo: "numero",
          respuesta: "56",
          pista: "Multiplica los pisos por la cantidad de botellas en cada piso.",
          explicacion: "7 × 8 = 56 botellas en total.",
        },
        {
          id: "3-1-7-e4",
          enunciado: "¿Qué número va en el espacio? 6 × ___ = 42",
          tipo: "numero",
          respuesta: "7",
          pista: "¿Por qué número multiplicas 6 para obtener 42? Recorre la tabla del 6.",
          explicacion: "6 × 7 = 42. Entonces el número es 7.",
        },
      ],
    },
    {
      id: "3-1-8",
      titulo: "Multiplicación por una cifra",
      objetivo: "Multiplicar números de varias cifras por un número de una sola cifra.",
      concepto_clave: "Multiplicamos cifra por cifra de derecha a izquierda, llevando cuando el resultado supera 9.",
      explicacion: [
        "Cuando multiplicamos un número grande por un número de una cifra, lo hacemos en partes: multiplicamos cada dígito por separado, de derecha a izquierda.",
        "Si el resultado de multiplicar una cifra es mayor que 9, 'llevamos' las decenas a la siguiente posición.",
        "Por ejemplo, para 234 × 3: primero 4 × 3 = 12 (escribo 2, llevo 1), luego 3 × 3 + 1 = 10 (escribo 0, llevo 1), luego 2 × 3 + 1 = 7.",
      ],
      ejemplos: [
        {
          enunciado: "Calcula 4.235 × 3",
          pasos: [
            { texto: "5 × 3 = 15 → escribo 5, llevo 1" },
            { texto: "3 × 3 + 1 = 10 → escribo 0, llevo 1" },
            { texto: "2 × 3 + 1 = 7 → escribo 7" },
            { texto: "4 × 3 = 12 → escribo 12" },
          ],
          resultado: "4.235 × 3 = 12.705",
        },
        {
          enunciado: "Una granja tiene 5 corrales y en cada uno hay 2.148 pollos. ¿Cuántos pollos hay en total?",
          pasos: [
            { texto: "Total = 2.148 × 5" },
            { texto: "8 × 5 = 40 → escribo 0, llevo 4" },
            { texto: "4 × 5 + 4 = 24 → escribo 4, llevo 2" },
            { texto: "1 × 5 + 2 = 7 → escribo 7" },
            { texto: "2 × 5 = 10 → escribo 10" },
          ],
          resultado: "2.148 × 5 = 10.740 pollos",
        },
      ],
      ejercicios: [
        {
          id: "3-1-8-e1",
          enunciado: "Calcula 3.214 × 4",
          tipo: "numero",
          respuesta: "12856",
          pista: "Empieza por las unidades: 4 × 4 = 16. Escribe el 6, lleva el 1.",
          explicacion: "3.214 × 4: (4×4=16, 1×4+1=5, 2×4=8, 3×4=12) → 12.856",
        },
        {
          id: "3-1-8-e2",
          enunciado: "Calcula 6.053 × 7",
          tipo: "numero",
          respuesta: "42371",
          pista: "Cuidado con el 0 en las decenas: 0 × 7 = 0.",
          explicacion: "6.053 × 7: (3×7=21, 5×7+2=37, 0×7+3=3, 6×7=42) → 42.371",
        },
        {
          id: "3-1-8-e3",
          enunciado: "Una escuela compra 8 cajas de lápices. Cada caja tiene 1.250 lápices. ¿Cuántos lápices compraron?",
          tipo: "numero",
          respuesta: "10000",
          pista: "Multiplica 1.250 × 8.",
          explicacion: "1.250 × 8 = 10.000 lápices",
        },
        {
          id: "3-1-8-e4",
          enunciado: "¿Qué número multiplicado por 6 da 31.254?",
          tipo: "numero",
          respuesta: "5209",
          pista: "Si A × 6 = 31.254, entonces A = 31.254 ÷ 6.",
          explicacion: "31.254 ÷ 6 = 5.209. Verificación: 5.209 × 6 = 31.254 ✓",
        },
      ],
    },
    {
      id: "3-1-9",
      titulo: "Multiplicación por dos o más cifras",
      objetivo: "Multiplicar números por factores de dos o más cifras usando el algoritmo estándar.",
      concepto_clave: "Al multiplicar por decenas, desplaza el resultado una posición a la izquierda (agrega un cero).",
      explicacion: [
        "Cuando el multiplicador tiene dos cifras, dividimos la operación en dos partes: primero multiplicamos por las unidades y luego por las decenas.",
        "El resultado de multiplicar por las decenas se escribe una posición a la izquierda (es como agregar un cero al final).",
        "Al final, sumamos los dos resultados parciales para obtener el producto final.",
      ],
      ejemplos: [
        {
          enunciado: "Calcula 234 × 23",
          pasos: [
            { texto: "Multiplico 234 × 3 (unidades) = 702" },
            { texto: "Multiplico 234 × 20 (decenas) = 4.680", detalle: "Es 234 × 2 = 468, desplazado una posición" },
            { texto: "Sumo los resultados parciales: 702 + 4.680" },
          ],
          resultado: "234 × 23 = 5.382",
        },
        {
          enunciado: "Un colegio tiene 45 salones y en cada uno hay 32 estudiantes. ¿Cuántos estudiantes hay?",
          pasos: [
            { texto: "Total = 45 × 32" },
            { texto: "45 × 2 = 90" },
            { texto: "45 × 30 = 1.350" },
            { texto: "90 + 1.350 = 1.440" },
          ],
          resultado: "45 × 32 = 1.440 estudiantes",
        },
      ],
      ejercicios: [
        {
          id: "3-1-9-e1",
          enunciado: "Calcula 312 × 14",
          tipo: "numero",
          respuesta: "4368",
          pista: "Multiplica 312 × 4 = 1.248, luego 312 × 10 = 3.120. Suma los dos resultados.",
          explicacion: "312 × 4 = 1.248 y 312 × 10 = 3.120. Total: 1.248 + 3.120 = 4.368",
        },
        {
          id: "3-1-9-e2",
          enunciado: "Calcula 425 × 21",
          tipo: "numero",
          respuesta: "8925",
          pista: "425 × 1 = 425, luego 425 × 20 = 8.500.",
          explicacion: "425 × 1 = 425 y 425 × 20 = 8.500. Total: 425 + 8.500 = 8.925",
        },
        {
          id: "3-1-9-e3",
          enunciado: "Una fábrica produce 135 juguetes por hora. ¿Cuántos juguetes produce en 24 horas?",
          tipo: "numero",
          respuesta: "3240",
          pista: "Multiplica 135 × 24.",
          explicacion: "135 × 4 = 540 y 135 × 20 = 2.700. Total: 540 + 2.700 = 3.240 juguetes.",
        },
        {
          id: "3-1-9-e4",
          enunciado: "¿Cuánto es 200 × 35?",
          tipo: "numero",
          respuesta: "7000",
          pista: "Puedes pensar: 2 × 35 = 70, luego agrega los dos ceros del 200.",
          explicacion: "200 × 35 = 2 × 100 × 35 = 70 × 100 = 7.000",
        },
      ],
    },
    {
      id: "3-1-10",
      titulo: "La división y sus términos",
      objetivo: "Identificar los términos de la división y comprender su significado.",
      concepto_clave: "Dividendo ÷ Divisor = Cociente (con posible Residuo). La división es repartir en partes iguales.",
      explicacion: [
        "La división nos sirve para repartir una cantidad en grupos iguales. Por ejemplo, si tienes 20 manzanas y quieres repartirlas en 4 grupos iguales, necesitas dividir.",
        "Los términos de la división son: Dividendo (lo que se divide), Divisor (entre qué se divide), Cociente (el resultado) y Residuo (lo que sobra).",
        "Verificamos una división con la prueba: (Divisor × Cociente) + Residuo = Dividendo.",
      ],
      ejemplos: [
        {
          enunciado: "Identifica los términos en: 25 ÷ 4 = 6 residuo 1",
          pasos: [
            { texto: "Dividendo: 25 (el número que se divide)" },
            { texto: "Divisor: 4 (entre qué se divide)" },
            { texto: "Cociente: 6 (el resultado)" },
            { texto: "Residuo: 1 (lo que sobra)" },
          ],
          resultado: "Verificación: (4 × 6) + 1 = 24 + 1 = 25 ✓",
        },
        {
          enunciado: "Tengo 30 fichas y las reparto en 7 grupos. ¿Cuántas fichas tiene cada grupo y cuántas sobran?",
          pasos: [
            { texto: "30 ÷ 7 = ?" },
            { texto: "7 × 4 = 28 (cabe 4 veces)" },
            { texto: "Residuo: 30 - 28 = 2" },
          ],
          resultado: "Cada grupo tiene 4 fichas y sobran 2",
        },
      ],
      ejercicios: [
        {
          id: "3-1-10-e1",
          enunciado: "En 45 ÷ 6 = 7 residuo 3, ¿cuál es el dividendo?",
          tipo: "numero",
          respuesta: "45",
          pista: "El dividendo es el número que se divide, el más grande al inicio.",
          explicacion: "El dividendo es 45. Es el número que estamos dividiendo.",
        },
        {
          id: "3-1-10-e2",
          enunciado: "Verifica si esta división es correcta: 38 ÷ 5 = 7 residuo 4",
          tipo: "seleccion",
          opciones: ["Sí es correcta", "No es correcta"],
          respuesta: "No es correcta",
          pista: "Aplica la prueba: (Divisor × Cociente) + Residuo = Dividendo.",
          explicacion: "(5 × 7) + 4 = 35 + 4 = 39 ≠ 38. La división está incorrecta. Debería ser 38 ÷ 5 = 7 residuo 3.",
        },
        {
          id: "3-1-10-e3",
          enunciado: "Reparto 52 dulces entre 8 niños. ¿Cuántos recibe cada uno y cuántos sobran?",
          tipo: "texto",
          respuesta: "6 dulces, sobran 4",
          pista: "¿Cuántas veces cabe 8 en 52? 8 × 6 = 48.",
          explicacion: "52 ÷ 8 = 6 residuo 4. Cada niño recibe 6 dulces y sobran 4.",
        },
        {
          id: "3-1-10-e4",
          enunciado: "¿Cuándo el residuo de una división es 0?",
          tipo: "seleccion",
          opciones: [
            "Cuando el divisor es mayor al dividendo",
            "Cuando la división es exacta (no sobra nada)",
            "Cuando el cociente es 0",
          ],
          respuesta: "Cuando la división es exacta (no sobra nada)",
          pista: "Piensa en 20 ÷ 4 = 5. ¿Sobra algo?",
          explicacion: "El residuo es 0 cuando la división es exacta, es decir, el dividendo se divide perfectamente.",
        },
      ],
    },
    {
      id: "3-1-11",
      titulo: "Divisor de una cifra",
      objetivo: "Realizar divisiones con divisor de una cifra usando el algoritmo estándar.",
      concepto_clave: "En la división larga: Divide → Multiplica → Resta → Baja. Repite hasta terminar.",
      explicacion: [
        "Para dividir un número grande entre un número de una cifra, usamos la división larga. El proceso es: Divide, Multiplica, Resta, Baja (DMRB).",
        "Empezamos por la izquierda del dividendo y trabajamos cifra por cifra hasta terminar.",
        "Si no alcanza para dividir la primera cifra, incluimos la siguiente también.",
      ],
      ejemplos: [
        {
          enunciado: "Divide 856 ÷ 4",
          pasos: [
            { texto: "¿Cuántas veces cabe 4 en 8? → 2 veces. 2 × 4 = 8. Resto: 8-8=0" },
            { texto: "Bajo el 5: tengo 05. ¿Cuántas veces cabe 4 en 5? → 1 vez. 1 × 4 = 4. Resto: 5-4=1" },
            { texto: "Bajo el 6: tengo 16. ¿Cuántas veces cabe 4 en 16? → 4 veces. 4 × 4 = 16. Resto: 0" },
          ],
          resultado: "856 ÷ 4 = 214",
        },
        {
          enunciado: "Divide 1.035 ÷ 5",
          pasos: [
            { texto: "¿Cabe 5 en 1? No. Tomamos 10. ¿Cuántas veces cabe 5 en 10? → 2. Resto: 0" },
            { texto: "Bajo el 3: tengo 03. ¿Cuántas veces cabe 5 en 3? → 0 veces. Escribo 0. Resto: 3" },
            { texto: "Bajo el 5: tengo 35. ¿Cuántas veces cabe 5 en 35? → 7. 7 × 5 = 35. Resto: 0" },
          ],
          resultado: "1.035 ÷ 5 = 207",
        },
      ],
      ejercicios: [
        {
          id: "3-1-11-e1",
          enunciado: "Calcula 936 ÷ 3",
          tipo: "numero",
          respuesta: "312",
          pista: "Empieza: ¿cuántas veces cabe 3 en 9? (3 veces). Sigue con las siguientes cifras.",
          explicacion: "936 ÷ 3 = 312. Verificación: 312 × 3 = 936 ✓",
        },
        {
          id: "3-1-11-e2",
          enunciado: "Calcula 4.248 ÷ 6",
          tipo: "numero",
          respuesta: "708",
          pista: "¿Cabe 6 en 4? No. Toma 42: ¿cuántas veces cabe 6? (7 veces). Sigue.",
          explicacion: "4.248 ÷ 6 = 708. Verificación: 708 × 6 = 4.248 ✓",
        },
        {
          id: "3-1-11-e3",
          enunciado: "Hay 2.856 estudiantes en 8 jornadas iguales. ¿Cuántos estudiantes hay en cada jornada?",
          tipo: "numero",
          respuesta: "357",
          pista: "Divide 2.856 ÷ 8.",
          explicacion: "2.856 ÷ 8 = 357 estudiantes por jornada.",
        },
        {
          id: "3-1-11-e4",
          enunciado: "Calcula 5.432 ÷ 7 y escribe el cociente y el residuo",
          tipo: "texto",
          respuesta: "cociente 776 residuo 0",
          pista: "Divide paso a paso. Cuando termines, verifica: 776 × 7 = ?",
          explicacion: "5.432 ÷ 7 = 776 con residuo 0. Verificación: 776 × 7 = 5.432 ✓",
        },
      ],
    },
    {
      id: "3-1-12",
      titulo: "Divisor de dos cifras",
      objetivo: "Realizar divisiones con divisor de dos cifras.",
      concepto_clave: "Con divisor de dos cifras, estimamos cuántas veces cabe el divisor en las primeras cifras del dividendo.",
      explicacion: [
        "Dividir entre dos cifras es más difícil porque el divisor es más grande. Necesitamos tomar dos o más cifras del dividendo para empezar.",
        "Un truco es 'redondear' el divisor para estimar: si el divisor es 23, pensamos 'más o menos como 20'. ¿Cuántas veces cabe 20 en el número que tengo?",
        "Si la estimación es muy grande o muy pequeña, la ajustamos hasta que encaje.",
      ],
      ejemplos: [
        {
          enunciado: "Calcula 546 ÷ 13",
          pasos: [
            { texto: "Tomo 54. ¿Cuántas veces cabe 13? → estimo con 10: 54÷10≈5. Pruebo 4: 4×13=52. Resto: 54-52=2" },
            { texto: "Bajo el 6: tengo 26. ¿Cuántas veces cabe 13 en 26? → 2 veces. 2×13=26. Resto: 0" },
          ],
          resultado: "546 ÷ 13 = 42",
        },
        {
          enunciado: "Calcula 840 ÷ 24",
          pasos: [
            { texto: "Tomo 84. ¿Cuántas veces cabe 24? → estimo: 24≈20, 84÷20≈4. Pruebo 3: 3×24=72, resto 12. Pruebo 3 ✓" },
            { texto: "Bajo el 0: tengo 120. ¿Cuántas veces cabe 24 en 120? → 5 veces. 5×24=120. Resto: 0" },
          ],
          resultado: "840 ÷ 24 = 35",
        },
      ],
      ejercicios: [
        {
          id: "3-1-12-e1",
          enunciado: "Calcula 680 ÷ 20",
          tipo: "numero",
          respuesta: "34",
          pista: "Divide 68 ÷ 20 = 3 con resto 8. Luego baja el 0 y divide 80 ÷ 20.",
          explicacion: "680 ÷ 20 = 34. Verificación: 34 × 20 = 680 ✓",
        },
        {
          id: "3-1-12-e2",
          enunciado: "Calcula 756 ÷ 12",
          tipo: "numero",
          respuesta: "63",
          pista: "Toma 75 ÷ 12: ¿cuántas veces cabe 12? (6 veces, 6×12=72). Baja el 6.",
          explicacion: "756 ÷ 12 = 63. Verificación: 63 × 12 = 756 ✓",
        },
        {
          id: "3-1-12-e3",
          enunciado: "Se distribuyen 504 libros en cajas de 14 libros cada una. ¿Cuántas cajas se necesitan?",
          tipo: "numero",
          respuesta: "36",
          pista: "Divide 504 ÷ 14.",
          explicacion: "504 ÷ 14 = 36 cajas.",
        },
        {
          id: "3-1-12-e4",
          enunciado: "¿Cuánto es 960 ÷ 32?",
          tipo: "numero",
          respuesta: "30",
          pista: "Toma 96 ÷ 32: ¿cuántas veces cabe 32? Luego baja el 0.",
          explicacion: "96 ÷ 32 = 3 exacto. Luego bajo 0: 0 ÷ 32 = 0. Resultado: 30.",
        },
      ],
    },
    {
      id: "3-1-13",
      titulo: "Números pares e impares",
      objetivo: "Clasificar números naturales en pares e impares y reconocer sus propiedades.",
      concepto_clave: "Un número par termina en 0, 2, 4, 6 u 8. Un número impar termina en 1, 3, 5, 7 o 9.",
      explicacion: [
        "Los números pares son los que se pueden dividir entre 2 sin que sobre nada (residuo 0). Por ejemplo: 4 ÷ 2 = 2 exacto → 4 es par.",
        "Los números impares son los que al dividirlos entre 2 siempre sobra 1. Por ejemplo: 7 ÷ 2 = 3 residuo 1 → 7 es impar.",
        "Truco fácil: solo mira el último dígito. Si termina en 0, 2, 4, 6 u 8 → par. Si termina en 1, 3, 5, 7 o 9 → impar.",
      ],
      ejemplos: [
        {
          enunciado: "¿Es 45.678 par o impar?",
          pasos: [
            { texto: "Miro el último dígito: 8" },
            { texto: "8 es un número par (8 ÷ 2 = 4, sin residuo)" },
          ],
          resultado: "45.678 es PAR",
        },
        {
          enunciado: "¿Cuántos números pares hay entre 1 y 10?",
          pasos: [
            { texto: "Listo los números del 1 al 10: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10" },
            { texto: "Marco los pares: 2, 4, 6, 8, 10" },
          ],
          resultado: "Hay 5 números pares entre 1 y 10",
        },
      ],
      ejercicios: [
        {
          id: "3-1-13-e1",
          enunciado: "¿Es el número 73.245 par o impar?",
          tipo: "seleccion",
          opciones: ["Par", "Impar"],
          respuesta: "Impar",
          pista: "Solo mira el último dígito: ¿qué número es 5?",
          explicacion: "73.245 termina en 5. El 5 es impar (5 ÷ 2 = 2 residuo 1), así que 73.245 es impar.",
        },
        {
          id: "3-1-13-e2",
          enunciado: "¿Cuál de estos es par: 347, 892, 513?",
          tipo: "seleccion",
          opciones: ["347", "892", "513"],
          respuesta: "892",
          pista: "Revisa el último dígito de cada número.",
          explicacion: "892 termina en 2, que es par. 347 termina en 7 (impar) y 513 termina en 3 (impar).",
        },
        {
          id: "3-1-13-e3",
          enunciado: "¿Qué pasa cuando sumas dos números impares? Prueba con 3 + 5, 7 + 9, 1 + 11.",
          tipo: "seleccion",
          opciones: ["El resultado siempre es par", "El resultado siempre es impar", "A veces es par y a veces impar"],
          respuesta: "El resultado siempre es par",
          pista: "Calcula los tres casos y observa si los resultados son pares o impares.",
          explicacion: "3+5=8 (par), 7+9=16 (par), 1+11=12 (par). ¡La suma de dos impares siempre da par!",
        },
        {
          id: "3-1-13-e4",
          enunciado: "El número de estudiantes en un colegio es 1.248. ¿Se pueden organizar en grupos de 2 exactos sin que sobre nadie?",
          tipo: "seleccion",
          opciones: ["Sí, porque 1.248 es par", "No, porque 1.248 es impar"],
          respuesta: "Sí, porque 1.248 es par",
          pista: "¿Cuál es el último dígito de 1.248?",
          explicacion: "1.248 termina en 8, que es par. Por lo tanto, se puede dividir exactamente entre 2.",
        },
      ],
    },
  ],
}

export default unidad1
