import type { Unidad } from "../tipos"

const unidad3: Unidad = {
  id: 3,
  nombre: "Geometría",
  descripcion: "Explora figuras, rectas, ángulos y movimientos en el espacio.",
  color: "purple",
  icono: "📐",
  lecciones: [
    {
      id: "3-3-1",
      titulo: "Recta, semirrecta y segmento",
      objetivo: "Distinguir y representar rectas, semirrectas y segmentos.",
      concepto_clave: "Recta: infinita en dos sentidos. Semirrecta: infinita en un sentido. Segmento: finito con dos extremos.",
      explicacion: [
        "Una RECTA es como una carretera que nunca termina: se extiende infinitamente en los dos sentidos. Se nombra con dos letras o con una letra minúscula.",
        "Una SEMIRRECTA es como un rayo de luz que sale de un punto y va infinitamente en una dirección. Tiene un punto de inicio pero no termina.",
        "Un SEGMENTO es una parte de una recta con dos extremos (puntos de inicio y fin). Es el único de los tres que podemos medir.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cómo identifico cada uno en un dibujo?",
          pasos: [
            { texto: "Recta: ←————————→ (flechas en ambos extremos)" },
            { texto: "Semirrecta: •————————→ (punto en un extremo, flecha en el otro)" },
            { texto: "Segmento: •————————• (puntos en ambos extremos)" },
          ],
          resultado: "La clave está en los extremos: flechas = infinito, puntos = finito",
        },
        {
          enunciado: "¿Es finito o infinito el segmento AB que mide 5 cm?",
          pasos: [
            { texto: "Tiene dos puntos extremos: A y B" },
            { texto: "Podemos medirlo: 5 cm" },
          ],
          resultado: "Es finito. Los segmentos tienen longitud medible.",
        },
      ],
      ejercicios: [
        {
          id: "3-3-1-e1",
          enunciado: "¿Cuál de estos objetos del mundo real se parece más a una recta?",
          tipo: "seleccion",
          opciones: ["Un lápiz", "El horizonte del mar", "Un campo de fútbol", "Una moneda"],
          respuesta: "El horizonte del mar",
          pista: "Piensa en algo que parezca extenderse sin fin en dos direcciones.",
          explicacion: "El horizonte del mar parece una línea que se extiende infinitamente en ambas direcciones, como una recta.",
        },
        {
          id: "3-3-1-e2",
          enunciado: "¿Cuántos extremos tiene una semirrecta?",
          tipo: "numero",
          respuesta: "1",
          pista: "La semirrecta tiene inicio pero no tiene fin.",
          explicacion: "Una semirrecta tiene exactamente 1 extremo (el punto de inicio). El otro lado es infinito.",
        },
        {
          id: "3-3-1-e3",
          enunciado: "¿Cuál tiene longitud medible: una recta, una semirrecta o un segmento?",
          tipo: "seleccion",
          opciones: ["La recta", "La semirrecta", "El segmento", "Los tres"],
          respuesta: "El segmento",
          pista: "Solo lo que tiene dos extremos puede medirse.",
          explicacion: "Solo el segmento puede medirse porque tiene dos extremos definidos. Las rectas y semirrectas son infinitas.",
        },
        {
          id: "3-3-1-e4",
          enunciado: "El borde de la regla representa un ___",
          tipo: "seleccion",
          opciones: ["Recta", "Semirrecta", "Segmento"],
          respuesta: "Segmento",
          pista: "El borde de la regla tiene inicio y fin.",
          explicacion: "El borde de la regla tiene dos extremos definidos y se puede medir: es un segmento.",
        },
      ],
    },
    {
      id: "3-3-2",
      titulo: "Horizontalidad y verticalidad",
      objetivo: "Reconocer y trazar líneas horizontales y verticales en el entorno.",
      concepto_clave: "Horizontal: paralela al suelo (como el horizonte). Vertical: perpendicular al suelo (como un árbol parado).",
      explicacion: [
        "Una línea HORIZONTAL va de lado a lado, paralela al suelo o al nivel del mar. Piensa en la mesa, en el horizonte o en una cama.",
        "Una línea VERTICAL va de arriba abajo, perpendicular al suelo. Piensa en un árbol, una puerta o una pared.",
        "En una cuadrícula: las líneas que van de lado a lado son horizontales y las que van de arriba a abajo son verticales.",
      ],
      ejemplos: [
        {
          enunciado: "Clasifica: el tronco de un árbol, el borde de una mesa",
          pasos: [
            { texto: "Tronco de árbol: va de abajo hacia arriba → VERTICAL" },
            { texto: "Borde de una mesa: va de lado a lado → HORIZONTAL" },
          ],
          resultado: "Árbol = vertical | Mesa = horizontal",
        },
        {
          enunciado: "¿Cuántas líneas horizontales y verticales tiene la letra E?",
          pasos: [
            { texto: "Líneas verticales: 1 (el palo del lado izquierdo)" },
            { texto: "Líneas horizontales: 3 (los tres palitos hacia la derecha)" },
          ],
          resultado: "La letra E tiene 1 vertical y 3 horizontales",
        },
      ],
      ejercicios: [
        {
          id: "3-3-2-e1",
          enunciado: "¿Cómo se llama la línea que va de lado a lado, igual que el horizonte?",
          tipo: "seleccion",
          opciones: ["Vertical", "Horizontal", "Diagonal", "Curva"],
          respuesta: "Horizontal",
          pista: "La palabra 'horizontal' viene de 'horizonte'.",
          explicacion: "La línea horizontal va de lado a lado, paralela al suelo, como el horizonte.",
        },
        {
          id: "3-3-2-e2",
          enunciado: "En el número 1, ¿qué tipo de línea predomina?",
          tipo: "seleccion",
          opciones: ["Horizontal", "Vertical", "Curva"],
          respuesta: "Vertical",
          pista: "El número 1 se dibuja de arriba hacia abajo.",
          explicacion: "El número 1 es principalmente una línea vertical.",
        },
        {
          id: "3-3-2-e3",
          enunciado: "Nombra 2 objetos de tu casa que tengan líneas verticales",
          tipo: "texto",
          respuesta: "puerta,ventana",
          pista: "Busca objetos que vayan de arriba hacia abajo.",
          explicacion: "Ejemplos: puertas, ventanas, columnas, paredes, lápices en posición vertical.",
        },
        {
          id: "3-3-2-e4",
          enunciado: "¿Cuántas líneas verticales hay en la letra H?",
          tipo: "numero",
          respuesta: "2",
          pista: "La H tiene palitos en los lados y uno en el centro.",
          explicacion: "La letra H tiene 2 líneas verticales (las de los lados) y 1 horizontal (el puente del centro).",
        },
      ],
    },
    {
      id: "3-3-3",
      titulo: "Relaciones entre rectas",
      objetivo: "Identificar rectas paralelas, perpendiculares y secantes.",
      concepto_clave: "Paralelas: nunca se cruzan. Perpendiculares: se cruzan en ángulo recto (90°). Secantes: se cruzan en cualquier ángulo.",
      explicacion: [
        "Cuando dos rectas están en el mismo plano, pueden relacionarse de tres formas: paralelas (nunca se encuentran, siempre a la misma distancia), secantes (se cruzan en algún punto) o perpendiculares (caso especial de secantes que forman 4 ángulos rectos de 90°).",
        "Las rectas PARALELAS son como los rieles del tren: siempre a la misma distancia, nunca se tocan.",
        "Las rectas PERPENDICULARES forman una cruz perfecta: el símbolo ⊥ indica perpendicularidad.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cómo son las líneas del cuaderno?",
          pasos: [
            { texto: "Las líneas horizontales del cuaderno nunca se cruzan" },
            { texto: "Siempre están a la misma distancia" },
          ],
          resultado: "Las líneas del cuaderno son PARALELAS entre sí",
        },
        {
          enunciado: "¿Cómo se llaman las rectas que forman la cruz (+)?",
          pasos: [
            { texto: "La línea vertical y la horizontal se cruzan" },
            { texto: "Forman 4 ángulos de 90° cada uno" },
          ],
          resultado: "Son PERPENDICULARES (símbolo ⊥)",
        },
      ],
      ejercicios: [
        {
          id: "3-3-3-e1",
          enunciado: "Las vías del tren nunca se cruzan. ¿Cómo se llaman esas rectas?",
          tipo: "seleccion",
          opciones: ["Perpendiculares", "Paralelas", "Secantes"],
          respuesta: "Paralelas",
          pista: "Si nunca se cruzan, ¿cómo se llaman?",
          explicacion: "Las vías del tren son paralelas: siempre a la misma distancia y nunca se cruzan.",
        },
        {
          id: "3-3-3-e2",
          enunciado: "¿Las calles de una ciudad que se cruzan formando una L son perpendiculares o secantes?",
          tipo: "seleccion",
          opciones: ["Perpendiculares (forman 90°)", "Secantes (forman otro ángulo)"],
          respuesta: "Perpendiculares (forman 90°)",
          pista: "Una esquina en forma de L tiene ángulo de 90°.",
          explicacion: "Las calles que forman esquinas en L se cruzan a 90°: son perpendiculares.",
        },
        {
          id: "3-3-3-e3",
          enunciado: "¿Cuántos pares de lados paralelos tiene un rectángulo?",
          tipo: "numero",
          respuesta: "2",
          pista: "Mira los lados opuestos del rectángulo.",
          explicacion: "Un rectángulo tiene 2 pares de lados paralelos: los dos lados largos paralelos entre sí y los dos lados cortos paralelos entre sí.",
        },
        {
          id: "3-3-3-e4",
          enunciado: "¿Verdadero o falso? Todas las rectas perpendiculares son también secantes.",
          tipo: "seleccion",
          opciones: ["Verdadero", "Falso"],
          respuesta: "Verdadero",
          pista: "¿Las perpendiculares se cruzan? ¿Las secantes se cruzan?",
          explicacion: "Verdadero. Las perpendiculares son un caso especial de secantes: se cruzan (son secantes) y además forman ángulos de 90°.",
        },
      ],
    },
    {
      id: "3-3-4",
      titulo: "Ángulos: clasificación y comparación",
      objetivo: "Identificar y clasificar ángulos en agudos, rectos y obtusos.",
      concepto_clave: "Agudo: menos de 90°. Recto: exactamente 90°. Obtuso: entre 90° y 180°.",
      explicacion: [
        "Un ÁNGULO es la abertura que se forma entre dos rayos que tienen el mismo punto de origen (vértice). Los medimos en grados (°).",
        "ÁNGULO AGUDO: mide menos de 90°. Es como la punta de un triángulo delgado. La palabra 'agudo' significa puntiagudo.",
        "ÁNGULO RECTO: mide exactamente 90°. Es la esquina perfecta de un cuadrado o de la letra L. Lo identificamos con un cuadradito en el vértice.",
        "ÁNGULO OBTUSO: mide más de 90° y menos de 180°. Es más abierto que la esquina de un cuadrado.",
      ],
      ejemplos: [
        {
          enunciado: "Clasifica los ángulos de un triángulo rectángulo",
          pasos: [
            { texto: "Un ángulo mide 90° → RECTO (tiene el cuadradito)" },
            { texto: "Los otros dos miden menos de 90° → AGUDOS" },
          ],
          resultado: "Un triángulo rectángulo tiene 1 ángulo recto y 2 ángulos agudos",
        },
        {
          enunciado: "El minutero del reloj va de las 12 a las 3. ¿Qué tipo de ángulo forma?",
          pasos: [
            { texto: "De las 12 a las 3 es un cuarto de vuelta" },
            { texto: "Un cuarto de vuelta = 90°" },
          ],
          resultado: "Forma un ÁNGULO RECTO",
        },
      ],
      ejercicios: [
        {
          id: "3-3-4-e1",
          enunciado: "Un ángulo mide 45°. ¿Cómo se clasifica?",
          tipo: "seleccion",
          opciones: ["Agudo", "Recto", "Obtuso"],
          respuesta: "Agudo",
          pista: "45° es menor que 90°.",
          explicacion: "45° < 90°, entonces es un ángulo agudo.",
        },
        {
          id: "3-3-4-e2",
          enunciado: "Un ángulo mide 120°. ¿Cómo se clasifica?",
          tipo: "seleccion",
          opciones: ["Agudo", "Recto", "Obtuso"],
          respuesta: "Obtuso",
          pista: "120° es mayor que 90° y menor que 180°.",
          explicacion: "90° < 120° < 180°, entonces es un ángulo obtuso.",
        },
        {
          id: "3-3-4-e3",
          enunciado: "¿Cuántos ángulos rectos tiene un rectángulo?",
          tipo: "numero",
          respuesta: "4",
          pista: "Cuenta las esquinas del rectángulo. ¿Son todas de 90°?",
          explicacion: "Un rectángulo tiene 4 esquinas y todas miden 90°: son 4 ángulos rectos.",
        },
        {
          id: "3-3-4-e4",
          enunciado: "Las agujas de un reloj a las 6:00 forman un ángulo de 180°. ¿Cómo se llama ese ángulo?",
          tipo: "seleccion",
          opciones: ["Agudo", "Recto", "Obtuso", "Llano"],
          respuesta: "Llano",
          pista: "Un ángulo de 180° es una línea recta.",
          explicacion: "Un ángulo de 180° se llama ángulo llano. Forma una línea recta.",
        },
      ],
    },
    {
      id: "3-3-5",
      titulo: "Posiciones y movimientos en el plano",
      objetivo: "Describir posiciones y movimientos usando arriba/abajo, derecha/izquierda, adelante/atrás.",
      concepto_clave: "Para describir posiciones en el plano usamos referencias: arriba-abajo (vertical) y derecha-izquierda (horizontal).",
      explicacion: [
        "El plano es una superficie plana (como la hoja de papel o el piso). Para ubicar objetos en él, usamos palabras de posición: arriba, abajo, a la derecha, a la izquierda.",
        "Cuando seguimos instrucciones de movimiento, debemos ser exactos: '2 pasos a la derecha, 3 pasos arriba' lleva a un lugar diferente que '3 pasos a la derecha, 2 pasos arriba'.",
        "En un plano cuadriculado, podemos contar los cuadros para ser más precisos.",
      ],
      ejemplos: [
        {
          enunciado: "En un mapa, el parque está 3 cuadras al norte (arriba) y 2 cuadras al este (derecha) de la escuela. ¿Cómo llegamos?",
          pasos: [
            { texto: "Partimos de la escuela" },
            { texto: "Movemos 3 cuadras hacia arriba (norte)" },
            { texto: "Movemos 2 cuadras hacia la derecha (este)" },
          ],
          resultado: "Seguimos los pasos en orden y llegamos al parque",
        },
        {
          enunciado: "Un conejo está en la casilla (2,3) de una cuadrícula. Se mueve 4 casillas a la derecha. ¿Dónde queda?",
          pasos: [
            { texto: "Posición inicial: (2, 3)" },
            { texto: "Movimiento: +4 en la dirección horizontal" },
            { texto: "Nueva posición: (2+4, 3) = (6, 3)" },
          ],
          resultado: "El conejo queda en la casilla (6, 3)",
        },
      ],
      ejercicios: [
        {
          id: "3-3-5-e1",
          enunciado: "Si estás mirando al norte, ¿a qué punto cardinal quedaría tu mano derecha?",
          tipo: "seleccion",
          opciones: ["Norte", "Sur", "Este", "Oeste"],
          respuesta: "Este",
          pista: "Norte al frente, sur atrás. ¿Este u oeste a la derecha?",
          explicacion: "Mirando al norte: este (derecha), oeste (izquierda), norte (adelante), sur (atrás).",
        },
        {
          id: "3-3-5-e2",
          enunciado: "Un robot está en la casilla 5 de una fila. Da 3 pasos hacia la izquierda. ¿En qué casilla queda?",
          tipo: "numero",
          respuesta: "2",
          pista: "Empieza en 5 y resta 3.",
          explicacion: "5 - 3 = 2. El robot queda en la casilla 2.",
        },
        {
          id: "3-3-5-e3",
          enunciado: "Para ir de A (columna 1, fila 1) a B (columna 4, fila 3), ¿cuántos pasos hacia la derecha y cuántos hacia arriba necesitas?",
          tipo: "texto",
          respuesta: "3 derecha, 2 arriba",
          pista: "Resta las coordenadas: columna B - columna A y fila B - fila A.",
          explicacion: "Columnas: 4-1=3 (3 pasos a la derecha). Filas: 3-1=2 (2 pasos hacia arriba).",
        },
        {
          id: "3-3-5-e4",
          enunciado: "¿El movimiento 'hacia adelante' es horizontal o vertical?",
          tipo: "seleccion",
          opciones: ["Horizontal", "Vertical", "Depende de hacia dónde miras"],
          respuesta: "Depende de hacia dónde miras",
          pista: "Si miras hacia el norte, adelante es diferente que si miras hacia el este.",
          explicacion: "'Adelante' depende de tu orientación. Por eso en geometría preferimos usar norte/sur/este/oeste o derecha/izquierda con una referencia fija.",
        },
      ],
    },
    {
      id: "3-3-6",
      titulo: "Círculo y circunferencia",
      objetivo: "Distinguir el círculo de la circunferencia e identificar sus elementos.",
      concepto_clave: "Circunferencia: línea curva cerrada. Círculo: la superficie interior + la circunferencia.",
      explicacion: [
        "La CIRCUNFERENCIA es solo la línea curva cerrada (como el aro de un balón). El CÍRCULO incluye también todo el interior (como la cara del reloj completa).",
        "El CENTRO es el punto equidistante de todos los puntos de la circunferencia. El RADIO es la distancia del centro a cualquier punto de la circunferencia. El DIÁMETRO pasa por el centro y mide el doble del radio.",
        "Fórmula clave: Diámetro = 2 × Radio",
      ],
      ejemplos: [
        {
          enunciado: "Un círculo tiene radio de 5 cm. ¿Cuánto mide su diámetro?",
          pasos: [
            { texto: "Diámetro = 2 × Radio" },
            { texto: "Diámetro = 2 × 5 cm" },
          ],
          resultado: "El diámetro mide 10 cm",
        },
        {
          enunciado: "El diámetro de una rueda es 60 cm. ¿Cuánto mide el radio?",
          pasos: [
            { texto: "Radio = Diámetro ÷ 2" },
            { texto: "Radio = 60 ÷ 2" },
          ],
          resultado: "El radio mide 30 cm",
        },
      ],
      ejercicios: [
        {
          id: "3-3-6-e1",
          enunciado: "¿Cuál es la diferencia entre círculo y circunferencia?",
          tipo: "seleccion",
          opciones: [
            "Son exactamente lo mismo",
            "La circunferencia es solo la línea curva; el círculo incluye el interior",
            "El círculo es la línea curva; la circunferencia incluye el interior",
          ],
          respuesta: "La circunferencia es solo la línea curva; el círculo incluye el interior",
          pista: "Piensa en un aro vs un disco.",
          explicacion: "La circunferencia es la línea curva (como un aro). El círculo es esa línea más el área interior (como una moneda).",
        },
        {
          id: "3-3-6-e2",
          enunciado: "Un círculo tiene radio de 8 cm. ¿Cuánto mide el diámetro?",
          tipo: "numero",
          respuesta: "16",
          pista: "Diámetro = 2 × Radio.",
          explicacion: "Diámetro = 2 × 8 = 16 cm.",
        },
        {
          id: "3-3-6-e3",
          enunciado: "El diámetro de un CD es 12 cm. ¿Cuánto mide el radio?",
          tipo: "numero",
          respuesta: "6",
          pista: "Radio = Diámetro ÷ 2.",
          explicacion: "Radio = 12 ÷ 2 = 6 cm.",
        },
        {
          id: "3-3-6-e4",
          enunciado: "¿Todos los radios de un mismo círculo miden igual?",
          tipo: "seleccion",
          opciones: ["Sí, siempre", "No, pueden variar"],
          respuesta: "Sí, siempre",
          pista: "El centro está a la misma distancia de TODOS los puntos de la circunferencia.",
          explicacion: "Sí. Por definición, todos los radios de un círculo miden igual porque el centro está equidistante de todos los puntos.",
        },
      ],
    },
    {
      id: "3-3-7",
      titulo: "Ejes de simetría",
      objetivo: "Identificar ejes de simetría en figuras y en objetos del entorno.",
      concepto_clave: "Un eje de simetría divide una figura en dos partes iguales que son imagen espejo una de la otra.",
      explicacion: [
        "Una figura tiene SIMETRÍA cuando se puede doblar por una línea (eje de simetría) y las dos mitades coinciden perfectamente.",
        "El eje de simetría puede ser vertical, horizontal o diagonal. Algunas figuras tienen más de un eje de simetría.",
        "Ejemplos: la mariposa tiene 1 eje vertical. El rectángulo tiene 2 ejes. El círculo tiene infinitos ejes.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuántos ejes de simetría tiene un cuadrado?",
          pasos: [
            { texto: "Eje vertical: divide en dos rectángulos iguales ✓" },
            { texto: "Eje horizontal: divide en dos rectángulos iguales ✓" },
            { texto: "Diagonal ↗: divide en dos triángulos iguales ✓" },
            { texto: "Diagonal ↘: divide en dos triángulos iguales ✓" },
          ],
          resultado: "El cuadrado tiene 4 ejes de simetría",
        },
        {
          enunciado: "¿Tiene la letra A un eje de simetría?",
          pasos: [
            { texto: "Trazo una línea vertical por el centro de la A" },
            { texto: "Las dos mitades son imagen espejo ✓" },
          ],
          resultado: "Sí, la letra A tiene 1 eje de simetría vertical",
        },
      ],
      ejercicios: [
        {
          id: "3-3-7-e1",
          enunciado: "¿Cuántos ejes de simetría tiene un rectángulo (que no sea cuadrado)?",
          tipo: "numero",
          respuesta: "2",
          pista: "Prueba con el eje vertical, horizontal y las diagonales. ¿Cuáles funcionan?",
          explicacion: "El rectángulo tiene 2 ejes: vertical y horizontal. Las diagonales NO son ejes de simetría (las mitades no coinciden).",
        },
        {
          id: "3-3-7-e2",
          enunciado: "¿Cuáles de estas letras tienen eje de simetría vertical: A, B, C, D, M, W?",
          tipo: "texto",
          respuesta: "A,M,W",
          pista: "Imagina doblar la letra por el centro vertical. ¿Las dos mitades quedan iguales?",
          explicacion: "A, M y W tienen eje de simetría vertical. B, C y D tienen eje horizontal.",
        },
        {
          id: "3-3-7-e3",
          enunciado: "¿Tiene la letra Z algún eje de simetría?",
          tipo: "seleccion",
          opciones: ["Sí, uno vertical", "Sí, uno horizontal", "No tiene ninguno"],
          respuesta: "No tiene ninguno",
          pista: "Intenta doblar la Z por cualquier línea. ¿Las mitades coinciden?",
          explicacion: "La Z no tiene ejes de simetría. Ninguna línea la divide en dos mitades exactamente iguales.",
        },
        {
          id: "3-3-7-e4",
          enunciado: "Un colibrí con las alas extendidas simétricamente tiene ___ eje(s) de simetría",
          tipo: "numero",
          respuesta: "1",
          pista: "Traza una línea por el centro del cuerpo del colibrí.",
          explicacion: "El colibrí con alas simétricas tiene 1 eje de simetría: la línea vertical que pasa por su cuerpo.",
        },
      ],
    },
    {
      id: "3-3-8",
      titulo: "Traslación de figuras",
      objetivo: "Comprender y aplicar la traslación como movimiento de una figura en el plano.",
      concepto_clave: "La traslación desliza una figura sin rotarla ni cambiar su tamaño. La figura y su imagen son congruentes.",
      explicacion: [
        "La TRASLACIÓN es como deslizar un objeto: lo movemos de un lugar a otro sin girarlo ni cambiar su tamaño o forma. La figura original y la imagen trasladada son exactamente iguales.",
        "Para describir una traslación necesitamos: dirección (hacia dónde) y distancia (cuánto).",
        "Ejemplo: si traslado un triángulo 3 cuadros a la derecha y 2 cuadros arriba, todos sus puntos se mueven esa misma cantidad.",
      ],
      ejemplos: [
        {
          enunciado: "Traslada el punto A(1,2) cuatro unidades a la derecha y tres abajo",
          pasos: [
            { texto: "Posición inicial: A(1, 2)" },
            { texto: "Movimiento horizontal: 1 + 4 = 5" },
            { texto: "Movimiento vertical: 2 - 3 = -1 (o sea, 1 abajo del eje)" },
          ],
          resultado: "El punto A' (imagen) queda en (5, -1)",
        },
        {
          enunciado: "¿Cambia el tamaño de una figura al trasladarla?",
          pasos: [
            { texto: "Una traslación solo mueve la figura" },
            { texto: "No la gira ni la estira" },
          ],
          resultado: "NO. La figura y su imagen son exactamente iguales (congruentes)",
        },
      ],
      ejercicios: [
        {
          id: "3-3-8-e1",
          enunciado: "Un cuadrado se traslada 5 unidades a la izquierda. ¿Cambia su tamaño?",
          tipo: "seleccion",
          opciones: ["Sí, se hace más pequeño", "No, sigue siendo igual", "Sí, se hace más grande"],
          respuesta: "No, sigue siendo igual",
          pista: "La traslación solo cambia la posición, no el tamaño.",
          explicacion: "La traslación no cambia el tamaño ni la forma. Solo cambia la posición.",
        },
        {
          id: "3-3-8-e2",
          enunciado: "El punto B(3,4) se traslada 2 unidades arriba. ¿Dónde queda?",
          tipo: "texto",
          respuesta: "(3,6)",
          pista: "Solo cambia la coordenada vertical: 4 + 2 = 6.",
          explicacion: "B(3,4) trasladado 2 arriba: (3, 4+2) = (3, 6).",
        },
        {
          id: "3-3-8-e3",
          enunciado: "¿Qué elemento NO cambia en una traslación?",
          tipo: "seleccion",
          opciones: ["La posición", "La forma y el tamaño", "El ángulo de rotación"],
          respuesta: "La forma y el tamaño",
          pista: "En una traslación, la figura se mueve pero no cambia.",
          explicacion: "En una traslación, la forma y el tamaño siempre se conservan. Solo cambia la posición.",
        },
        {
          id: "3-3-8-e4",
          enunciado: "Si traslado un triángulo con vértices en (1,1), (3,1) y (2,3) dos unidades a la derecha, ¿dónde quedan los nuevos vértices?",
          tipo: "texto",
          respuesta: "(3,1),(5,1),(4,3)",
          pista: "Suma 2 a cada coordenada horizontal (primera coordenada).",
          explicacion: "(1+2,1)=(3,1), (3+2,1)=(5,1), (2+2,3)=(4,3).",
        },
      ],
    },
    {
      id: "3-3-9",
      titulo: "Rotación de figuras",
      objetivo: "Comprender la rotación como giro de una figura alrededor de un punto.",
      concepto_clave: "La rotación gira una figura alrededor de un punto fijo (centro de rotación) un determinado ángulo.",
      explicacion: [
        "La ROTACIÓN es como girar una llave: la figura da vueltas alrededor de un punto fijo llamado centro de rotación.",
        "Para describir una rotación necesitamos: el centro de rotación, el ángulo (cuánto gira) y el sentido (horario o antihorario).",
        "Las rotaciones más comunes son de 90°, 180° y 270°. Al girar 360° la figura regresa a su posición original.",
      ],
      ejemplos: [
        {
          enunciado: "Una figura gira 90° en sentido horario. ¿Cuánto falta para completar una vuelta?",
          pasos: [
            { texto: "Una vuelta completa = 360°" },
            { texto: "Ya giró: 90°" },
            { texto: "Falta: 360° - 90° = 270°" },
          ],
          resultado: "Faltan 270° para completar la vuelta",
        },
        {
          enunciado: "¿Cuántas rotaciones de 90° completan una vuelta?",
          pasos: [
            { texto: "360° ÷ 90° = 4" },
          ],
          resultado: "Se necesitan 4 rotaciones de 90° para completar una vuelta de 360°",
        },
      ],
      ejercicios: [
        {
          id: "3-3-9-e1",
          enunciado: "Una flecha apunta hacia arriba. Si la rotas 180°, ¿hacia dónde apunta?",
          tipo: "seleccion",
          opciones: ["Arriba", "Abajo", "A la derecha", "A la izquierda"],
          respuesta: "Abajo",
          pista: "180° es media vuelta completa.",
          explicacion: "Al girar 180°, la flecha queda apuntando en dirección opuesta: hacia abajo.",
        },
        {
          id: "3-3-9-e2",
          enunciado: "¿Cuántos grados hay en una vuelta completa?",
          tipo: "numero",
          respuesta: "360",
          pista: "Piensa en el reloj dando una vuelta completa.",
          explicacion: "Una vuelta completa equivale a 360°.",
        },
        {
          id: "3-3-9-e3",
          enunciado: "El minutero del reloj gira desde las 12 hasta las 3. ¿Cuántos grados giró?",
          tipo: "numero",
          respuesta: "90",
          pista: "De 12 a 3 es 1/4 de vuelta. ¿Cuánto es 1/4 de 360°?",
          explicacion: "De las 12 a las 3 es 1/4 de vuelta. 360° ÷ 4 = 90°.",
        },
        {
          id: "3-3-9-e4",
          enunciado: "¿Qué diferencia hay entre rotación y traslación?",
          tipo: "texto",
          respuesta: "La rotación gira la figura alrededor de un punto; la traslación la desliza sin girar",
          pista: "Piensa en deslizar vs girar.",
          explicacion: "La traslación desliza la figura sin girarla. La rotación la gira alrededor de un punto fijo.",
        },
      ],
    },
    {
      id: "3-3-10",
      titulo: "Ampliación y reducción de figuras",
      objetivo: "Ampliar y reducir figuras manteniendo la proporción.",
      concepto_clave: "Para ampliar o reducir una figura, multiplica o divide todos sus lados por el mismo número (factor de escala).",
      explicacion: [
        "Ampliar una figura es hacerla más grande. Reducirla es hacerla más pequeña. En ambos casos, la FORMA debe conservarse: los ángulos no cambian y los lados guardan la misma proporción.",
        "El FACTOR DE ESCALA nos dice cuánto se amplía o reduce. Si el factor es 2, todos los lados se duplican. Si el factor es 1/2, todos los lados se reducen a la mitad.",
        "Cuando una figura se amplía o reduce manteniendo la proporción, se llaman FIGURAS SEMEJANTES.",
      ],
      ejemplos: [
        {
          enunciado: "Un rectángulo mide 3 cm × 5 cm. Lo amplías con factor 3. ¿Cuánto mide la figura ampliada?",
          pasos: [
            { texto: "Lado 1: 3 × 3 = 9 cm" },
            { texto: "Lado 2: 5 × 3 = 15 cm" },
          ],
          resultado: "El rectángulo ampliado mide 9 cm × 15 cm",
        },
        {
          enunciado: "Un cuadrado mide 12 cm. Lo reduces con factor 1/4. ¿Cuánto mide el nuevo cuadrado?",
          pasos: [
            { texto: "12 × (1/4) = 12 ÷ 4 = 3 cm" },
          ],
          resultado: "El cuadrado reducido mide 3 cm de lado",
        },
      ],
      ejercicios: [
        {
          id: "3-3-10-e1",
          enunciado: "Un triángulo tiene lados de 4, 6 y 8 cm. Se amplía con factor 2. ¿Cuánto miden los nuevos lados?",
          tipo: "texto",
          respuesta: "8,12,16",
          pista: "Multiplica cada lado por 2.",
          explicacion: "4×2=8, 6×2=12, 8×2=16. El triángulo ampliado mide 8, 12 y 16 cm.",
        },
        {
          id: "3-3-10-e2",
          enunciado: "¿Cambian los ángulos cuando ampliamos una figura?",
          tipo: "seleccion",
          opciones: ["Sí, se hacen más grandes", "No, los ángulos se conservan", "Sí, se hacen más pequeños"],
          respuesta: "No, los ángulos se conservan",
          pista: "Las figuras semejantes tienen los mismos ángulos aunque diferente tamaño.",
          explicacion: "Al ampliar o reducir una figura, los ángulos siempre se conservan. Solo cambia el tamaño de los lados.",
        },
        {
          id: "3-3-10-e3",
          enunciado: "Un mapa usa escala 1:100. Si en el mapa una calle mide 5 cm, ¿cuánto mide en la realidad?",
          tipo: "numero",
          respuesta: "500",
          pista: "Multiplica la medida del mapa por el factor de escala (100).",
          explicacion: "5 cm × 100 = 500 cm = 5 metros en la realidad.",
        },
        {
          id: "3-3-10-e4",
          enunciado: "¿Qué factor de escala se usó si un lado de 8 cm se convirtió en 2 cm?",
          tipo: "seleccion",
          opciones: ["Factor 4 (ampliación)", "Factor 1/4 (reducción)", "Factor 2 (ampliación)"],
          respuesta: "Factor 1/4 (reducción)",
          pista: "8 ÷ ? = 2. ¿Por qué número divido 8 para obtener 2?",
          explicacion: "8 ÷ 4 = 2. Se aplicó un factor de 1/4: la figura se redujo a la cuarta parte.",
        },
      ],
    },
  ],
}

export default unidad3
