import type { Unidad } from "../tipos"

const unidad3: Unidad = {
  id: 3,
  nombre: "Relaciones Multiplicativas y Fracciones",
  descripcion: "Descubre los secretos de los números primos, múltiplos, divisores y las fracciones.",
  color: "purple",
  icono: "🔗",
  lecciones: [
    {
      id: "4-3-1",
      titulo: "Números primos y compuestos",
      objetivo: "Identificar si un número es primo o compuesto y conocer sus características.",
      concepto_clave: "Número primo: solo divisible entre 1 y sí mismo. Número compuesto: tiene más de 2 divisores.",
      explicacion: [
        "Un NÚMERO PRIMO es aquel que solo puede dividirse exactamente entre 1 y entre sí mismo. Por ejemplo, 7 solo es divisible entre 1 y entre 7. No hay otra opción.",
        "Un NÚMERO COMPUESTO es el que tiene más divisores. Por ejemplo, 12 es divisible entre 1, 2, 3, 4, 6 y 12. Los números compuestos pueden 'desarmarse' en factores primos.",
        "El número 1 NO es primo ni compuesto: es un caso especial. Los primeros números primos son: 2, 3, 5, 7, 11, 13, 17, 19, 23... ¡El 2 es el único primo par!",
      ],
      ejemplos: [
        {
          enunciado: "¿Es primo el número 17?",
          pasos: [
            { texto: "Pruebo divisores: ¿17 ÷ 2? No exacto (8,5)" },
            { texto: "¿17 ÷ 3? No exacto (5,6...)" },
            { texto: "¿17 ÷ 4? No (4,25)" },
            { texto: "¿17 ÷ 5? No (3,4)" },
            { texto: "Solo me queda probar hasta √17 ≈ 4. Ya probé todos." },
          ],
          resultado: "17 es PRIMO (solo divisible entre 1 y 17)",
        },
        {
          enunciado: "Descompón 24 en factores primos",
          pasos: [
            { texto: "24 ÷ 2 = 12" },
            { texto: "12 ÷ 2 = 6" },
            { texto: "6 ÷ 2 = 3" },
            { texto: "3 es primo → terminamos" },
          ],
          resultado: "24 = 2 × 2 × 2 × 3 = 2³ × 3",
        },
      ],
      ejercicios: [
        {
          id: "4-3-1-e1",
          enunciado: "¿Cuál de estos es primo: 9, 11, 15, 21?",
          tipo: "seleccion",
          opciones: ["9", "11", "15", "21"],
          respuesta: "11",
          pista: "Un primo solo es divisible entre 1 y sí mismo. ¿Cuál de estos no tiene otros divisores?",
          explicacion: "9=3×3, 15=3×5, 21=3×7 (todos compuestos). 11 solo es divisible entre 1 y 11: es primo.",
        },
        {
          id: "4-3-1-e2",
          enunciado: "¿Por qué el 2 es el único número primo par?",
          tipo: "texto",
          respuesta: "Porque todos los pares mayores que 2 son divisibles entre 2, por lo que tienen al menos 3 divisores",
          pista: "¿Puedes dividir 4, 6, 8... entre 2 además de entre 1 y sí mismos?",
          explicacion: "Todo número par es divisible entre 2. Si es mayor que 2, tiene al menos los divisores 1, 2, y él mismo (3 divisores) → es compuesto. El 2 solo tiene 1 y 2.",
        },
        {
          id: "4-3-1-e3",
          enunciado: "¿Cuántos números primos hay entre 1 y 20?",
          tipo: "numero",
          respuesta: "8",
          pista: "Lista: 2, 3, 5, 7, ___, ___, ___, ___. Verifica cada número.",
          explicacion: "Los primos entre 1 y 20 son: 2, 3, 5, 7, 11, 13, 17, 19. Son 8 en total.",
        },
        {
          id: "4-3-1-e4",
          enunciado: "Descompón 18 en factores primos",
          tipo: "texto",
          respuesta: "2×3×3",
          pista: "Empieza dividiendo entre 2: 18÷2=9. Luego 9 ÷ 3 = ?",
          explicacion: "18 = 2 × 9 = 2 × 3 × 3. Los factores primos de 18 son 2, 3, 3.",
        },
      ],
    },
    {
      id: "4-3-2",
      titulo: "Múltiplos y Mínimo Común Múltiplo (MCM)",
      objetivo: "Encontrar múltiplos de un número y calcular el Mínimo Común Múltiplo de dos números.",
      concepto_clave: "Múltiplos de n: n×1, n×2, n×3... MCM(a,b): el múltiplo más pequeño que tienen en común a y b.",
      explicacion: [
        "Los MÚLTIPLOS de un número son todos los resultados de multiplicarlo por 1, 2, 3, 4... Por ejemplo, los múltiplos de 4 son: 4, 8, 12, 16, 20, 24...",
        "El MÍNIMO COMÚN MÚLTIPLO (MCM) de dos números es el número más pequeño que es múltiplo de ambos al mismo tiempo.",
        "¿Para qué sirve el MCM? Para resolver problemas como: 'Una señal roja destella cada 4 segundos y una azul cada 6. ¿Cuándo destellan juntas por primera vez?' → MCM(4,6) = 12 segundos.",
      ],
      ejemplos: [
        {
          enunciado: "Halla el MCM de 4 y 6",
          pasos: [
            { texto: "Múltiplos de 4: 4, 8, 12, 16, 20, 24..." },
            { texto: "Múltiplos de 6: 6, 12, 18, 24, 30..." },
            { texto: "Múltiplos comunes: 12, 24, 36..." },
            { texto: "El más pequeño: 12" },
          ],
          resultado: "MCM(4, 6) = 12",
        },
        {
          enunciado: "Halla el MCM de 3 y 5",
          pasos: [
            { texto: "Múltiplos de 3: 3, 6, 9, 12, 15, 18..." },
            { texto: "Múltiplos de 5: 5, 10, 15, 20..." },
            { texto: "Primer múltiplo común: 15" },
          ],
          resultado: "MCM(3, 5) = 15",
        },
      ],
      ejercicios: [
        {
          id: "4-3-2-e1",
          enunciado: "¿Cuáles son los primeros 5 múltiplos de 7?",
          tipo: "texto",
          respuesta: "7,14,21,28,35",
          pista: "7×1, 7×2, 7×3, 7×4, 7×5",
          explicacion: "7×1=7, 7×2=14, 7×3=21, 7×4=28, 7×5=35.",
        },
        {
          id: "4-3-2-e2",
          enunciado: "Halla el MCM(4, 10)",
          tipo: "numero",
          respuesta: "20",
          pista: "Múltiplos de 4: 4,8,12,16,20... Múltiplos de 10: 10,20...",
          explicacion: "Múltiplos de 4: 4,8,12,16,20. Múltiplos de 10: 10,20. El primero en común es 20.",
        },
        {
          id: "4-3-2-e3",
          enunciado: "Una máquina A suena cada 3 minutos y una máquina B cada 5 minutos. ¿Cuándo suenan juntas por primera vez?",
          tipo: "numero",
          respuesta: "15",
          pista: "Necesitas el MCM(3, 5).",
          explicacion: "MCM(3,5) = 15 minutos. A los 15 minutos, la máquina A habrá sonado 5 veces y B habrá sonado 3 veces, y coinciden.",
        },
        {
          id: "4-3-2-e4",
          enunciado: "¿El MCM de dos números siempre es mayor que los dos números?",
          tipo: "seleccion",
          opciones: [
            "Sí, siempre",
            "No, si uno es múltiplo del otro, el MCM es el mayor de los dos",
            "No, el MCM siempre es su producto",
          ],
          respuesta: "No, si uno es múltiplo del otro, el MCM es el mayor de los dos",
          pista: "Piensa en MCM(3, 6). ¿Es mayor que 6?",
          explicacion: "MCM(3,6) = 6. Como 6 es múltiplo de 3, el MCM es simplemente 6. No siempre es mayor que ambos.",
        },
      ],
    },
    {
      id: "4-3-3",
      titulo: "Divisores y Máximo Común Divisor (MCD)",
      objetivo: "Encontrar todos los divisores de un número y calcular el Máximo Común Divisor de dos números.",
      concepto_clave: "Divisores de n: números que dividen a n exactamente. MCD(a,b): el mayor divisor que comparten a y b.",
      explicacion: [
        "Un DIVISOR de un número es aquel que lo divide exactamente (sin residuo). Por ejemplo, los divisores de 12 son: 1, 2, 3, 4, 6, 12.",
        "El MÁXIMO COMÚN DIVISOR (MCD) de dos números es el divisor más grande que tienen en común. Por ejemplo, MCD(12, 8) = 4.",
        "¿Para qué sirve el MCD? Para simplificar fracciones y para resolver problemas de reparto: '¿Cuántos grupos iguales más grandes puedo hacer con 12 manzanas y 8 peras?' → MCD(12, 8) = 4 grupos.",
      ],
      ejemplos: [
        {
          enunciado: "Halla todos los divisores de 18",
          pasos: [
            { texto: "Pruebo: 1 → 18÷1=18 ✓" },
            { texto: "2 → 18÷2=9 ✓" },
            { texto: "3 → 18÷3=6 ✓" },
            { texto: "6 → 18÷6=3 ✓" },
            { texto: "9 → 18÷9=2 ✓" },
            { texto: "18 → 18÷18=1 ✓" },
          ],
          resultado: "Divisores de 18: {1, 2, 3, 6, 9, 18}",
        },
        {
          enunciado: "Halla el MCD(12, 18)",
          pasos: [
            { texto: "Divisores de 12: 1, 2, 3, 4, 6, 12" },
            { texto: "Divisores de 18: 1, 2, 3, 6, 9, 18" },
            { texto: "Divisores comunes: 1, 2, 3, 6" },
            { texto: "El mayor: 6" },
          ],
          resultado: "MCD(12, 18) = 6",
        },
      ],
      ejercicios: [
        {
          id: "4-3-3-e1",
          enunciado: "¿Cuáles son los divisores de 20?",
          tipo: "texto",
          respuesta: "1,2,4,5,10,20",
          pista: "Prueba dividir 20 entre 1, 2, 3, 4, 5... ¿Cuáles dan resultado exacto?",
          explicacion: "Divisores de 20: 20÷1=20✓, 20÷2=10✓, 20÷4=5✓, 20÷5=4✓, 20÷10=2✓, 20÷20=1✓. Son: 1,2,4,5,10,20.",
        },
        {
          id: "4-3-3-e2",
          enunciado: "Halla el MCD(8, 12)",
          tipo: "numero",
          respuesta: "4",
          pista: "Divisores de 8: 1,2,4,8. Divisores de 12: 1,2,3,4,6,12. ¿Cuál es el mayor en común?",
          explicacion: "Divisores comunes de 8 y 12: 1, 2, 4. El mayor es 4. MCD(8,12) = 4.",
        },
        {
          id: "4-3-3-e3",
          enunciado: "Tengo 24 manzanas y 36 peras. Quiero hacer la mayor cantidad de canastas con la misma cantidad de manzanas y peras en cada una. ¿Cuántas canastas hago?",
          tipo: "numero",
          respuesta: "12",
          pista: "Necesitas el MCD(24, 36).",
          explicacion: "MCD(24,36) = 12. Puedes hacer 12 canastas con 2 manzanas y 3 peras cada una.",
        },
        {
          id: "4-3-3-e4",
          enunciado: "¿Cuál es la diferencia entre MCM y MCD?",
          tipo: "texto",
          respuesta: "El MCM es el mínimo múltiplo común (se usa para sumar fracciones). El MCD es el máximo divisor común (se usa para simplificar fracciones).",
          pista: "M de MCM = Múltiplo. M de MCD = Divisor.",
          explicacion: "MCM: múltiplo más pequeño compartido (subimos). MCD: divisor más grande compartido (bajamos). Sirven para propósitos opuestos.",
        },
      ],
    },
    {
      id: "4-3-4",
      titulo: "Fracciones: lectura, escritura y tipos",
      objetivo: "Leer, escribir y clasificar fracciones propias, impropias y números mixtos.",
      concepto_clave: "Propia: numerador < denominador (menos de 1 entero). Impropia: numerador ≥ denominador (1 o más enteros). Número mixto: entero + fracción.",
      explicacion: [
        "En cuarto grado profundizamos en las fracciones. Recordamos: el NUMERADOR (arriba) dice cuántas partes tenemos y el DENOMINADOR (abajo) dice en cuántas partes iguales está dividido el entero.",
        "FRACCIÓN PROPIA: el numerador es menor que el denominador. Vale menos que 1. Ejemplo: 3/5.",
        "FRACCIÓN IMPROPIA: el numerador es mayor o igual al denominador. Vale 1 o más. Ejemplo: 7/4.",
        "NÚMERO MIXTO: es la forma de escribir una fracción impropia como entero + fracción propia. Ejemplo: 7/4 = 1 y 3/4 (un entero y tres cuartos).",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 11/3 a número mixto",
          pasos: [
            { texto: "Divido 11 ÷ 3 = 3 con residuo 2" },
            { texto: "Entero = cociente = 3" },
            { texto: "Fracción = residuo/denominador = 2/3" },
          ],
          resultado: "11/3 = 3 y 2/3 (tres enteros y dos tercios)",
        },
        {
          enunciado: "Convierte 2 y 3/5 a fracción impropia",
          pasos: [
            { texto: "Numerador = (entero × denominador) + numerador de la fracción" },
            { texto: "= (2 × 5) + 3 = 10 + 3 = 13" },
            { texto: "Denominador permanece igual: 5" },
          ],
          resultado: "2 y 3/5 = 13/5",
        },
      ],
      ejercicios: [
        {
          id: "4-3-4-e1",
          enunciado: "Clasifica estas fracciones: 3/8, 9/4, 5/5, 7/10",
          tipo: "texto",
          respuesta: "3/8 propia, 9/4 impropia, 5/5 impropia, 7/10 propia",
          pista: "Compara numerador y denominador. Si num < den → propia. Si num ≥ den → impropia.",
          explicacion: "3/8 → 3<8 propia. 9/4 → 9>4 impropia. 5/5 → 5=5 impropia (=1). 7/10 → 7<10 propia.",
        },
        {
          id: "4-3-4-e2",
          enunciado: "Convierte 9/4 a número mixto",
          tipo: "texto",
          respuesta: "2 y 1/4",
          pista: "Divide 9 ÷ 4. El cociente es el entero y el residuo sobre 4 es la fracción.",
          explicacion: "9 ÷ 4 = 2 con residuo 1. Entonces 9/4 = 2 y 1/4.",
        },
        {
          id: "4-3-4-e3",
          enunciado: "Convierte 3 y 2/7 a fracción impropia",
          tipo: "texto",
          respuesta: "23/7",
          pista: "Numerador = 3×7 + 2. Denominador permanece 7.",
          explicacion: "(3×7)+2 = 21+2 = 23. La fracción impropia es 23/7.",
        },
        {
          id: "4-3-4-e4",
          enunciado: "¿Cuánto vale la fracción 8/8?",
          tipo: "numero",
          respuesta: "1",
          pista: "Cuando numerador = denominador, la fracción vale exactamente...",
          explicacion: "8/8 = 1 entero completo. Cuando el numerador y denominador son iguales, la fracción vale 1.",
        },
      ],
    },
    {
      id: "4-3-5",
      titulo: "Fracción de un conjunto y lectura de fracciones",
      objetivo: "Calcular la fracción de un conjunto y leer fracciones usando los sufijos '-avos'.",
      concepto_clave: "Para leer fracciones: 1/4 = un cuarto, 1/5 = un quinto, 1/8 = un octavo, 1/10 = un décimo, 1/n = un n-avo.",
      explicacion: [
        "Para LEER fracciones usamos nombres especiales: mitad (1/2), tercio (1/3), cuarto (1/4), quinto (1/5), sexto (1/6), séptimo (1/7), octavo (1/8), noveno (1/9), décimo (1/10). Para el resto usamos '-avo': 1/11 = un onceavo, 1/15 = un quinceavo, 1/20 = un veinteavo.",
        "Para hallar la fracción de un conjunto seguimos dos pasos: 1) Dividimos el total entre el denominador (para saber cuánto es 1 parte). 2) Multiplicamos por el numerador (para saber cuántas partes queremos).",
        "Ejemplo: 3/4 de 24 → 24 ÷ 4 = 6 (una parte), 6 × 3 = 18 (tres partes). Entonces 3/4 de 24 = 18.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cómo se lee la fracción 5/8?",
          pasos: [
            { texto: "Numerador 5: cinco" },
            { texto: "Denominador 8: octavos" },
          ],
          resultado: "5/8 se lee 'cinco octavos'",
        },
        {
          enunciado: "Halla 2/3 de 45 estudiantes",
          pasos: [
            { texto: "45 ÷ 3 = 15 (una tercera parte)" },
            { texto: "15 × 2 = 30 (dos tercios)" },
          ],
          resultado: "2/3 de 45 estudiantes = 30 estudiantes",
        },
        {
          enunciado: "En una clase de 40 estudiantes, 3/8 tienen mascotas. ¿Cuántos son?",
          pasos: [
            { texto: "40 ÷ 8 = 5 (un octavo)" },
            { texto: "5 × 3 = 15 (tres octavos)" },
          ],
          resultado: "15 estudiantes tienen mascotas",
        },
      ],
      ejercicios: [
        {
          id: "4-3-5-e1",
          enunciado: "¿Cómo se lee 7/12?",
          tipo: "texto",
          respuesta: "siete doceaos",
          pista: "El denominador 12 se dice doceavo. El numerador 7 se dice siete.",
          explicacion: "7/12 = siete doceaos. Para denominadores del 11 en adelante: n-avo (doceavo, quinceavo, etc.).",
        },
        {
          id: "4-3-5-e2",
          enunciado: "Halla 3/5 de 35",
          tipo: "numero",
          respuesta: "21",
          pista: "35 ÷ 5 = 7 (un quinto). Luego 7 × 3 = ?",
          explicacion: "35 ÷ 5 = 7. 7 × 3 = 21. Tres quintos de 35 son 21.",
        },
        {
          id: "4-3-5-e3",
          enunciado: "En una caja hay 48 chocolates. Se comieron 5/8. ¿Cuántos chocolates quedan?",
          tipo: "numero",
          respuesta: "18",
          pista: "Primero halla cuántos se comieron: 5/8 de 48. Luego resta del total.",
          explicacion: "48÷8=6, 6×5=30 se comieron. 48−30=18 chocolates quedan.",
        },
        {
          id: "4-3-5-e4",
          enunciado: "Si 1/4 de un conjunto es 9, ¿cuántos elementos tiene el conjunto completo?",
          tipo: "numero",
          respuesta: "36",
          pista: "Si 1/4 = 9, entonces el total = 9 × 4.",
          explicacion: "Si una cuarta parte es 9, el total es 4 veces eso: 9 × 4 = 36.",
        },
      ],
    },
  ],
}

export default unidad3
