import type { Unidad } from "../tipos"

const unidad4: Unidad = {
  id: 4,
  nombre: "Medición",
  descripcion: "Convierte unidades de longitud, área, volumen, masa, tiempo y temperatura con confianza.",
  color: "orange",
  icono: "📏",
  lecciones: [
    {
      id: "5-4-1",
      titulo: "Unidades de longitud y conversiones",
      objetivo: "Convertir entre unidades del sistema métrico (km, hm, dam, m, dm, cm, mm).",
      concepto_clave: "Cada unidad es 10 veces la siguiente. Para bajar (m→cm): multiplica por 10. Para subir (cm→m): divide entre 10.",
      explicacion: [
        "El sistema métrico de longitud tiene estas unidades de mayor a menor: kilómetro (km), hectómetro (hm), decámetro (dam), METRO (m), decímetro (dm), centímetro (cm), milímetro (mm). Cada una es 10 veces la siguiente.",
        "Para convertir a una unidad MENOR (bajar en la tabla): multiplicas por 10 por cada escalón que bajas. 3 m = 300 cm (bajé 2 escalones, multipliqué por 100).",
        "Para convertir a una unidad MAYOR (subir en la tabla): divides por 10 por cada escalón que subes. 450 mm = 45 cm = 0,45 m (subí escalones dividiendo por 10 cada vez).",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 2,5 km a metros",
          pasos: [
            { texto: "km a m: bajo 3 escalones → multiplico por 1000" },
            { texto: "2,5 × 1000 = 2500" },
          ],
          resultado: "2,5 km = 2.500 m",
        },
        {
          enunciado: "Convierte 850 cm a metros",
          pasos: [
            { texto: "cm a m: subo 2 escalones → divido entre 100" },
            { texto: "850 ÷ 100 = 8,5" },
          ],
          resultado: "850 cm = 8,5 m",
        },
      ],
      ejercicios: [
        {
          id: "5-4-1-e1",
          enunciado: "Convierte 3,2 km a metros",
          tipo: "numero",
          respuesta: "3200",
          pista: "km → m: 3 escalones hacia abajo → multiplica por 1000.",
          explicacion: "3,2 × 1000 = 3.200 m.",
        },
        {
          id: "5-4-1-e2",
          enunciado: "Convierte 560 mm a centímetros",
          tipo: "numero",
          respuesta: "56",
          pista: "mm → cm: 1 escalón hacia arriba → divide entre 10.",
          explicacion: "560 ÷ 10 = 56 cm.",
        },
        {
          id: "5-4-1-e3",
          enunciado: "Un estadio mide 400 m. ¿Cuántos km son?",
          tipo: "texto",
          respuesta: "0,4",
          pista: "m → km: sube 3 escalones → divide entre 1000.",
          explicacion: "400 ÷ 1000 = 0,4 km.",
        },
        {
          id: "5-4-1-e4",
          enunciado: "¿Cuántos centímetros tiene 1 km?",
          tipo: "numero",
          respuesta: "100000",
          pista: "1 km = 1000 m = 100.000 cm.",
          explicacion: "1 km = 1000 m. 1 m = 100 cm. 1 km = 1000 × 100 = 100.000 cm.",
        },
      ],
    },
    {
      id: "5-4-2",
      titulo: "Unidades de superficie y conversiones",
      objetivo: "Calcular áreas y convertir entre unidades de superficie (km², m², cm², mm²).",
      concepto_clave: "Al pasar de una unidad de longitud a una de área, el factor se ELEVA AL CUADRADO. 1 m = 100 cm → 1 m² = 10.000 cm².",
      explicacion: [
        "Las unidades de superficie son el cuadrado de las unidades de longitud: m², cm², km², etc. Para convertir entre ellas, el factor de conversión se eleva al cuadrado.",
        "1 m² = (100 cm)² = 10.000 cm². 1 km² = (1000 m)² = 1.000.000 m².",
        "También existen unidades agrarias: 1 hectárea (ha) = 10.000 m². 1 km² = 100 ha. Una cancha de fútbol estándar tiene aproximadamente 0,7 ha.",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 3 m² a cm²",
          pasos: [
            { texto: "1 m² = 10.000 cm²" },
            { texto: "3 m² = 3 × 10.000 = 30.000 cm²" },
          ],
          resultado: "3 m² = 30.000 cm²",
        },
        {
          enunciado: "Un lote mide 50 m × 30 m. ¿Cuántas hectáreas tiene?",
          pasos: [
            { texto: "Área = 50 × 30 = 1.500 m²" },
            { texto: "1 ha = 10.000 m²" },
            { texto: "1.500 ÷ 10.000 = 0,15 ha" },
          ],
          resultado: "El lote tiene 0,15 ha",
        },
      ],
      ejercicios: [
        {
          id: "5-4-2-e1",
          enunciado: "¿Cuántos cm² equivalen a 5 m²?",
          tipo: "numero",
          respuesta: "50000",
          pista: "1 m² = 10.000 cm². Multiplica.",
          explicacion: "5 × 10.000 = 50.000 cm².",
        },
        {
          id: "5-4-2-e2",
          enunciado: "Un patio mide 8 m × 6 m. ¿Cuántos m² tiene?",
          tipo: "numero",
          respuesta: "48",
          pista: "Área de rectángulo = largo × ancho.",
          explicacion: "8 × 6 = 48 m².",
        },
        {
          id: "5-4-2-e3",
          enunciado: "¿Cuántos m² tiene 1 hectárea?",
          tipo: "numero",
          respuesta: "10000",
          pista: "Una hectárea es un cuadrado de 100 m de lado.",
          explicacion: "1 ha = 100 m × 100 m = 10.000 m².",
        },
        {
          id: "5-4-2-e4",
          enunciado: "Convierte 25.000 cm² a m²",
          tipo: "texto",
          respuesta: "2,5",
          pista: "Divide entre 10.000 (ya que 1 m² = 10.000 cm²).",
          explicacion: "25.000 ÷ 10.000 = 2,5 m².",
        },
      ],
    },
    {
      id: "5-4-3",
      titulo: "Relación entre área y perímetro",
      objetivo: "Comprender que área y perímetro son medidas diferentes y que no son proporcionales entre sí.",
      concepto_clave: "Perímetro: suma de los lados (longitud del borde). Área: superficie interior. Figuras con igual perímetro pueden tener diferente área y viceversa.",
      explicacion: [
        "El PERÍMETRO es la longitud del contorno de una figura (suma de todos sus lados). El ÁREA es la medida de la superficie que ocupa la figura.",
        "Una idea sorprendente: dos figuras pueden tener el mismo perímetro pero diferente área, o el mismo área pero diferente perímetro. No existe una relación fija entre ellos.",
        "Entre todos los rectángulos con el mismo perímetro, el CUADRADO siempre tiene el mayor área. Por eso las ciudades y campos cuadrados 'aprovechan mejor' el espacio.",
      ],
      ejemplos: [
        {
          enunciado: "Un rectángulo de 4×6 y un cuadrado de 5×5. ¿Cuál tiene mayor área si tienen perímetros similares?",
          pasos: [
            { texto: "Perímetro rectángulo: 2(4+6) = 20" },
            { texto: "Perímetro cuadrado: 4×5 = 20 (iguales!)" },
            { texto: "Área rectángulo: 4×6 = 24 m²" },
            { texto: "Área cuadrado: 5×5 = 25 m²" },
          ],
          resultado: "Con el mismo perímetro (20), el cuadrado tiene mayor área (25>24)",
        },
      ],
      ejercicios: [
        {
          id: "5-4-3-e1",
          enunciado: "Un cuadrado de lado 6 cm. ¿Cuál es su perímetro y área?",
          tipo: "texto",
          respuesta: "Perímetro 24 cm, área 36 cm²",
          pista: "Perímetro = 4 × lado. Área = lado × lado.",
          explicacion: "Perímetro = 4×6 = 24 cm. Área = 6×6 = 36 cm².",
        },
        {
          id: "5-4-3-e2",
          enunciado: "¿Pueden dos rectángulos diferentes tener el mismo área?",
          tipo: "seleccion",
          opciones: ["No, el área es única para cada figura", "Sí, por ejemplo 2×6 y 3×4 tienen la misma área"],
          respuesta: "Sí, por ejemplo 2×6 y 3×4 tienen la misma área",
          pista: "2×6=12 y 3×4=12.",
          explicacion: "Sí. El rectángulo 2×6 tiene área 12 cm² y el 3×4 también tiene área 12 cm². Mismo área, diferente forma y diferente perímetro.",
        },
        {
          id: "5-4-3-e3",
          enunciado: "Un jardín rectangular tiene área de 24 m². Si el largo es 8 m, ¿cuánto mide el ancho?",
          tipo: "numero",
          respuesta: "3",
          pista: "Área = largo × ancho → ancho = área ÷ largo.",
          explicacion: "Ancho = 24 ÷ 8 = 3 m.",
        },
        {
          id: "5-4-3-e4",
          enunciado: "Si duplicas los lados de un cuadrado, ¿cuántas veces crece el área?",
          tipo: "numero",
          respuesta: "4",
          pista: "Si lado original = L, área original = L². Nuevo lado = 2L, nueva área = (2L)².",
          explicacion: "(2L)² = 4L². El área se multiplica por 4 cuando el lado se duplica.",
        },
      ],
    },
    {
      id: "5-4-4",
      titulo: "Unidades de capacidad y conversiones",
      objetivo: "Convertir entre unidades de capacidad (kL, hL, daL, L, dL, cL, mL).",
      concepto_clave: "Litro (L) es la unidad principal. Las conversiones son por factores de 10. 1 L = 10 dL = 100 cL = 1000 mL.",
      explicacion: [
        "La capacidad mide cuánto líquido cabe en un recipiente. La unidad principal es el LITRO (L). Las demás unidades siguen el mismo patrón del sistema métrico: cada unidad es 10 veces la siguiente.",
        "De mayor a menor: kilolitro (kL), hectolitro (hL), decalitro (daL), LITRO (L), decilitro (dL), centilitro (cL), mililitro (mL).",
        "Equivalencias más usadas: 1 L = 1.000 mL, 1 L = 10 dL, 1 L = 100 cL. Una lata de gaseosa tiene 330 mL = 0,33 L.",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 2,5 L a mL",
          pasos: [
            { texto: "L → mL: bajo 3 escalones → multiplico por 1000" },
            { texto: "2,5 × 1000 = 2500" },
          ],
          resultado: "2,5 L = 2.500 mL",
        },
        {
          enunciado: "Convierte 750 mL a litros",
          pasos: [
            { texto: "mL → L: subo 3 escalones → divido entre 1000" },
            { texto: "750 ÷ 1000 = 0,75" },
          ],
          resultado: "750 mL = 0,75 L",
        },
      ],
      ejercicios: [
        {
          id: "5-4-4-e1",
          enunciado: "Convierte 3 L a mililitros",
          tipo: "numero",
          respuesta: "3000",
          pista: "1 L = 1.000 mL.",
          explicacion: "3 × 1000 = 3.000 mL.",
        },
        {
          id: "5-4-4-e2",
          enunciado: "Una receta pide 250 mL de leche. ¿Cuántos litros son?",
          tipo: "texto",
          respuesta: "0,25",
          pista: "250 ÷ 1000 = ?",
          explicacion: "250 ÷ 1000 = 0,25 L.",
        },
        {
          id: "5-4-4-e3",
          enunciado: "Tengo 4 botellas de 330 mL. ¿Cuántos litros en total?",
          tipo: "texto",
          respuesta: "1,32",
          pista: "Total mL = 4 × 330 = 1320. Luego convierte a litros.",
          explicacion: "4 × 330 = 1.320 mL. 1.320 ÷ 1000 = 1,32 L.",
        },
        {
          id: "5-4-4-e4",
          enunciado: "¿Cuántos vasos de 200 mL caben en 2 litros?",
          tipo: "numero",
          respuesta: "10",
          pista: "2 litros = 2000 mL. 2000 ÷ 200 = ?",
          explicacion: "2.000 ÷ 200 = 10 vasos.",
        },
      ],
    },
    {
      id: "5-4-5",
      titulo: "Unidades de volumen y conversiones",
      objetivo: "Calcular volúmenes de prismas rectangulares y convertir entre cm³, dm³ y m³.",
      concepto_clave: "Volumen = largo × ancho × alto. 1 m³ = 1.000 dm³ = 1.000.000 cm³. El factor se ELEVA AL CUBO.",
      explicacion: [
        "El VOLUMEN mide el espacio tridimensional que ocupa un sólido. Para un prisma rectangular: V = largo × ancho × alto.",
        "Las unidades de volumen son el cubo de las unidades de longitud: cm³, dm³, m³. Al convertir, el factor se eleva al cubo: 1 m = 10 dm → 1 m³ = 10³ dm³ = 1.000 dm³.",
        "La relación entre el dm³ y el litro es clave: 1 dm³ = 1 L. Por eso 1 m³ = 1.000 L = 1 kL.",
      ],
      ejemplos: [
        {
          enunciado: "Calcula el volumen de una caja de 4 cm × 3 cm × 5 cm",
          pasos: [
            { texto: "V = largo × ancho × alto" },
            { texto: "V = 4 × 3 × 5 = 60" },
          ],
          resultado: "V = 60 cm³",
        },
        {
          enunciado: "Convierte 2 m³ a dm³",
          pasos: [
            { texto: "1 m = 10 dm → 1 m³ = 10³ dm³ = 1.000 dm³" },
            { texto: "2 m³ = 2 × 1.000 = 2.000 dm³" },
          ],
          resultado: "2 m³ = 2.000 dm³",
        },
      ],
      ejercicios: [
        {
          id: "5-4-5-e1",
          enunciado: "Calcula el volumen de un cubo de 3 cm de lado",
          tipo: "numero",
          respuesta: "27",
          pista: "V = lado³ = 3 × 3 × 3.",
          explicacion: "V = 3³ = 27 cm³.",
        },
        {
          id: "5-4-5-e2",
          enunciado: "¿Cuántos cm³ tiene 1 dm³?",
          tipo: "numero",
          respuesta: "1000",
          pista: "1 dm = 10 cm → 1 dm³ = 10³ cm³.",
          explicacion: "1 dm³ = 10 × 10 × 10 = 1.000 cm³.",
        },
        {
          id: "5-4-5-e3",
          enunciado: "Una pecera mide 50 cm × 30 cm × 40 cm. ¿Cuántos litros caben? (1 L = 1 dm³ = 1.000 cm³)",
          tipo: "numero",
          respuesta: "60",
          pista: "Volumen en cm³ = 50×30×40. Luego ÷ 1000 para litros.",
          explicacion: "V = 50×30×40 = 60.000 cm³. 60.000 ÷ 1.000 = 60 L.",
        },
        {
          id: "5-4-5-e4",
          enunciado: "Convierte 4.500 cm³ a dm³",
          tipo: "texto",
          respuesta: "4,5",
          pista: "÷1000.",
          explicacion: "4.500 ÷ 1.000 = 4,5 dm³.",
        },
      ],
    },
    {
      id: "5-4-6",
      titulo: "Relación entre unidades de volumen y capacidad",
      objetivo: "Aplicar la equivalencia entre dm³ y litro para resolver problemas de capacidad y volumen.",
      concepto_clave: "1 dm³ = 1 L. 1 cm³ = 1 mL. Esta equivalencia conecta el volumen con la capacidad.",
      explicacion: [
        "La relación más importante entre volumen y capacidad: 1 dm³ = 1 L (un litro ocupa exactamente 1 dm³). También: 1 cm³ = 1 mL.",
        "Esto significa que cuando calculamos el volumen de un recipiente en dm³, obtenemos directamente su capacidad en litros.",
        "Ejemplo práctico: un botellón de agua tiene volumen de 20 dm³ → cabe exactamente 20 L de agua.",
      ],
      ejemplos: [
        {
          enunciado: "Una pileta tiene 3 m × 2 m × 1,5 m. ¿Cuántos litros caben?",
          pasos: [
            { texto: "Primero convierte a dm: 30 dm × 20 dm × 15 dm" },
            { texto: "V = 30 × 20 × 15 = 9.000 dm³" },
            { texto: "1 dm³ = 1 L → 9.000 L" },
          ],
          resultado: "La pileta tiene capacidad de 9.000 L",
        },
      ],
      ejercicios: [
        {
          id: "5-4-6-e1",
          enunciado: "Una caja tiene volumen de 500 cm³. ¿Cuántos mL de líquido caben?",
          tipo: "numero",
          respuesta: "500",
          pista: "1 cm³ = 1 mL.",
          explicacion: "500 cm³ = 500 mL.",
        },
        {
          id: "5-4-6-e2",
          enunciado: "¿Cuántos dm³ caben en un recipiente de 3,5 litros?",
          tipo: "texto",
          respuesta: "3,5",
          pista: "1 L = 1 dm³.",
          explicacion: "3,5 L = 3,5 dm³.",
        },
        {
          id: "5-4-6-e3",
          enunciado: "Una heladera tiene volumen interno de 0,3 m³. ¿Cuántos litros de capacidad tiene?",
          tipo: "numero",
          respuesta: "300",
          pista: "0,3 m³ = ? dm³. Luego 1 dm³ = 1 L.",
          explicacion: "0,3 m³ = 300 dm³ = 300 L.",
        },
        {
          id: "5-4-6-e4",
          enunciado: "¿Cuántos mL hay en 1 m³?",
          tipo: "numero",
          respuesta: "1000000",
          pista: "1 m³ = 1.000.000 cm³ = 1.000.000 mL.",
          explicacion: "1 m³ = 1.000.000 cm³ y 1 cm³ = 1 mL. Por tanto 1 m³ = 1.000.000 mL.",
        },
      ],
    },
    {
      id: "5-4-7",
      titulo: "Área del cuadrado y volumen del cubo",
      objetivo: "Calcular el área del cuadrado (l²) y el volumen del cubo (l³) y hallar el lado conociendo el área o volumen.",
      concepto_clave: "Cuadrado: Área = l². Cubo: Volumen = l³. Inversos: l = √Área (cuadrado) y l = ³√Volumen (cubo).",
      explicacion: [
        "El cuadrado y el cubo son figuras especiales porque tienen todos sus lados iguales. Esto simplifica enormemente sus fórmulas.",
        "CUADRADO: Área = l × l = l². Si el área es 49 cm², el lado es √49 = 7 cm.",
        "CUBO: Volumen = l × l × l = l³. Si el volumen es 125 cm³, el lado es ³√125 = 5 cm (porque 5³ = 125).",
      ],
      ejemplos: [
        {
          enunciado: "Un cuadrado tiene área de 81 m². ¿Cuánto mide su lado?",
          pasos: [
            { texto: "Área = l² → l = √Área" },
            { texto: "l = √81 = 9 m (porque 9² = 81)" },
          ],
          resultado: "El lado mide 9 m",
        },
        {
          enunciado: "Un cubo tiene volumen de 64 cm³. ¿Cuánto mide su arista?",
          pasos: [
            { texto: "V = l³ → l = ³√V" },
            { texto: "l = ³√64 = 4 cm (porque 4³ = 64)" },
          ],
          resultado: "La arista mide 4 cm",
        },
      ],
      ejercicios: [
        {
          id: "5-4-7-e1",
          enunciado: "¿Cuánto mide el área de un cuadrado de lado 12 cm?",
          tipo: "numero",
          respuesta: "144",
          pista: "Área = 12² = 12 × 12.",
          explicacion: "12 × 12 = 144 cm².",
        },
        {
          id: "5-4-7-e2",
          enunciado: "Un cubo tiene arista de 5 cm. ¿Cuánto es su volumen?",
          tipo: "numero",
          respuesta: "125",
          pista: "V = 5³ = 5 × 5 × 5.",
          explicacion: "5 × 5 × 5 = 125 cm³.",
        },
        {
          id: "5-4-7-e3",
          enunciado: "El área de un cuadrado es 100 m². ¿Cuánto mide su perímetro?",
          tipo: "numero",
          respuesta: "40",
          pista: "Primero halla el lado: l = √100. Luego el perímetro = 4 × l.",
          explicacion: "l = √100 = 10 m. Perímetro = 4 × 10 = 40 m.",
        },
        {
          id: "5-4-7-e4",
          enunciado: "¿Cuántas cajas cúbicas de 10 cm de arista caben en un metro cúbico?",
          tipo: "numero",
          respuesta: "1000",
          pista: "Volumen de cada caja = 10³ = 1.000 cm³. 1 m³ = 1.000.000 cm³. Divide.",
          explicacion: "1.000.000 ÷ 1.000 = 1.000 cajas.",
        },
      ],
    },
    {
      id: "5-4-8",
      titulo: "Unidades de masa y conversiones",
      objetivo: "Convertir entre unidades de masa (t, kg, g, mg) y resolver problemas de pesaje.",
      concepto_clave: "1 t = 1.000 kg. 1 kg = 1.000 g. 1 g = 1.000 mg. La tonelada métrica equivale a 1.000 kg.",
      explicacion: [
        "La masa mide la cantidad de materia. Las unidades principales son: TONELADA (t), KILOGRAMO (kg), GRAMO (g), MILIGRAMO (mg).",
        "A diferencia de las unidades de longitud (que van de 10 en 10), las unidades de masa más usadas van de 1.000 en 1.000: 1 t = 1.000 kg, 1 kg = 1.000 g, 1 g = 1.000 mg.",
        "Ejemplos de masas cotidianas: una moneda ≈ 5 g, un libro ≈ 300 g, un estudiante ≈ 40 kg, un carro ≈ 1,5 t.",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 2,5 kg a gramos",
          pasos: [
            { texto: "1 kg = 1.000 g" },
            { texto: "2,5 × 1.000 = 2.500 g" },
          ],
          resultado: "2,5 kg = 2.500 g",
        },
        {
          enunciado: "Convierte 3.500 g a kg",
          pasos: [
            { texto: "g → kg: ÷ 1.000" },
            { texto: "3.500 ÷ 1.000 = 3,5 kg" },
          ],
          resultado: "3.500 g = 3,5 kg",
        },
      ],
      ejercicios: [
        {
          id: "5-4-8-e1",
          enunciado: "Convierte 4,5 kg a gramos",
          tipo: "numero",
          respuesta: "4500",
          pista: "× 1000.",
          explicacion: "4,5 × 1.000 = 4.500 g.",
        },
        {
          id: "5-4-8-e2",
          enunciado: "Convierte 2 toneladas a kilogramos",
          tipo: "numero",
          respuesta: "2000",
          pista: "1 t = 1.000 kg.",
          explicacion: "2 × 1.000 = 2.000 kg.",
        },
        {
          id: "5-4-8-e3",
          enunciado: "Un camión carga 850 kg. ¿Cuántas toneladas es?",
          tipo: "texto",
          respuesta: "0,85",
          pista: "kg → t: ÷1000.",
          explicacion: "850 ÷ 1.000 = 0,85 t.",
        },
        {
          id: "5-4-8-e4",
          enunciado: "Compro 3 paquetes de 750 g de arroz. ¿Cuántos kg de arroz tengo?",
          tipo: "texto",
          respuesta: "2,25",
          pista: "Total g = 3 × 750 = 2250. Luego ÷ 1000.",
          explicacion: "3 × 750 = 2.250 g. 2.250 ÷ 1.000 = 2,25 kg.",
        },
      ],
    },
    {
      id: "5-4-9",
      titulo: "Unidades de tiempo y conversiones",
      objetivo: "Convertir entre unidades de tiempo y resolver problemas con operaciones de tiempo.",
      concepto_clave: "60 seg = 1 min. 60 min = 1 hora. 24 h = 1 día. 7 días = 1 semana. 365 días = 1 año.",
      explicacion: [
        "Las unidades de tiempo no siguen el sistema decimal. Las equivalencias son: 60 segundos = 1 minuto, 60 minutos = 1 hora, 24 horas = 1 día, 7 días = 1 semana, 4 semanas ≈ 1 mes, 12 meses = 1 año, 365 días = 1 año.",
        "Para convertir de una unidad mayor a menor: multiplicas por el factor. Para ir de menor a mayor: divides.",
        "Para SUMAR tiempos: suma cada unidad por separado y 'convierte' cuando supera el límite (60 segundos = 1 minuto, etc.). Para RESTAR: si no alcanza, 'prestas' de la unidad superior.",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 3 horas y 45 minutos a minutos",
          pasos: [
            { texto: "3 horas = 3 × 60 = 180 minutos" },
            { texto: "180 + 45 = 225 minutos" },
          ],
          resultado: "3 h 45 min = 225 minutos",
        },
        {
          enunciado: "Suma: 2 h 45 min + 1 h 30 min",
          pasos: [
            { texto: "Minutos: 45 + 30 = 75 min = 1 h 15 min" },
            { texto: "Horas: 2 + 1 + 1 (llevada) = 4 h" },
          ],
          resultado: "4 h 15 min",
        },
      ],
      ejercicios: [
        {
          id: "5-4-9-e1",
          enunciado: "¿Cuántos minutos son 2 horas?",
          tipo: "numero",
          respuesta: "120",
          pista: "1 hora = 60 minutos.",
          explicacion: "2 × 60 = 120 minutos.",
        },
        {
          id: "5-4-9-e2",
          enunciado: "Convierte 150 minutos a horas y minutos",
          tipo: "texto",
          respuesta: "2 horas y 30 minutos",
          pista: "150 ÷ 60 = 2 horas con residuo 30 minutos.",
          explicacion: "150 ÷ 60 = 2 (resto 30). 150 minutos = 2 horas y 30 minutos.",
        },
        {
          id: "5-4-9-e3",
          enunciado: "Una película dura 1 h 40 min. Empieza a las 7:30 pm. ¿A qué hora termina?",
          tipo: "texto",
          respuesta: "9:10 pm",
          pista: "7:30 + 1:40. Suma minutos: 30+40=70 min=1h 10min. Suma horas: 7+1+1=9.",
          explicacion: "7:30 + 1:40 = 8:70 = 9:10 pm.",
        },
        {
          id: "5-4-9-e4",
          enunciado: "¿Cuántos segundos hay en 1 hora?",
          tipo: "numero",
          respuesta: "3600",
          pista: "1 hora = 60 min. 1 min = 60 seg. Multiplica.",
          explicacion: "60 × 60 = 3.600 segundos.",
        },
      ],
    },
    {
      id: "5-4-10",
      titulo: "Unidades de temperatura y conversiones",
      objetivo: "Leer temperaturas en Celsius y Fahrenheit y convertir entre ambas escalas.",
      concepto_clave: "Celsius (°C): 0° = agua congela, 100° = agua hierve. Fahrenheit (°F): 32° = congela, 212° = hierve. °F = °C × 9/5 + 32.",
      explicacion: [
        "La temperatura mide el calor de un cuerpo. Las dos escalas más usadas son CELSIUS (°C) y FAHRENHEIT (°F). En Colombia usamos Celsius, pero en EE.UU. se usa Fahrenheit.",
        "Puntos de referencia: Celsius: 0°C congela el agua, 37°C es la temperatura corporal normal, 100°C hierve el agua.",
        "Conversiones: °F = °C × (9/5) + 32 y °C = (°F − 32) × (5/9). Ejemplo: 37°C = 37 × 9/5 + 32 = 66,6 + 32 = 98,6°F.",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 100°C a Fahrenheit",
          pasos: [
            { texto: "°F = 100 × (9/5) + 32" },
            { texto: "= 100 × 1,8 + 32" },
            { texto: "= 180 + 32 = 212" },
          ],
          resultado: "100°C = 212°F",
        },
        {
          enunciado: "Convierte 68°F a Celsius",
          pasos: [
            { texto: "°C = (68 − 32) × 5/9" },
            { texto: "= 36 × 5/9 = 180/9 = 20" },
          ],
          resultado: "68°F = 20°C",
        },
      ],
      ejercicios: [
        {
          id: "5-4-10-e1",
          enunciado: "¿A cuántos °F equivale 0°C (punto de congelación del agua)?",
          tipo: "numero",
          respuesta: "32",
          pista: "°F = 0 × 9/5 + 32.",
          explicacion: "0 × 1,8 + 32 = 32°F.",
        },
        {
          id: "5-4-10-e2",
          enunciado: "La temperatura corporal normal es 98,6°F. ¿Cuántos °C son?",
          tipo: "numero",
          respuesta: "37",
          pista: "°C = (98,6 − 32) × 5/9.",
          explicacion: "(98,6 − 32) × 5/9 = 66,6 × 5/9 = 333/9 = 37°C.",
        },
        {
          id: "5-4-10-e3",
          enunciado: "Si afuera hay 25°C, ¿hace frío o calor?",
          tipo: "seleccion",
          opciones: ["Mucho frío (menos de 10°C)", "Fresco/agradable (entre 18°C y 28°C)", "Mucho calor (más de 35°C)"],
          respuesta: "Fresco/agradable (entre 18°C y 28°C)",
          pista: "25°C es la temperatura típica de un día agradable en Colombia.",
          explicacion: "25°C es una temperatura agradable. El frío empieza a sentirse por debajo de 18°C y el calor intenso por encima de 30°C.",
        },
        {
          id: "5-4-10-e4",
          enunciado: "¿A qué temperatura son iguales los grados Celsius y Fahrenheit? (°C = °F)",
          tipo: "numero",
          respuesta: "-40",
          pista: "Plantea la ecuación: x = x × 9/5 + 32. Despeja x.",
          explicacion: "Si °C = °F = x: x = 9x/5 + 32 → x − 9x/5 = 32 → −4x/5 = 32 → x = −40. A −40° ambas escalas coinciden.",
        },
      ],
    },
  ],
}

export default unidad4
