import type { Unidad } from "../tipos"

const unidad6: Unidad = {
  id: 6,
  nombre: "Proporcionalidad y ecuaciones",
  descripcion: "Descubre razones, proporciones, magnitudes proporcionales y aprende a resolver ecuaciones.",
  color: "red",
  icono: "⚖️",
  lecciones: [
    {
      id: "5-6-1",
      titulo: "Razones",
      objetivo: "Expresar relaciones entre cantidades como razones y simplificarlas.",
      concepto_clave: "Razón a:b = a/b. Compara dos cantidades del mismo tipo. Se simplifica dividiendo ambos términos por su MCD.",
      explicacion: [
        "Una RAZÓN es una comparación entre dos cantidades que indica cuántas veces una contiene a la otra. Se expresa como a:b, a/b, o 'a por cada b'.",
        "Una razón de 3:5 significa 'por cada 3 de la primera cantidad hay 5 de la segunda'. Las razones se pueden simplificar dividiendo ambos términos por su MCD.",
        "Las razones son la base de las proporciones, la regla de tres y muchos problemas cotidianos: velocidad (km por hora), precio por unidad, mezclas, escalas...",
      ],
      ejemplos: [
        {
          enunciado: "En una clase hay 14 niñas y 21 niños. ¿Cuál es la razón de niñas a niños?",
          pasos: [
            { texto: "Razón = 14:21" },
            { texto: "MCD(14,21) = 7" },
            { texto: "14÷7 : 21÷7 = 2:3" },
          ],
          resultado: "La razón de niñas a niños es 2:3 (por cada 2 niñas hay 3 niños)",
        },
        {
          enunciado: "Si la razón de azúcar a harina en una receta es 2:5, ¿cuánta azúcar necesito si uso 400 g de harina?",
          pasos: [
            { texto: "Razón 2:5. Por cada 5 g de harina → 2 g de azúcar" },
            { texto: "400 g de harina → 400 × (2/5) = 160 g de azúcar" },
          ],
          resultado: "Necesito 160 g de azúcar",
        },
      ],
      ejercicios: [
        {
          id: "5-6-1-e1",
          enunciado: "Simplifica la razón 18:24",
          tipo: "texto",
          respuesta: "3:4",
          pista: "MCD(18,24)=6. Divide ambos entre 6.",
          explicacion: "18÷6=3 y 24÷6=4. Razón simplificada: 3:4.",
        },
        {
          id: "5-6-1-e2",
          enunciado: "¿Cuántos días hay en 3 semanas? Expresa la razón días:semanas",
          tipo: "texto",
          respuesta: "7:1",
          pista: "1 semana = 7 días. ¿Cuántos días hay por cada semana?",
          explicacion: "Por cada 1 semana hay 7 días. Razón días:semanas = 7:1.",
        },
        {
          id: "5-6-1-e3",
          enunciado: "Un carro recorre 240 km con 20 litros. ¿Cuántos km recorre por litro?",
          tipo: "numero",
          respuesta: "12",
          pista: "Razón km:litros = 240:20. Simplifica.",
          explicacion: "240÷20 = 12. El carro hace 12 km por litro.",
        },
        {
          id: "5-6-1-e4",
          enunciado: "La razón de estudiantes que pasan a los que pierden un examen es 7:3. Si hay 30 estudiantes, ¿cuántos pasan?",
          tipo: "numero",
          respuesta: "21",
          pista: "7:3 → de cada 10 estudiantes, 7 pasan. ¿Cuántos grupos de 10 hay en 30?",
          explicacion: "7+3=10 partes. 30÷10=3 grupos. Pasan: 7×3=21 estudiantes.",
        },
      ],
    },
    {
      id: "5-6-2",
      titulo: "Proporciones",
      objetivo: "Identificar proporciones y resolver el término desconocido usando la propiedad fundamental.",
      concepto_clave: "Proporción: a:b = c:d equivale a a×d = b×c (el producto de los extremos = producto de los medios).",
      explicacion: [
        "Una PROPORCIÓN es la igualdad entre dos razones: a:b = c:d, que también se escribe a/b = c/d. Los términos a y d se llaman EXTREMOS; b y c se llaman MEDIOS.",
        "PROPIEDAD FUNDAMENTAL: en toda proporción, el producto de los extremos es igual al producto de los medios: a × d = b × c. Esta propiedad nos permite encontrar el término desconocido.",
        "Ejemplo: 2/3 = x/12. Aplicando: 2 × 12 = 3 × x → 24 = 3x → x = 8.",
      ],
      ejemplos: [
        {
          enunciado: "Resuelve: 4/6 = x/15",
          pasos: [
            { texto: "Producto de extremos = producto de medios" },
            { texto: "4 × 15 = 6 × x" },
            { texto: "60 = 6x" },
            { texto: "x = 60 ÷ 6 = 10" },
          ],
          resultado: "x = 10",
        },
        {
          enunciado: "Verifica si 3:4 y 9:12 forman una proporción",
          pasos: [
            { texto: "Extremos × medios: 3 × 12 = 36" },
            { texto: "Medios × extremos: 4 × 9 = 36" },
            { texto: "36 = 36 ✓" },
          ],
          resultado: "Sí forman una proporción (3:4 = 9:12)",
        },
      ],
      ejercicios: [
        {
          id: "5-6-2-e1",
          enunciado: "Resuelve: x/8 = 3/4",
          tipo: "numero",
          respuesta: "6",
          pista: "x × 4 = 8 × 3 → 4x = 24 → x = ?",
          explicacion: "4x = 24 → x = 6.",
        },
        {
          id: "5-6-2-e2",
          enunciado: "¿Forman proporción las razones 5:8 y 15:24?",
          tipo: "seleccion",
          opciones: ["Sí", "No"],
          respuesta: "Sí",
          pista: "Verifica: 5×24 y 8×15.",
          explicacion: "5×24=120 y 8×15=120. Extremos = medios → Sí forman proporción.",
        },
        {
          id: "5-6-2-e3",
          enunciado: "Si 5 bolígrafos cuestan $3.500, ¿cuánto cuestan 12 bolígrafos?",
          tipo: "numero",
          respuesta: "8400",
          pista: "Plantea la proporción: 5/$3500 = 12/x.",
          explicacion: "5×x = 3500×12 → 5x = 42000 → x = 8400.",
        },
        {
          id: "5-6-2-e4",
          enunciado: "En una proporción a:b = c:d, si a=6, b=9, c=8, ¿cuánto es d?",
          tipo: "numero",
          respuesta: "12",
          pista: "a×d = b×c → 6×d = 9×8.",
          explicacion: "6d = 72 → d = 12.",
        },
      ],
    },
    {
      id: "5-6-3",
      titulo: "Magnitudes correlacionadas",
      objetivo: "Identificar pares de magnitudes que se relacionan entre sí y determinar el tipo de relación.",
      concepto_clave: "Dos magnitudes están correlacionadas cuando al cambiar una, la otra también cambia de manera sistemática.",
      explicacion: [
        "Dos magnitudes están CORRELACIONADAS cuando al variar una, la otra también varía de forma predecible. No siempre hay una relación proporcional — pueden relacionarse de otras formas.",
        "Ejemplos de magnitudes correlacionadas: velocidad y tiempo de recorrido (a mayor velocidad, menor tiempo), precio y cantidad de compra (a mayor precio, menor cantidad).",
        "Antes de aplicar 'regla de tres', debes identificar QUÉ TIPO de correlación hay: ¿si una sube, la otra sube también (directa)? ¿O si una sube, la otra baja (inversa)?",
      ],
      ejemplos: [
        {
          enunciado: "¿Cómo se relacionan el número de obreros y el tiempo para construir una casa?",
          pasos: [
            { texto: "Más obreros → cada uno hace su parte → terminan más rápido" },
            { texto: "Cuando una magnitud (obreros) sube, la otra (tiempo) baja" },
          ],
          resultado: "Relación inversamente proporcional",
        },
        {
          enunciado: "¿Cómo se relacionan el número de metros de tela y el costo?",
          pasos: [
            { texto: "Más metros → más dinero hay que pagar" },
            { texto: "Cuando metros sube, el costo también sube" },
          ],
          resultado: "Relación directamente proporcional",
        },
      ],
      ejercicios: [
        {
          id: "5-6-3-e1",
          enunciado: "¿Qué tipo de relación hay entre la velocidad de un carro y el tiempo en llegar a un destino?",
          tipo: "seleccion",
          opciones: ["Directamente proporcional", "Inversamente proporcional", "No están relacionadas"],
          respuesta: "Inversamente proporcional",
          pista: "Si vas más rápido, ¿llegas en más o menos tiempo?",
          explicacion: "A mayor velocidad, menor tiempo. Relación inversa: cuando una sube, la otra baja.",
        },
        {
          id: "5-6-3-e2",
          enunciado: "¿Qué tipo de relación hay entre el ahorro mensual y el tiempo para juntar cierta cantidad de dinero?",
          tipo: "seleccion",
          opciones: ["Directamente proporcional", "Inversamente proporcional"],
          respuesta: "Inversamente proporcional",
          pista: "Si ahorras más cada mes, ¿necesitas más o menos meses?",
          explicacion: "Si ahorras más por mes, tardarás menos meses. Relación inversa.",
        },
        {
          id: "5-6-3-e3",
          enunciado: "¿El precio de la gasolina y la cantidad de kilómetros que puedes recorrer con $20.000 tienen relación directa o inversa?",
          tipo: "seleccion",
          opciones: ["Directa (más precio, más km)", "Inversa (más precio, menos km con el mismo dinero)"],
          respuesta: "Inversa (más precio, menos km con el mismo dinero)",
          pista: "Si la gasolina sube de precio, ¿con $20.000 compras más o menos litros?",
          explicacion: "Si el precio sube, con la misma plata compras menos litros y recorres menos kilómetros. Relación inversa.",
        },
        {
          id: "5-6-3-e4",
          enunciado: "¿Las magnitudes 'número de pisos de un edificio' y 'tiempo en subir por las escaleras' son proporcionales?",
          tipo: "seleccion",
          opciones: ["Sí, directamente proporcionales", "No necesariamente, depende de la velocidad al subir"],
          respuesta: "Sí, directamente proporcionales",
          pista: "Si cada piso tarda el mismo tiempo, a más pisos más tiempo.",
          explicacion: "Asumiendo velocidad constante, el tiempo es directamente proporcional al número de pisos.",
        },
      ],
    },
    {
      id: "5-6-4",
      titulo: "Magnitudes directamente proporcionales",
      objetivo: "Resolver problemas de proporcionalidad directa usando la regla de tres simple directa.",
      concepto_clave: "Proporcionalidad directa: si una magnitud se multiplica por k, la otra también. Regla de tres: a/b = c/x → x = b×c/a.",
      explicacion: [
        "Dos magnitudes son DIRECTAMENTE PROPORCIONALES si al multiplicar una por un número, la otra queda multiplicada por el mismo número. La razón entre valores correspondientes siempre es constante (k = constante de proporcionalidad).",
        "La REGLA DE TRES SIMPLE DIRECTA sirve para encontrar un valor desconocido cuando se conocen tres. Se plantea la proporción y se despeja.",
        "Pasos: 1) Identifica que son directamente proporcionales. 2) Organiza los datos en una tabla. 3) Plantea la proporción y resuelve. Ej: 4 litros de pintura dan para 16 m². ¿Cuántos litros para 28 m²? → 4/16 = x/28 → x = 7.",
      ],
      ejemplos: [
        {
          enunciado: "Si 3 kg de naranjas cuestan $6.000, ¿cuánto cuestan 7 kg?",
          pasos: [
            { texto: "Relación directa: más kg → más precio" },
            { texto: "3/$6.000 = 7/x" },
            { texto: "3x = 6.000 × 7 = 42.000" },
            { texto: "x = 42.000 ÷ 3 = 14.000" },
          ],
          resultado: "7 kg de naranjas cuestan $14.000",
        },
      ],
      ejercicios: [
        {
          id: "5-6-4-e1",
          enunciado: "Si un grifo llena 5 cubos de agua en 20 minutos, ¿cuántos minutos tarda en llenar 8 cubos?",
          tipo: "numero",
          respuesta: "32",
          pista: "Relación directa. 5/20 = 8/x. Despeja x.",
          explicacion: "5x = 20×8 = 160. x = 32 minutos.",
        },
        {
          id: "5-6-4-e2",
          enunciado: "5 obreros construyen una pared en 6 días. ¿Cuántos días tardan 10 obreros? (misma capacidad de trabajo)",
          tipo: "seleccion",
          opciones: ["12 días (proporcionalidad directa)", "3 días (proporcionalidad inversa)", "6 días (no cambia)"],
          respuesta: "3 días (proporcionalidad inversa)",
          pista: "Más obreros → ¿más o menos días? Cuidado con el tipo de proporcionalidad.",
          explicacion: "Más obreros → menos días. Es INVERSA, no directa. 5×6 = 10×x → x = 3 días.",
        },
        {
          id: "5-6-4-e3",
          enunciado: "Si 2 lápices cuestan $1.600, ¿cuánto cuestan 5 lápices?",
          tipo: "numero",
          respuesta: "4000",
          pista: "2/$1.600 = 5/x. 2x = 1600×5.",
          explicacion: "2x = 8.000 → x = 4.000.",
        },
        {
          id: "5-6-4-e4",
          enunciado: "Una impresora hace 40 copias en 5 minutos. ¿Cuántas copias hace en 12 minutos?",
          tipo: "numero",
          respuesta: "96",
          pista: "40/5 = x/12. 5x = 40×12.",
          explicacion: "5x = 480 → x = 96 copias.",
        },
      ],
    },
    {
      id: "5-6-5",
      titulo: "Magnitudes inversamente proporcionales",
      objetivo: "Resolver problemas de proporcionalidad inversa usando la regla de tres inversa.",
      concepto_clave: "Proporcionalidad inversa: si una magnitud se multiplica por k, la otra queda dividida por k. El PRODUCTO de correspondientes es constante: a×b = c×d.",
      explicacion: [
        "Dos magnitudes son INVERSAMENTE PROPORCIONALES si cuando una aumenta, la otra disminuye de tal modo que su PRODUCTO siempre es el mismo. Ejemplo: velocidad × tiempo = distancia (constante).",
        "Para la REGLA DE TRES INVERSA: al plantear la proporción, se invierte uno de los pares. Si a→b y c→x: a/c = x/b (se cruzan). O también: a×b = c×x (producto constante).",
        "Clave para identificar proporcionalidad inversa: '¿Si uno sube, el otro baja?' Si sí → inversa.",
      ],
      ejemplos: [
        {
          enunciado: "4 obreros pintan una casa en 6 días. ¿Cuántos días tardan 8 obreros?",
          pasos: [
            { texto: "Más obreros → menos días → relación inversa" },
            { texto: "Producto constante: 4 × 6 = 8 × x" },
            { texto: "24 = 8x → x = 3" },
          ],
          resultado: "8 obreros tardan 3 días",
        },
        {
          enunciado: "A 60 km/h un viaje dura 4 horas. ¿Cuánto dura a 80 km/h?",
          pasos: [
            { texto: "Mayor velocidad → menos tiempo → relación inversa" },
            { texto: "60 × 4 = 80 × x → 240 = 80x" },
            { texto: "x = 3" },
          ],
          resultado: "A 80 km/h el viaje dura 3 horas",
        },
      ],
      ejercicios: [
        {
          id: "5-6-5-e1",
          enunciado: "3 bombas llenan un tanque en 8 horas. ¿Cuántas horas necesitan 6 bombas?",
          tipo: "numero",
          respuesta: "4",
          pista: "Relación inversa. 3×8 = 6×x.",
          explicacion: "24 = 6x → x = 4 horas.",
        },
        {
          id: "5-6-5-e2",
          enunciado: "Hay comida para 30 personas durante 10 días. ¿Cuántos días dura la misma comida para 50 personas?",
          tipo: "numero",
          respuesta: "6",
          pista: "Relación inversa: más personas, menos días. 30×10 = 50×x.",
          explicacion: "300 = 50x → x = 6 días.",
        },
        {
          id: "5-6-5-e3",
          enunciado: "A 90 km/h un carro llega en 2 horas. ¿A qué velocidad llega en 3 horas?",
          tipo: "numero",
          respuesta: "60",
          pista: "90×2 = x×3.",
          explicacion: "180 = 3x → x = 60 km/h.",
        },
        {
          id: "5-6-5-e4",
          enunciado: "¿Cuál es la diferencia clave entre regla de tres directa e inversa?",
          tipo: "texto",
          respuesta: "En la directa, cuando una magnitud aumenta la otra también aumenta. En la inversa, cuando una aumenta la otra disminuye (su producto permanece constante).",
          pista: "Piensa en el comportamiento de las magnitudes: ¿suben juntas o una baja cuando la otra sube?",
          explicacion: "Directa: ambas magnitudes varían en el mismo sentido (las dos suben o las dos bajan). Inversa: varían en sentido contrario.",
        },
      ],
    },
    {
      id: "5-6-6",
      titulo: "Igualdades y desigualdades",
      objetivo: "Distinguir entre igualdades y desigualdades y representarlas en la recta numérica.",
      concepto_clave: "Igualdad: a = b. Desigualdad: a < b (a menor que b), a > b (a mayor que b), a ≤ b, a ≥ b.",
      explicacion: [
        "Una IGUALDAD es una expresión matemática que afirma que dos expresiones tienen el mismo valor: 3 + 5 = 8. Una DESIGUALDAD afirma que una es mayor o menor que la otra.",
        "Símbolos de desigualdad: < (menor que), > (mayor que), ≤ (menor o igual), ≥ (mayor o igual). Ejemplo: 3 < 7 se lee 'tres es menor que siete'.",
        "Las desigualdades pueden tener una variable: x > 5 significa 'todos los números mayores que 5'. Su solución no es un número único sino un conjunto infinito de valores.",
      ],
      ejemplos: [
        {
          enunciado: "¿Es verdadera la desigualdad 7 + 3 ≥ 2 × 5?",
          pasos: [
            { texto: "Calculo cada lado: 7 + 3 = 10 y 2 × 5 = 10" },
            { texto: "10 ≥ 10: ¿es 10 mayor o igual a 10? Sí (son iguales)" },
          ],
          resultado: "Verdadera (10 ≥ 10 porque son iguales)",
        },
        {
          enunciado: "¿Qué valores de x satisfacen x + 3 > 8?",
          pasos: [
            { texto: "x + 3 > 8 → x > 8 − 3 → x > 5" },
            { texto: "Todos los números mayores que 5: 6, 7, 8, 9, 6.5, 100..." },
          ],
          resultado: "x > 5 (todos los números mayores que 5)",
        },
      ],
      ejercicios: [
        {
          id: "5-6-6-e1",
          enunciado: "¿Es verdadera o falsa: 5 × 4 > 3 × 7?",
          tipo: "seleccion",
          opciones: ["Verdadera", "Falsa"],
          respuesta: "Falsa",
          pista: "5×4=20 y 3×7=21. ¿Es 20 > 21?",
          explicacion: "5×4=20 y 3×7=21. 20 > 21 es FALSO. Lo correcto sería 20 < 21.",
        },
        {
          id: "5-6-6-e2",
          enunciado: "Coloca el símbolo correcto (<, >, =) entre: 3/4 ___ 0,7",
          tipo: "seleccion",
          opciones: ["3/4 < 0,7", "3/4 = 0,7", "3/4 > 0,7"],
          respuesta: "3/4 > 0,7",
          pista: "Convierte 3/4 a decimal.",
          explicacion: "3/4 = 0,75. Como 0,75 > 0,7, entonces 3/4 > 0,7.",
        },
        {
          id: "5-6-6-e3",
          enunciado: "¿Cuántos números enteros satisfacen: 2 < x < 7?",
          tipo: "numero",
          respuesta: "4",
          pista: "Los enteros entre 2 y 7 (sin incluir 2 ni 7) son: 3, 4, 5, 6.",
          explicacion: "Los enteros mayores que 2 y menores que 7 son: 3, 4, 5, 6. Son 4 valores.",
        },
        {
          id: "5-6-6-e4",
          enunciado: "¿Qué diferencia hay entre x > 5 y x ≥ 5?",
          tipo: "texto",
          respuesta: "x > 5 excluye el 5 (solo mayores estrictos). x ≥ 5 incluye el 5.",
          pista: "El símbolo ≥ incluye la igualdad, el > no.",
          explicacion: "x > 5: valores como 6, 7, 8... pero NO el 5. x ≥ 5: valores como 5, 6, 7, 8... incluyendo el 5.",
        },
      ],
    },
    {
      id: "5-6-7",
      titulo: "Ecuaciones",
      objetivo: "Resolver ecuaciones de primer grado con una incógnita usando operaciones inversas.",
      concepto_clave: "Una ecuación es una igualdad con incógnita (x). Para resolverla, aplica la operación inversa en ambos lados hasta dejar x sola.",
      explicacion: [
        "Una ECUACIÓN es una igualdad que contiene una o más variables desconocidas (incógnitas). El objetivo es encontrar el valor de la incógnita que hace verdadera la igualdad.",
        "Principio clave: lo que haces en UN LADO de la ecuación debes hacerlo en el OTRO. La ecuación es como una balanza: si agregas o quitas algo a un lado, debes hacer lo mismo al otro para mantener el equilibrio.",
        "Para resolver: 1) Identifica la incógnita. 2) Aplica operaciones inversas (+ ↔ −, × ↔ ÷) para 'despejar' la incógnita. 3) Verifica sustituyendo el valor encontrado.",
      ],
      ejemplos: [
        {
          enunciado: "Resuelve: x + 7 = 15",
          pasos: [
            { texto: "Para despejar x, resto 7 a ambos lados" },
            { texto: "x + 7 − 7 = 15 − 7" },
            { texto: "x = 8" },
            { texto: "Verifico: 8 + 7 = 15 ✓" },
          ],
          resultado: "x = 8",
        },
        {
          enunciado: "Resuelve: 3x − 4 = 11",
          pasos: [
            { texto: "Sumo 4 a ambos lados: 3x = 15" },
            { texto: "Divido entre 3: x = 5" },
            { texto: "Verifico: 3(5) − 4 = 15 − 4 = 11 ✓" },
          ],
          resultado: "x = 5",
        },
      ],
      ejercicios: [
        {
          id: "5-6-7-e1",
          enunciado: "Resuelve: x − 9 = 4",
          tipo: "numero",
          respuesta: "13",
          pista: "Suma 9 a ambos lados.",
          explicacion: "x = 4 + 9 = 13. Verifica: 13 − 9 = 4 ✓",
        },
        {
          id: "5-6-7-e2",
          enunciado: "Resuelve: 4x = 28",
          tipo: "numero",
          respuesta: "7",
          pista: "Divide ambos lados entre 4.",
          explicacion: "x = 28 ÷ 4 = 7. Verifica: 4×7 = 28 ✓",
        },
        {
          id: "5-6-7-e3",
          enunciado: "Resuelve: 2x + 5 = 17",
          tipo: "numero",
          respuesta: "6",
          pista: "Primero resta 5 a ambos lados: 2x = 12. Luego divide entre 2.",
          explicacion: "2x = 17−5 = 12. x = 12÷2 = 6. Verifica: 2(6)+5 = 17 ✓",
        },
        {
          id: "5-6-7-e4",
          enunciado: "El doble de un número más 3 es igual a 15. ¿Cuál es el número?",
          tipo: "numero",
          respuesta: "6",
          pista: "Escribe la ecuación: 2x + 3 = 15. Luego resuélvela.",
          explicacion: "2x + 3 = 15 → 2x = 12 → x = 6. El número es 6.",
        },
      ],
    },
  ],
}

export default unidad6
