import type { Unidad } from "../tipos"

const unidad5: Unidad = {
  id: 5,
  nombre: "Estadística y probabilidad",
  descripcion: "Recolecta, organiza y analiza datos con gráficas, medidas estadísticas y probabilidad.",
  color: "teal",
  icono: "📊",
  lecciones: [
    {
      id: "5-5-1",
      titulo: "Variables estadísticas",
      objetivo: "Identificar variables estadísticas cualitativas y cuantitativas, y recolectar datos correctamente.",
      concepto_clave: "Variable cuantitativa: valores numéricos (edad, estatura). Variable cualitativa: atributos (color de ojos, sabor favorito).",
      explicacion: [
        "En estadística, una VARIABLE es la característica que medimos u observamos en cada individuo de un grupo. Por ejemplo, si estudiamos a los estudiantes de una clase, las variables podrían ser: edad, estatura, género, deporte favorito.",
        "Variables CUANTITATIVAS: tienen valores numéricos. Pueden ser DISCRETAS (se cuentan: número de hermanos, calificaciones) o CONTINUAS (se miden: estatura, temperatura, peso).",
        "Variables CUALITATIVAS: describen atributos sin valor numérico. Ejemplo: color de ojos, sabor favorito, grado académico.",
      ],
      ejemplos: [
        {
          enunciado: "Clasifica las variables: estatura, color de cabello, número de mascotas, ciudad de nacimiento",
          pasos: [
            { texto: "Estatura: valor numérico → cuantitativa continua" },
            { texto: "Color de cabello: atributo → cualitativa" },
            { texto: "Número de mascotas: valor numérico entero → cuantitativa discreta" },
            { texto: "Ciudad de nacimiento: atributo → cualitativa" },
          ],
          resultado: "Cuantitativas: estatura, número de mascotas. Cualitativas: color de cabello, ciudad de nacimiento.",
        },
      ],
      ejercicios: [
        {
          id: "5-5-1-e1",
          enunciado: "¿Es cuantitativa o cualitativa la variable 'temperatura diaria'?",
          tipo: "seleccion",
          opciones: ["Cuantitativa continua", "Cuantitativa discreta", "Cualitativa"],
          respuesta: "Cuantitativa continua",
          pista: "La temperatura se mide con un termómetro y puede tomar cualquier valor decimal.",
          explicacion: "La temperatura es un valor numérico que puede ser 22,5°C, 23,1°C... Se mide, no se cuenta → cuantitativa continua.",
        },
        {
          id: "5-5-1-e2",
          enunciado: "Encuestas a 20 estudiantes sobre su deporte favorito. ¿Cuál variable se está midiendo?",
          tipo: "seleccion",
          opciones: ["Cuantitativa discreta", "Cualitativa", "Cuantitativa continua"],
          respuesta: "Cualitativa",
          pista: "El deporte favorito es un nombre/atributo, no un número.",
          explicacion: "El deporte favorito (fútbol, natación, etc.) es un atributo, no un número. Es una variable cualitativa.",
        },
        {
          id: "5-5-1-e3",
          enunciado: "¿La variable 'número de libros leídos en el año' es discreta o continua?",
          tipo: "seleccion",
          opciones: ["Discreta", "Continua"],
          respuesta: "Discreta",
          pista: "¿Puedes leer 3,7 libros? ¿O solo números enteros?",
          explicacion: "No puedes leer 2,5 libros. Los libros se CUENTAN con números enteros → es discreta.",
        },
        {
          id: "5-5-1-e4",
          enunciado: "Antes de recolectar datos, ¿qué debes definir primero?",
          tipo: "seleccion",
          opciones: ["El color del gráfico", "La pregunta de investigación y la variable a medir", "Cuántos colores usar en la gráfica"],
          respuesta: "La pregunta de investigación y la variable a medir",
          pista: "Sin saber qué quieres investigar, ¿qué datos recolectarías?",
          explicacion: "Primero defines QUÉ quieres saber (la pregunta de investigación), luego QUÉ variable medir y cómo recolectar los datos.",
        },
      ],
    },
    {
      id: "5-5-2",
      titulo: "Diagramas de barras",
      objetivo: "Leer, interpretar y construir diagramas de barras verticales y horizontales.",
      concepto_clave: "En un diagrama de barras, la altura (o longitud) de cada barra representa la frecuencia de esa categoría.",
      explicacion: [
        "El DIAGRAMA DE BARRAS es uno de los gráficos más usados. Cada categoría tiene una barra cuya altura (o longitud, si es horizontal) representa cuántas veces aparece (frecuencia).",
        "Las barras deben tener el mismo ancho y deben estar separadas entre sí (a diferencia del histograma). Los ejes siempre deben tener etiquetas y la escala debe ser uniforme.",
        "Para construirlo: 1) Elige los ejes. 2) Define la escala del eje de frecuencias. 3) Dibuja una barra por categoría. 4) Agrega título y etiquetas.",
      ],
      ejemplos: [
        {
          enunciado: "En una clase, los deportes favoritos son: fútbol 12, natación 5, baloncesto 8, voleibol 3. ¿Cuál es el deporte menos preferido?",
          pasos: [
            { texto: "Busco la categoría con la barra más corta" },
            { texto: "Voleibol tiene frecuencia 3 (la menor)" },
          ],
          resultado: "El deporte menos preferido es el voleibol (3 estudiantes)",
        },
        {
          enunciado: "¿Cuántos estudiantes participaron en total en la encuesta anterior?",
          pasos: [
            { texto: "Suma todas las frecuencias: 12 + 5 + 8 + 3" },
          ],
          resultado: "12 + 5 + 8 + 3 = 28 estudiantes",
        },
      ],
      ejercicios: [
        {
          id: "5-5-2-e1",
          enunciado: "En una gráfica de barras, la categoría 'Rojo' tiene una barra de altura 15 y 'Azul' de altura 9. ¿Cuántos más eligieron Rojo que Azul?",
          tipo: "numero",
          respuesta: "6",
          pista: "Resta: 15 − 9.",
          explicacion: "15 − 9 = 6 personas más eligieron Rojo.",
        },
        {
          id: "5-5-2-e2",
          enunciado: "En un diagrama de barras, ¿qué representa la altura de cada barra?",
          tipo: "seleccion",
          opciones: ["El nombre de la categoría", "La frecuencia (cuántas veces aparece)", "El color de la barra"],
          respuesta: "La frecuencia (cuántas veces aparece)",
          pista: "El eje vertical generalmente muestra números.",
          explicacion: "La altura de la barra indica la frecuencia: cuántos datos corresponden a esa categoría.",
        },
        {
          id: "5-5-2-e3",
          enunciado: "Frutas favoritas: mango 10, guayaba 6, banano 8, papaya 4. ¿Qué porcentaje eligió mango?",
          tipo: "numero",
          respuesta: "36",
          pista: "Total = 10+6+8+4 = 28. Porcentaje de mango = (10÷28)×100.",
          explicacion: "(10÷28)×100 = 35,7% ≈ 36%.",
        },
        {
          id: "5-5-2-e4",
          enunciado: "¿Cuál es la diferencia entre diagrama de barras y pictograma?",
          tipo: "texto",
          respuesta: "En el diagrama de barras se usan barras rectangulares. En el pictograma se usan imágenes o símbolos para representar los datos.",
          pista: "Un pictograma usa dibujos simbólicos, el de barras usa formas geométricas.",
          explicacion: "Diagrama de barras: barras rectangulares cuya altura indica la frecuencia. Pictograma: imágenes o símbolos donde cada uno representa una cantidad fija.",
        },
      ],
    },
    {
      id: "5-5-3",
      titulo: "Diagramas de puntos y de líneas",
      objetivo: "Leer e interpretar diagramas de puntos y de líneas para analizar tendencias en el tiempo.",
      concepto_clave: "Diagrama de puntos: muestra distribución de valores. Diagrama de líneas: conecta puntos en el tiempo para mostrar tendencias (subida/bajada).",
      explicacion: [
        "El DIAGRAMA DE PUNTOS (o de dispersión) coloca un punto por cada dato en el eje, mostrando cómo se distribuyen los valores. Permite ver dónde se concentran los datos.",
        "El DIAGRAMA DE LÍNEAS conecta puntos con segmentos y es ideal para mostrar cómo cambia una variable en el TIEMPO. La pendiente de la línea indica si la variable sube, baja o se mantiene.",
        "Se usa en economía (evolución de precios), ciencias (temperatura mensual), deportes (puntos por partido). La tendencia general es el patrón de comportamiento a largo plazo.",
      ],
      ejemplos: [
        {
          enunciado: "La temperatura de Bogotá en una semana (°C): L=13, M=15, Mi=14, J=16, V=12, S=17, D=15. ¿En qué día fue más alta?",
          pasos: [
            { texto: "Busco el valor máximo: 17°C" },
            { texto: "Ocurrió el sábado" },
          ],
          resultado: "El sábado fue el día más cálido (17°C)",
        },
      ],
      ejercicios: [
        {
          id: "5-5-3-e1",
          enunciado: "Una línea que baja de izquierda a derecha indica una tendencia...",
          tipo: "seleccion",
          opciones: ["Creciente", "Decreciente", "Estable"],
          respuesta: "Decreciente",
          pista: "Si la línea baja, los valores son cada vez menores.",
          explicacion: "Una línea descendente (que baja) indica que los valores disminuyen con el tiempo → tendencia decreciente.",
        },
        {
          id: "5-5-3-e2",
          enunciado: "Las ventas mensuales (en miles): Ene=5, Feb=7, Mar=6, Abr=9, May=8. ¿En cuánto crecieron de Ene a Abr?",
          tipo: "numero",
          respuesta: "4",
          pista: "9 (Abr) − 5 (Ene) = ?",
          explicacion: "9 − 5 = 4 mil unidades de crecimiento.",
        },
        {
          id: "5-5-3-e3",
          enunciado: "¿Para qué tipo de datos es más apropiado el diagrama de líneas?",
          tipo: "seleccion",
          opciones: ["Categorías sin orden (deportes favoritos)", "Datos que cambian en el tiempo (temperatura mensual)", "Comparar grupos independientes"],
          respuesta: "Datos que cambian en el tiempo (temperatura mensual)",
          pista: "Las líneas conectan puntos en secuencia temporal.",
          explicacion: "El diagrama de líneas es ideal para datos temporales o secuenciales, mostrando la evolución o tendencia a lo largo del tiempo.",
        },
        {
          id: "5-5-3-e4",
          enunciado: "¿Cuál es el rango de los datos: 3, 7, 5, 9, 2, 8?",
          tipo: "numero",
          respuesta: "7",
          pista: "Rango = valor máximo − valor mínimo.",
          explicacion: "Máximo = 9, mínimo = 2. Rango = 9 − 2 = 7.",
        },
      ],
    },
    {
      id: "5-5-4",
      titulo: "Pictogramas",
      objetivo: "Leer e interpretar pictogramas, incluyendo el uso de medios símbolos.",
      concepto_clave: "En un pictograma cada símbolo o imagen representa una cantidad fija. Si el símbolo vale 4, medio símbolo vale 2.",
      explicacion: [
        "Un PICTOGRAMA usa imágenes o símbolos para representar datos. Es más visual y atractivo que una tabla, pero menos preciso.",
        "Cada símbolo representa una cantidad fija (llamada ESCALA o CLAVE). Por ejemplo, si cada 🍎 = 5 frutas, entonces 3 manzanas y media representan 3 × 5 + 2,5 = 17,5 frutas.",
        "Para leer un pictograma: 1) Lee la clave. 2) Cuenta los símbolos de cada categoría (incluyendo fracciones). 3) Multiplica por el valor de la clave.",
      ],
      ejemplos: [
        {
          enunciado: "Clave: ⭐ = 10 puntos. Equipo A tiene 3,5 estrellas. ¿Cuántos puntos tiene?",
          pasos: [
            { texto: "3 estrellas = 3 × 10 = 30 puntos" },
            { texto: "Media estrella = 5 puntos" },
            { texto: "Total = 30 + 5 = 35" },
          ],
          resultado: "El equipo A tiene 35 puntos",
        },
      ],
      ejercicios: [
        {
          id: "5-5-4-e1",
          enunciado: "Clave: 🌟 = 20 estudiantes. Una categoría tiene 2,5 estrellas. ¿Cuántos estudiantes son?",
          tipo: "numero",
          respuesta: "50",
          pista: "2 × 20 + 0,5 × 20 = 40 + 10.",
          explicacion: "2 × 20 = 40 y 0,5 × 20 = 10. Total = 50 estudiantes.",
        },
        {
          id: "5-5-4-e2",
          enunciado: "¿Cuál es la ventaja del pictograma sobre una tabla de datos?",
          tipo: "seleccion",
          opciones: ["Es más preciso", "Es más visual y fácil de entender rápidamente", "Muestra más información"],
          respuesta: "Es más visual y fácil de entender rápidamente",
          pista: "¿A qué tipo de lector le es más fácil un pictograma?",
          explicacion: "Los pictogramas son más atractivos y fáciles de leer de un vistazo, especialmente para niños. Son menos precisos que las tablas.",
        },
        {
          id: "5-5-4-e3",
          enunciado: "En un pictograma de libros leídos, clave=5 libros por 📚. Carlos tiene 4 símbolos y Sofía 3,5. ¿Quién leyó más y cuánto?",
          tipo: "texto",
          respuesta: "Carlos con 20 libros vs 17,5 de Sofía",
          pista: "Carlos: 4×5=20. Sofía: 3,5×5=17,5.",
          explicacion: "Carlos: 4 × 5 = 20 libros. Sofía: 3,5 × 5 = 17,5 libros. Carlos leyó más.",
        },
        {
          id: "5-5-4-e4",
          enunciado: "Si en un pictograma una categoría tiene 30 elementos y la clave es 6 por símbolo, ¿cuántos símbolos debe tener?",
          tipo: "numero",
          respuesta: "5",
          pista: "30 ÷ 6 = ?",
          explicacion: "30 ÷ 6 = 5 símbolos.",
        },
      ],
    },
    {
      id: "5-5-5",
      titulo: "Diagramas circulares",
      objetivo: "Leer e interpretar diagramas circulares y calcular el ángulo de cada sector.",
      concepto_clave: "El círculo completo = 360° = 100%. Cada sector: ángulo = porcentaje × 360° / 100 o porcentaje × 3,6°.",
      explicacion: [
        "El DIAGRAMA CIRCULAR (o de torta) muestra partes de un todo como sectores de un círculo. El círculo completo representa el 100% del total.",
        "Para construirlo: calcula el porcentaje de cada categoría, luego el ángulo de cada sector: ángulo = (frecuencia/total) × 360°.",
        "Son ideales cuando quieres ver qué parte del total representa cada categoría. No son buenos para comparar categorías entre sí (los diagramas de barras son mejores para eso).",
      ],
      ejemplos: [
        {
          enunciado: "En una encuesta: chocolate 40%, vainilla 35%, fresa 25%. ¿Cuántos grados ocupa el sector de chocolate?",
          pasos: [
            { texto: "Ángulo = porcentaje × 3,6°" },
            { texto: "Chocolate: 40 × 3,6 = 144°" },
          ],
          resultado: "El sector de chocolate ocupa 144°",
        },
        {
          enunciado: "Un sector ocupa 90° en el diagrama. ¿Qué porcentaje representa?",
          pasos: [
            { texto: "% = ángulo / 360° × 100" },
            { texto: "= 90/360 × 100 = 25%" },
          ],
          resultado: "El sector de 90° representa el 25%",
        },
      ],
      ejercicios: [
        {
          id: "5-5-5-e1",
          enunciado: "Un sector en un diagrama circular ocupa 72°. ¿Qué porcentaje representa?",
          tipo: "numero",
          respuesta: "20",
          pista: "72/360 × 100.",
          explicacion: "72/360 = 0,2. 0,2 × 100 = 20%.",
        },
        {
          id: "5-5-5-e2",
          enunciado: "En 200 estudiantes, 50 prefieren ciencias. ¿Cuántos grados ocupa su sector?",
          tipo: "numero",
          respuesta: "90",
          pista: "50/200 × 360 = 0,25 × 360.",
          explicacion: "50/200 = 0,25 = 25%. 25 × 3,6 = 90°.",
        },
        {
          id: "5-5-5-e3",
          enunciado: "Los sectores son: A=40%, B=35%, C=?. ¿Qué porcentaje corresponde a C?",
          tipo: "numero",
          respuesta: "25",
          pista: "A + B + C = 100%.",
          explicacion: "40 + 35 + C = 100. C = 25%.",
        },
        {
          id: "5-5-5-e4",
          enunciado: "¿Para qué tipo de análisis es mejor el diagrama circular?",
          tipo: "seleccion",
          opciones: ["Para comparar cambios en el tiempo", "Para ver qué parte del todo representa cada categoría", "Para mostrar datos continuos"],
          respuesta: "Para ver qué parte del todo representa cada categoría",
          pista: "El 'todo' está representado por el círculo completo (360° = 100%).",
          explicacion: "El diagrama circular es ideal para mostrar partes de un todo: cuánto del 100% le corresponde a cada categoría.",
        },
      ],
    },
    {
      id: "5-5-6",
      titulo: "Moda y mediana",
      objetivo: "Calcular la moda y la mediana de un conjunto de datos y entender cuándo usar cada una.",
      concepto_clave: "Moda: el valor que más se repite. Mediana: el valor del centro al ordenar los datos (si son pares: promedio de los dos del centro).",
      explicacion: [
        "La MODA es el dato que aparece con mayor frecuencia en un conjunto. Puede haber cero modas (todos son diferentes), una moda, o varias modas (bimodal, trimodal...).",
        "La MEDIANA es el valor central al ordenar los datos de menor a mayor. Si hay un número impar de datos, es el dato del medio. Si hay un número par, es el promedio de los dos datos centrales.",
        "¿Cuándo usar cada una? La moda: para datos cualitativos o para saber el valor 'más popular'. La mediana: cuando hay valores extremos muy altos o bajos que distorsionan el promedio.",
      ],
      ejemplos: [
        {
          enunciado: "Datos: 5, 3, 8, 3, 7, 3, 9. Halla la moda y la mediana.",
          pasos: [
            { texto: "Moda: el 3 aparece 3 veces → moda = 3" },
            { texto: "Ordeno: 3, 3, 3, 5, 7, 8, 9 (7 datos)" },
            { texto: "El dato central es el 4° → mediana = 5" },
          ],
          resultado: "Moda = 3 y Mediana = 5",
        },
        {
          enunciado: "Datos: 4, 7, 2, 8 (número par de datos). Halla la mediana.",
          pasos: [
            { texto: "Ordeno: 2, 4, 7, 8" },
            { texto: "Los dos del centro son 4 y 7" },
            { texto: "Mediana = (4 + 7) / 2 = 5,5" },
          ],
          resultado: "Mediana = 5,5",
        },
      ],
      ejercicios: [
        {
          id: "5-5-6-e1",
          enunciado: "Halla la moda de: 2, 5, 3, 5, 7, 5, 1, 2",
          tipo: "numero",
          respuesta: "5",
          pista: "Cuenta cuántas veces aparece cada número. ¿Cuál se repite más?",
          explicacion: "El 5 aparece 3 veces (y el 2 aparece 2 veces). La moda es 5.",
        },
        {
          id: "5-5-6-e2",
          enunciado: "Halla la mediana de: 1, 4, 6, 8, 10",
          tipo: "numero",
          respuesta: "6",
          pista: "5 datos, el central es el 3° al estar ordenados.",
          explicacion: "Ya están ordenados: 1, 4, 6, 8, 10. El dato central (3°) es 6.",
        },
        {
          id: "5-5-6-e3",
          enunciado: "Halla la mediana de: 3, 7, 5, 9",
          tipo: "texto",
          respuesta: "6",
          pista: "Ordena: 3, 5, 7, 9. Dos datos centrales: 5 y 7.",
          explicacion: "Ordenados: 3, 5, 7, 9. Mediana = (5 + 7) / 2 = 6.",
        },
        {
          id: "5-5-6-e4",
          enunciado: "Un conjunto tiene datos: 10, 10, 10, 10, 100. ¿Cuál es más representativo, la moda o la mediana?",
          tipo: "seleccion",
          opciones: ["La moda (10) porque aparece 4 veces y la mediana sería 10 también", "La mediana, ya que no se ve afectada por el valor extremo 100", "Son igualmente representativos"],
          respuesta: "La mediana, ya que no se ve afectada por el valor extremo 100",
          pista: "¿Qué pasa con el promedio cuando hay un valor muy diferente a los demás?",
          explicacion: "La mediana = 10 y no cambia aunque el 100 sea muy grande. El promedio sería 28 (distorsionado por el 100). La mediana es más robusta ante valores extremos.",
        },
      ],
    },
    {
      id: "5-5-7",
      titulo: "Media (promedio)",
      objetivo: "Calcular la media aritmética y entender su significado como medida de centro.",
      concepto_clave: "Media = suma de todos los datos ÷ cantidad de datos. Representa el 'reparto equitativo' de los valores.",
      explicacion: [
        "La MEDIA ARITMÉTICA (o promedio) se calcula sumando todos los datos y dividiendo entre la cantidad de datos. Representa el valor 'central' imaginando que todos tuvieran el mismo valor.",
        "Interpretación: si 5 amigos tienen respectivamente 3, 5, 4, 7 y 6 canicas, la media es (3+5+4+7+6)/5 = 25/5 = 5. Si distribuyeran las canicas equitativamente, cada uno tendría 5.",
        "Limitación: la media se ve afectada por valores extremos. Si uno de los amigos tiene 100 canicas, la media sube mucho aunque nadie realmente tenga cerca de ese valor.",
      ],
      ejemplos: [
        {
          enunciado: "Califica de 5 exámenes: 7, 8, 6, 9, 5. ¿Cuál es la media?",
          pasos: [
            { texto: "Suma: 7 + 8 + 6 + 9 + 5 = 35" },
            { texto: "Cantidad de datos: 5" },
            { texto: "Media = 35 ÷ 5 = 7" },
          ],
          resultado: "La media de las calificaciones es 7",
        },
        {
          enunciado: "La media de 4 números es 8. ¿Cuánto suman todos?",
          pasos: [
            { texto: "Media = suma ÷ cantidad → suma = media × cantidad" },
            { texto: "Suma = 8 × 4 = 32" },
          ],
          resultado: "La suma de los 4 números es 32",
        },
      ],
      ejercicios: [
        {
          id: "5-5-7-e1",
          enunciado: "Halla la media de: 4, 6, 8, 10, 12",
          tipo: "numero",
          respuesta: "8",
          pista: "Suma todos y divide entre 5.",
          explicacion: "(4+6+8+10+12) / 5 = 40/5 = 8.",
        },
        {
          id: "5-5-7-e2",
          enunciado: "En 3 días un niño estudió 2, 3 y 4 horas. ¿Cuál es la media diaria?",
          tipo: "numero",
          respuesta: "3",
          pista: "(2+3+4) ÷ 3.",
          explicacion: "(2+3+4) / 3 = 9/3 = 3 horas por día.",
        },
        {
          id: "5-5-7-e3",
          enunciado: "La media de 3 datos es 10. Dos de los datos son 8 y 12. ¿Cuánto vale el tercer dato?",
          tipo: "numero",
          respuesta: "10",
          pista: "Suma = 10 × 3 = 30. 8 + 12 + x = 30.",
          explicacion: "Suma total = 10 × 3 = 30. 8 + 12 + x = 30. 20 + x = 30. x = 10.",
        },
        {
          id: "5-5-7-e4",
          enunciado: "¿Puede la media ser mayor que todos los datos del conjunto?",
          tipo: "seleccion",
          opciones: ["Sí, si hay muchos datos", "No, la media siempre está entre el mínimo y el máximo"],
          respuesta: "No, la media siempre está entre el mínimo y el máximo",
          pista: "Piénsalo: si divides la suma de todos los datos entre su cantidad, ¿puede ser mayor que el mayor dato?",
          explicacion: "La media aritmética siempre es mayor o igual que el valor mínimo y menor o igual que el máximo del conjunto.",
        },
      ],
    },
    {
      id: "5-5-8",
      titulo: "Probabilidad de un evento",
      objetivo: "Calcular la probabilidad de eventos simples y usar la escala de probabilidad 0 a 1.",
      concepto_clave: "P(evento) = casos favorables ÷ casos posibles totales. Va de 0 (imposible) a 1 (seguro).",
      explicacion: [
        "La PROBABILIDAD mide qué tan probable es que ocurra un evento. Se expresa como un número entre 0 y 1 (o entre 0% y 100%). P=0 significa imposible, P=1 significa que ocurrirá con certeza.",
        "Para calcular la probabilidad de un evento: P(A) = número de casos favorables / número de casos posibles totales.",
        "Ejemplo: al lanzar un dado justo, la probabilidad de obtener 4 es P(4) = 1/6 (1 caso favorable, 6 posibles). La probabilidad de obtener un número par es P(par) = 3/6 = 1/2 (pares: 2, 4, 6).",
      ],
      ejemplos: [
        {
          enunciado: "En una bolsa hay 5 bolas rojas, 3 azules y 2 verdes. ¿Cuál es la probabilidad de sacar una azul?",
          pasos: [
            { texto: "Casos favorables: 3 (bolas azules)" },
            { texto: "Casos posibles: 5 + 3 + 2 = 10" },
            { texto: "P(azul) = 3/10 = 0,3" },
          ],
          resultado: "P(azul) = 3/10 = 30%",
        },
        {
          enunciado: "Al lanzar un dado, ¿cuál es la probabilidad de obtener un número mayor que 4?",
          pasos: [
            { texto: "Casos favorables: 5 y 6 → 2 casos" },
            { texto: "Casos posibles: 1,2,3,4,5,6 → 6 casos" },
            { texto: "P(>4) = 2/6 = 1/3" },
          ],
          resultado: "P(>4) = 1/3 ≈ 33%",
        },
      ],
      ejercicios: [
        {
          id: "5-5-8-e1",
          enunciado: "Al lanzar una moneda, ¿cuál es la probabilidad de obtener cara?",
          tipo: "texto",
          respuesta: "1/2",
          pista: "1 cara favorable, 2 posibles (cara o sello).",
          explicacion: "P(cara) = 1/2 = 0,5 = 50%.",
        },
        {
          id: "5-5-8-e2",
          enunciado: "Un dado tiene 6 caras. ¿Cuál es la probabilidad de obtener un número impar?",
          tipo: "texto",
          respuesta: "1/2",
          pista: "Impares en un dado: 1, 3, 5 (3 casos).",
          explicacion: "P(impar) = 3/6 = 1/2. Hay 3 números impares (1,3,5) de 6 posibles.",
        },
        {
          id: "5-5-8-e3",
          enunciado: "En una clase hay 12 niñas y 18 niños. Se elige un estudiante al azar. ¿Cuál es la probabilidad de que sea niña?",
          tipo: "texto",
          respuesta: "2/5",
          pista: "Total estudiantes = 12+18=30. P(niña) = 12/30.",
          explicacion: "12/30 = 2/5. La probabilidad de elegir una niña es 2/5 = 40%.",
        },
        {
          id: "5-5-8-e4",
          enunciado: "¿Qué significa que un evento tenga probabilidad 0?",
          tipo: "seleccion",
          opciones: ["Es muy poco probable", "Es imposible que ocurra", "Ocurre con certeza"],
          respuesta: "Es imposible que ocurra",
          pista: "P=0 está en el extremo de la escala de probabilidades.",
          explicacion: "Probabilidad 0 significa que el evento es IMPOSIBLE. Por ejemplo, sacar un 7 de un dado de 6 caras tiene probabilidad 0.",
        },
      ],
    },
  ],
}

export default unidad5
