import type { Unidad } from "../tipos"

const unidad1: Unidad = {
  id: 1,
  nombre: "Teoría de números y fracciones",
  descripcion: "Domina potencias, raíces, fracciones como razón y porcentaje, y opera con fracciones con soltura.",
  color: "blue",
  icono: "🔢",
  lecciones: [
    {
      id: "5-1-1",
      titulo: "Descomposición de números",
      objetivo: "Descomponer números naturales grandes usando valor posicional y factores primos.",
      concepto_clave: "Descomponer un número es escribirlo como suma de sus valores posicionales o como producto de factores primos.",
      explicacion: [
        "Descomponer un número significa escribirlo de distintas formas. La descomposición POSICIONAL expresa el número según cada cifra y su valor: 45.320 = 40.000 + 5.000 + 300 + 20.",
        "La descomposición en FACTORES PRIMOS divide el número entre primos hasta obtener 1: 60 = 2 × 2 × 3 × 5 = 2² × 3 × 5. Es única para cada número.",
        "¿Para qué sirve? La descomposición posicional nos ayuda a entender el valor real de cada cifra. La factorial es clave para calcular MCM, MCD y simplificar fracciones.",
      ],
      ejemplos: [
        {
          enunciado: "Descompón 84.506 posicionalmente",
          pasos: [
            { texto: "8 está en decenas de millar: 80.000" },
            { texto: "4 está en unidades de millar: 4.000" },
            { texto: "5 está en centenas: 500" },
            { texto: "0 en decenas: 0" },
            { texto: "6 en unidades: 6" },
          ],
          resultado: "84.506 = 80.000 + 4.000 + 500 + 6",
        },
        {
          enunciado: "Descompón 90 en factores primos",
          pasos: [
            { texto: "90 ÷ 2 = 45" },
            { texto: "45 ÷ 3 = 15" },
            { texto: "15 ÷ 3 = 5" },
            { texto: "5 es primo → fin" },
          ],
          resultado: "90 = 2 × 3² × 5",
        },
      ],
      ejercicios: [
        {
          id: "5-1-1-e1",
          enunciado: "¿Cuánto vale el dígito 7 en el número 273.840?",
          tipo: "numero",
          respuesta: "70000",
          pista: "Cuenta desde la derecha: unidades, decenas, centenas, miles, decenas de miles...",
          explicacion: "El 7 ocupa el lugar de las decenas de millar. Su valor es 7 × 10.000 = 70.000.",
        },
        {
          id: "5-1-1-e2",
          enunciado: "Descompón 36 en factores primos",
          tipo: "texto",
          respuesta: "2²×3²",
          pista: "36 ÷ 2 = 18, luego 18 ÷ 2 = 9, luego 9 ÷ 3 = ?",
          explicacion: "36 = 2 × 18 = 2 × 2 × 9 = 2 × 2 × 3 × 3 = 2² × 3².",
        },
        {
          id: "5-1-1-e3",
          enunciado: "¿Qué número corresponde a: 500.000 + 30.000 + 400 + 5?",
          tipo: "numero",
          respuesta: "530405",
          pista: "Suma cada valor posicional.",
          explicacion: "500.000 + 30.000 + 400 + 5 = 530.405.",
        },
        {
          id: "5-1-1-e4",
          enunciado: "¿Cuántos factores primos (contando repetidos) tiene el número 12?",
          tipo: "numero",
          respuesta: "3",
          pista: "12 = 2 × 2 × 3. Cuenta todos los factores incluyendo los repetidos.",
          explicacion: "12 = 2 × 2 × 3. Son 3 factores primos en total (dos doses y un tres).",
        },
      ],
    },
    {
      id: "5-1-2",
      titulo: "Redondeo y estimación de operaciones",
      objetivo: "Redondear números naturales y usar la estimación para verificar resultados.",
      concepto_clave: "Redondear: si el dígito siguiente ≥ 5, sube el dígito. Si < 5, queda igual. La estimación nos da una idea rápida del resultado.",
      explicacion: [
        "REDONDEAR es aproximar un número al valor más cercano en una posición determinada. Miras el dígito a la derecha de donde vas a redondear: si es 5 o más, subes 1; si es 4 o menos, dejas igual.",
        "La ESTIMACIÓN usa números redondeados para calcular rápidamente si un resultado parece correcto. Es como una 'comprobación rápida' antes de hacer la operación exacta.",
        "Ejemplo de uso real: antes de comprar en una tienda puedes estimar si tienes suficiente dinero. 4.850 + 3.120 ≈ 5.000 + 3.000 = 8.000. Ya sabes que necesitas aproximadamente $8.000.",
      ],
      ejemplos: [
        {
          enunciado: "Redondea 47.836 a la centena más cercana",
          pasos: [
            { texto: "La posición de las centenas tiene un 8" },
            { texto: "Miro el dígito a su derecha: 3" },
            { texto: "3 < 5 → la centena queda igual" },
            { texto: "Las posiciones menores se vuelven ceros" },
          ],
          resultado: "47.836 ≈ 47.800",
        },
        {
          enunciado: "Estima: 6.782 × 4",
          pasos: [
            { texto: "Redondeo 6.782 ≈ 7.000" },
            { texto: "7.000 × 4 = 28.000" },
          ],
          resultado: "6.782 × 4 ≈ 28.000 (resultado exacto: 27.128)",
        },
      ],
      ejercicios: [
        {
          id: "5-1-2-e1",
          enunciado: "Redondea 63.582 a la unidad de millar más cercana",
          tipo: "numero",
          respuesta: "64000",
          pista: "La posición de los miles tiene 3. Mira el dígito siguiente: 5.",
          explicacion: "El dígito siguiente al millar es 5 (5 ≥ 5), por lo tanto el 3 sube a 4. 63.582 ≈ 64.000.",
        },
        {
          id: "5-1-2-e2",
          enunciado: "Estima la suma: 3.847 + 5.123",
          tipo: "numero",
          respuesta: "9000",
          pista: "Redondea cada número a la unidad de millar: 3.847 ≈ 4.000 y 5.123 ≈ 5.000.",
          explicacion: "3.847 ≈ 4.000 y 5.123 ≈ 5.000. Estimación: 4.000 + 5.000 = 9.000.",
        },
        {
          id: "5-1-2-e3",
          enunciado: "¿Cuál de estas respuestas parece correcta para 298 × 3?",
          tipo: "seleccion",
          opciones: ["Aproximadamente 900", "Aproximadamente 6.000", "Aproximadamente 300"],
          respuesta: "Aproximadamente 900",
          pista: "298 ≈ 300. ¿Cuánto es 300 × 3?",
          explicacion: "298 ≈ 300. 300 × 3 = 900. El resultado exacto es 894, muy cercano a 900.",
        },
        {
          id: "5-1-2-e4",
          enunciado: "Redondea 9.950 a la centena más cercana",
          tipo: "numero",
          respuesta: "10000",
          pista: "La centena es 9 y el siguiente dígito es 5. ¿Qué pasa cuando el 9 sube?",
          explicacion: "9 + 1 = 10, lo que genera un acarreo: 9.950 ≈ 10.000.",
        },
      ],
    },
    {
      id: "5-1-3",
      titulo: "Operaciones combinadas",
      objetivo: "Resolver correctamente expresiones con múltiples operaciones usando el orden correcto.",
      concepto_clave: "Orden de operaciones: 1° paréntesis, 2° potencias/raíces, 3° multiplicación/división (izq. a der.), 4° suma/resta (izq. a der.).",
      explicacion: [
        "Cuando hay varias operaciones en una misma expresión, NO se resuelven de izquierda a derecha. Hay un orden establecido: paréntesis primero, luego potencias y raíces, después multiplicaciones y divisiones, y al final sumas y restas.",
        "La regla se recuerda con la sigla PEMDAS o PAPOMUDAS: Paréntesis, Potencias, Multiplicación, División, Adición, Sustracción.",
        "Si hay operaciones del mismo nivel (ejemplo: una multiplicación y una división), se resuelven de izquierda a derecha. Lo mismo con sumas y restas entre sí.",
      ],
      ejemplos: [
        {
          enunciado: "Resuelve: 5 + 3 × 4 − 2",
          pasos: [
            { texto: "Primero la multiplicación: 3 × 4 = 12" },
            { texto: "Ahora: 5 + 12 − 2" },
            { texto: "De izquierda a derecha: 5 + 12 = 17" },
            { texto: "17 − 2 = 15" },
          ],
          resultado: "5 + 3 × 4 − 2 = 15",
        },
        {
          enunciado: "Resuelve: (8 + 2) × 3 − 4 ÷ 2",
          pasos: [
            { texto: "Paréntesis: 8 + 2 = 10" },
            { texto: "10 × 3 = 30 y 4 ÷ 2 = 2 (mismo nivel, izq. a der.)" },
            { texto: "30 − 2 = 28" },
          ],
          resultado: "(8 + 2) × 3 − 4 ÷ 2 = 28",
        },
      ],
      ejercicios: [
        {
          id: "5-1-3-e1",
          enunciado: "¿Cuánto es 20 − 4 × 3 + 5?",
          tipo: "numero",
          respuesta: "13",
          pista: "Primero la multiplicación: 4 × 3 = 12. Luego 20 − 12 + 5.",
          explicacion: "4 × 3 = 12. Luego 20 − 12 = 8. Luego 8 + 5 = 13.",
        },
        {
          id: "5-1-3-e2",
          enunciado: "¿Cuánto es (15 − 5) × 2 + 8 ÷ 4?",
          tipo: "numero",
          respuesta: "22",
          pista: "Paréntesis primero: (15−5)=10. Luego 10×2=20 y 8÷4=2. Finalmente 20+2.",
          explicacion: "Paréntesis: 15−5=10. Mult: 10×2=20. Div: 8÷4=2. Suma: 20+2=22.",
        },
        {
          id: "5-1-3-e3",
          enunciado: "Un estudiante calculó 3 + 4 × 2 = 14. ¿Está correcto?",
          tipo: "seleccion",
          opciones: ["Sí, 3+4=7 y 7×2=14", "No, debe hacer 4×2=8 primero, resultado es 11"],
          respuesta: "No, debe hacer 4×2=8 primero, resultado es 11",
          pista: "¿Qué operación va primero: suma o multiplicación?",
          explicacion: "La multiplicación va antes que la suma. 4×2=8 primero, luego 3+8=11.",
        },
        {
          id: "5-1-3-e4",
          enunciado: "Resuelve: 100 ÷ (2 + 3) × 4",
          tipo: "numero",
          respuesta: "80",
          pista: "Paréntesis: 2+3=5. Luego 100÷5=20. Luego 20×4.",
          explicacion: "2+3=5. 100÷5=20. 20×4=80.",
        },
      ],
    },
    {
      id: "5-1-4",
      titulo: "Potenciación y radicación de números naturales",
      objetivo: "Calcular potencias y raíces cuadradas de números naturales y aplicarlas en problemas.",
      concepto_clave: "Potencia: aⁿ = a×a×...×a (n veces). Raíz cuadrada: √a = el número que al cuadrado da a.",
      explicacion: [
        "La POTENCIACIÓN es una multiplicación repetida. 3⁴ = 3 × 3 × 3 × 3 = 81. La base es el número que se multiplica y el exponente dice cuántas veces.",
        "Casos especiales: cualquier número elevado a 0 = 1 (ej: 5⁰ = 1). Cualquier número elevado a 1 = sí mismo (ej: 7¹ = 7).",
        "La RADICACIÓN es la operación inversa: √25 = 5 porque 5² = 25. La raíz cuadrada de un número es el valor que multiplicado por sí mismo da ese número. No todos los números tienen raíz exacta (√2, √3... son decimales infinitos).",
      ],
      ejemplos: [
        {
          enunciado: "Calcula 2⁵",
          pasos: [
            { texto: "2⁵ = 2 × 2 × 2 × 2 × 2" },
            { texto: "= 4 × 2 × 2 × 2 = 8 × 2 × 2 = 16 × 2" },
          ],
          resultado: "2⁵ = 32",
        },
        {
          enunciado: "¿Cuánto es √144?",
          pasos: [
            { texto: "Busco un número que al cuadrado dé 144" },
            { texto: "¿12 × 12 = 144? → 12 × 12 = 144 ✓" },
          ],
          resultado: "√144 = 12",
        },
      ],
      ejercicios: [
        {
          id: "5-1-4-e1",
          enunciado: "¿Cuánto es 4³?",
          tipo: "numero",
          respuesta: "64",
          pista: "4³ = 4 × 4 × 4. Primero 4×4=16, luego 16×4.",
          explicacion: "4³ = 4 × 4 × 4 = 16 × 4 = 64.",
        },
        {
          id: "5-1-4-e2",
          enunciado: "¿Cuánto es √81?",
          tipo: "numero",
          respuesta: "9",
          pista: "¿Qué número multiplicado por sí mismo da 81?",
          explicacion: "9 × 9 = 81, entonces √81 = 9.",
        },
        {
          id: "5-1-4-e3",
          enunciado: "¿Cuánto mide el lado de un cuadrado cuya área es 49 cm²?",
          tipo: "numero",
          respuesta: "7",
          pista: "Área = lado². Si el área es 49, el lado = √49.",
          explicacion: "Lado = √49 = 7 cm. Verificación: 7² = 49 ✓",
        },
        {
          id: "5-1-4-e4",
          enunciado: "¿Cuál es mayor: 3⁴ o 4³?",
          tipo: "seleccion",
          opciones: ["3⁴ es mayor", "4³ es mayor", "Son iguales"],
          respuesta: "3⁴ es mayor",
          pista: "Calcula cada uno: 3⁴=3×3×3×3 y 4³=4×4×4.",
          explicacion: "3⁴ = 81 y 4³ = 64. Como 81 > 64, entonces 3⁴ es mayor.",
        },
      ],
    },
    {
      id: "5-1-5",
      titulo: "Números primos y compuestos",
      objetivo: "Clasificar números naturales en primos y compuestos, y usar la criba de Eratóstenes.",
      concepto_clave: "Primo: exactamente 2 divisores (1 y él mismo). Compuesto: más de 2 divisores. El 1 no es primo ni compuesto.",
      explicacion: [
        "Un número PRIMO solo tiene exactamente dos divisores: 1 y él mismo. Los primeros primos son 2, 3, 5, 7, 11, 13, 17, 19, 23, 29... El 2 es el único primo par.",
        "Un número COMPUESTO tiene más divisores. Puede expresarse como producto de factores primos. Por ejemplo, 12 = 2² × 3.",
        "La CRIBA DE ERATÓSTENES es un método para encontrar todos los primos hasta un número: escribes todos los números, marcas el 1 (no es primo), luego vas tachando todos los múltiplos de 2, de 3, de 5... Los que quedan sin tachar son primos.",
      ],
      ejemplos: [
        {
          enunciado: "¿Es primo el número 37?",
          pasos: [
            { texto: "Pruebo divisores hasta √37 ≈ 6,08" },
            { texto: "37 ÷ 2 = 18,5 (no exacto)" },
            { texto: "37 ÷ 3 = 12,3 (no exacto)" },
            { texto: "37 ÷ 5 = 7,4 (no exacto)" },
            { texto: "No hay más divisores posibles menores que √37" },
          ],
          resultado: "37 es PRIMO",
        },
        {
          enunciado: "¿Por qué 51 NO es primo?",
          pasos: [
            { texto: "51 ÷ 3 = 17 (exacto!)" },
            { texto: "Entonces 51 = 3 × 17" },
          ],
          resultado: "51 es COMPUESTO (divisible entre 3 y 17)",
        },
      ],
      ejercicios: [
        {
          id: "5-1-5-e1",
          enunciado: "¿Cuántos números primos hay entre 20 y 30?",
          tipo: "numero",
          respuesta: "2",
          pista: "Verifica: 21=3×7, 22=2×11, 23=?, 24=2³×3, 25=5², 26=2×13, 27=3³, 28=2²×7, 29=?",
          explicacion: "Los primos entre 20 y 30 son 23 y 29. Son 2 en total.",
        },
        {
          id: "5-1-5-e2",
          enunciado: "¿Es primo el 91?",
          tipo: "seleccion",
          opciones: ["Sí, es primo", "No, es compuesto"],
          respuesta: "No, es compuesto",
          pista: "Prueba dividir 91 entre 7.",
          explicacion: "91 ÷ 7 = 13. Entonces 91 = 7 × 13. Es un número compuesto.",
        },
        {
          id: "5-1-5-e3",
          enunciado: "¿Cuál es el número primo más pequeño mayor que 10?",
          tipo: "numero",
          respuesta: "11",
          pista: "Verifica 11: ¿es divisible entre 2? ¿entre 3?",
          explicacion: "11 no es divisible entre 2 ni entre 3 (√11 ≈ 3.3, solo hay que probar hasta 3). 11 es primo.",
        },
        {
          id: "5-1-5-e4",
          enunciado: "Todo número par mayor que 2 es compuesto. ¿Por qué?",
          tipo: "texto",
          respuesta: "Porque es divisible entre 2, por lo que tiene al menos 3 divisores: 1, 2 y el número mismo",
          pista: "¿Qué tienen en común todos los números pares?",
          explicacion: "Todo número par mayor que 2 es divisible entre 2 y entre 1 y entre sí mismo, teniendo al menos 3 divisores → compuesto.",
        },
      ],
    },
    {
      id: "5-1-6",
      titulo: "Mínimo común múltiplo y máximo común divisor",
      objetivo: "Calcular el MCM y MCD usando factores primos y aplicarlos a problemas reales.",
      concepto_clave: "MCM(a,b): producto de todos los factores primos con el mayor exponente. MCD(a,b): producto de los factores comunes con el menor exponente.",
      explicacion: [
        "Con la DESCOMPOSICIÓN EN FACTORES PRIMOS podemos calcular MCM y MCD de forma sistemática. Descomponemos ambos números, luego aplicamos las reglas.",
        "Para el MCD: tomamos solo los factores primos que AMBOS números tienen en común, y usamos el exponente MENOR. Ejemplo: 12=2²×3 y 18=2×3². MCD = 2¹×3¹ = 6.",
        "Para el MCM: tomamos TODOS los factores primos (de cualquiera de los dos), y usamos el exponente MAYOR. Con el mismo ejemplo: MCM = 2²×3² = 36.",
      ],
      ejemplos: [
        {
          enunciado: "Halla el MCD y MCM de 24 y 36",
          pasos: [
            { texto: "24 = 2³ × 3" },
            { texto: "36 = 2² × 3²" },
            { texto: "MCD: factores comunes con exp. menor → 2² × 3 = 4 × 3 = 12" },
            { texto: "MCM: todos los factores con exp. mayor → 2³ × 3² = 8 × 9 = 72" },
          ],
          resultado: "MCD(24, 36) = 12 y MCM(24, 36) = 72",
        },
        {
          enunciado: "Dos buses salen juntos cada 15 y 20 minutos. ¿Cada cuánto coinciden?",
          pasos: [
            { texto: "15 = 3 × 5 y 20 = 2² × 5" },
            { texto: "MCM = 2² × 3 × 5 = 4 × 3 × 5 = 60" },
          ],
          resultado: "Coinciden cada 60 minutos (1 hora)",
        },
      ],
      ejercicios: [
        {
          id: "5-1-6-e1",
          enunciado: "Halla el MCD(16, 24)",
          tipo: "numero",
          respuesta: "8",
          pista: "16=2⁴, 24=2³×3. Los factores comunes son solo las potencias de 2. Toma la menor.",
          explicacion: "16=2⁴ y 24=2³×3. Factor común: 2³=8. MCD(16,24)=8.",
        },
        {
          id: "5-1-6-e2",
          enunciado: "Halla el MCM(6, 10)",
          tipo: "numero",
          respuesta: "30",
          pista: "6=2×3 y 10=2×5. MCM usa todos los factores con mayor exponente.",
          explicacion: "6=2×3 y 10=2×5. MCM = 2×3×5 = 30.",
        },
        {
          id: "5-1-6-e3",
          enunciado: "Tengo 48 mangos y 36 guanábanas para hacer cestas iguales con la mayor cantidad posible. ¿Cuántas cestas puedo hacer?",
          tipo: "numero",
          respuesta: "12",
          pista: "Necesitas el MCD(48, 36) para saber el máximo número de cestas iguales.",
          explicacion: "48=2⁴×3 y 36=2²×3². MCD=2²×3=12. Puedo hacer 12 cestas con 4 mangos y 3 guanábanas cada una.",
        },
        {
          id: "5-1-6-e4",
          enunciado: "¿Cuánto es MCD(a,b) × MCM(a,b) para a=4 y b=6?",
          tipo: "numero",
          respuesta: "24",
          pista: "Hay una propiedad: MCD × MCM = a × b. Compruébala.",
          explicacion: "MCD(4,6)=2 y MCM(4,6)=12. 2×12=24. Verifica: 4×6=24 ✓. Propiedad: MCD×MCM = a×b.",
        },
      ],
    },
    {
      id: "5-1-7",
      titulo: "Fracción como medida",
      objetivo: "Usar fracciones para expresar medidas y cantidades que no son números enteros.",
      concepto_clave: "La fracción como medida expresa partes de una unidad de medida: 3/4 de metro = 75 cm.",
      explicacion: [
        "Cuando medimos longitudes, masas o tiempos, frecuentemente obtenemos valores que no son números enteros. Las fracciones nos permiten expresarlos exactamente: una tela que mide 2 y 3/4 metros, un tiempo de 1 y 1/2 horas.",
        "Para usar fracciones como medida es útil saber las equivalencias: 1/2 metro = 50 cm, 1/4 metro = 25 cm, 3/4 metro = 75 cm, 1/10 kg = 100 g.",
        "También podemos representar medidas en la recta numérica: dividimos la unidad en tantas partes iguales como indica el denominador y contamos los numeradores.",
      ],
      ejemplos: [
        {
          enunciado: "Un tablón mide 5/4 de metro. ¿Cuántos centímetros mide?",
          pasos: [
            { texto: "1 metro = 100 cm" },
            { texto: "5/4 de metro = (5/4) × 100 cm" },
            { texto: "= 500/4 = 125 cm" },
          ],
          resultado: "5/4 de metro = 125 cm = 1 metro y 25 cm",
        },
        {
          enunciado: "¿Qué fracción de metro es 60 cm?",
          pasos: [
            { texto: "60 cm de 100 cm (un metro)" },
            { texto: "60/100 = 3/5 (simplificando ÷20)" },
          ],
          resultado: "60 cm = 3/5 de metro",
        },
      ],
      ejercicios: [
        {
          id: "5-1-7-e1",
          enunciado: "¿Cuántos centímetros son 3/4 de metro?",
          tipo: "numero",
          respuesta: "75",
          pista: "1 metro = 100 cm. Halla 3/4 de 100.",
          explicacion: "3/4 de 100 = 300/4 = 75 cm.",
        },
        {
          id: "5-1-7-e2",
          enunciado: "¿Qué fracción de un kilogramo es 250 gramos?",
          tipo: "texto",
          respuesta: "1/4",
          pista: "1 kg = 1000 g. 250/1000 simplificado.",
          explicacion: "250/1000 = 25/100 = 1/4. 250 g es la cuarta parte de un kilogramo.",
        },
        {
          id: "5-1-7-e3",
          enunciado: "Una caminata dura 3/2 horas. ¿Cuántos minutos son?",
          tipo: "numero",
          respuesta: "90",
          pista: "1 hora = 60 minutos. 3/2 × 60.",
          explicacion: "3/2 × 60 = 180/2 = 90 minutos = 1 hora y media.",
        },
        {
          id: "5-1-7-e4",
          enunciado: "Ordena de menor a mayor: 2/3 m, 5/6 m, 1/2 m",
          tipo: "texto",
          respuesta: "1/2, 2/3, 5/6",
          pista: "Convierte a centímetros: 2/3=66,7cm, 5/6=83,3cm, 1/2=50cm.",
          explicacion: "1/2=50cm, 2/3≈66,7cm, 5/6≈83,3cm. Orden: 1/2 < 2/3 < 5/6.",
        },
      ],
    },
    {
      id: "5-1-8",
      titulo: "Fracción como parte-todo y como operador",
      objetivo: "Interpretar fracciones como parte de un entero y como operador que transforma cantidades.",
      concepto_clave: "Parte-todo: 3/5 de la pizza está comida. Operador: 3/5 × 20 = 12 (opera sobre una cantidad).",
      explicacion: [
        "Como PARTE-TODO, la fracción describe qué porción de un entero se considera. Si un pastel se divide en 8 partes y comes 3, has comido 3/8 del pastel. El entero (el pastel completo) es la unidad de referencia.",
        "Como OPERADOR, la fracción actúa sobre una cantidad y la transforma. '2/3 de 30 estudiantes' = 20 estudiantes. La fracción multiplica la cantidad.",
        "Para calcular la fracción de un conjunto: DIVIDES el total entre el denominador, luego MULTIPLICAS por el numerador.",
      ],
      ejemplos: [
        {
          enunciado: "¿Qué fracción representa 12 de 20 mangos?",
          pasos: [
            { texto: "Parte = 12, Total = 20" },
            { texto: "Fracción = 12/20" },
            { texto: "Simplificando (÷4): 3/5" },
          ],
          resultado: "12 de 20 mangos = 3/5 del total",
        },
        {
          enunciado: "¿Cuánto es 3/4 de 60?",
          pasos: [
            { texto: "60 ÷ 4 = 15 (un cuarto)" },
            { texto: "15 × 3 = 45 (tres cuartos)" },
          ],
          resultado: "3/4 de 60 = 45",
        },
      ],
      ejercicios: [
        {
          id: "5-1-8-e1",
          enunciado: "En una clase de 35 estudiantes, 4/7 son niñas. ¿Cuántas niñas hay?",
          tipo: "numero",
          respuesta: "20",
          pista: "35 ÷ 7 = 5 (una parte). 5 × 4 = ?",
          explicacion: "35 ÷ 7 = 5. 5 × 4 = 20 niñas.",
        },
        {
          id: "5-1-8-e2",
          enunciado: "Si 1/3 de un número es 15, ¿cuánto es el número completo?",
          tipo: "numero",
          respuesta: "45",
          pista: "Si una tercera parte es 15, el entero es 3 veces eso.",
          explicacion: "1/3 del número = 15. El número completo = 15 × 3 = 45.",
        },
        {
          id: "5-1-8-e3",
          enunciado: "Una escuela tiene 240 alumnos. 5/8 van al comedor. ¿Cuántos NO van al comedor?",
          tipo: "numero",
          respuesta: "90",
          pista: "Primero halla cuántos SÍ van (5/8 de 240). Luego resta del total.",
          explicacion: "240÷8=30, 30×5=150 van. 240−150=90 no van.",
        },
        {
          id: "5-1-8-e4",
          enunciado: "¿Cuánto es 2/5 de 2/3?",
          tipo: "texto",
          respuesta: "4/15",
          pista: "Multiplicar fracciones: multiplica numeradores entre sí y denominadores entre sí.",
          explicacion: "2/5 × 2/3 = (2×2)/(5×3) = 4/15.",
        },
      ],
    },
    {
      id: "5-1-9",
      titulo: "Fracción como razón y como porcentaje",
      objetivo: "Expresar relaciones entre cantidades como razón y convertir entre fracciones y porcentajes.",
      concepto_clave: "Razón: compara dos cantidades (3:5 o 3/5). Porcentaje: razón con denominador 100 (35% = 35/100 = 0,35).",
      explicacion: [
        "Una RAZÓN compara dos cantidades. 'Por cada 3 niñas hay 5 niños' → razón 3:5 o 3/5. No es lo mismo que la fracción parte-todo: aquí comparamos dos partes entre sí, no una parte con el todo.",
        "El PORCENTAJE es una razón cuyo segundo término es siempre 100. 40% = 40 de cada 100 = 40/100 = 2/5. El símbolo % significa 'de cada cien'.",
        "Para convertir fracción a porcentaje: numerador ÷ denominador × 100. Para convertir porcentaje a fracción: porcentaje/100 (simplificar si es posible).",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 3/4 a porcentaje",
          pasos: [
            { texto: "3 ÷ 4 = 0,75" },
            { texto: "0,75 × 100 = 75%" },
          ],
          resultado: "3/4 = 75%",
        },
        {
          enunciado: "¿Cuánto es el 30% de 80?",
          pasos: [
            { texto: "30% = 30/100 = 3/10" },
            { texto: "3/10 de 80 = (80 ÷ 10) × 3 = 8 × 3 = 24" },
          ],
          resultado: "30% de 80 = 24",
        },
      ],
      ejercicios: [
        {
          id: "5-1-9-e1",
          enunciado: "¿Cuánto es el 25% de 120?",
          tipo: "numero",
          respuesta: "30",
          pista: "25% = 1/4. Halla 1/4 de 120.",
          explicacion: "25% = 1/4. 120 ÷ 4 = 30.",
        },
        {
          id: "5-1-9-e2",
          enunciado: "¿Qué porcentaje es 18 de 72?",
          tipo: "numero",
          respuesta: "25",
          pista: "18/72 = ? /100. Divide 18÷72 y multiplica por 100.",
          explicacion: "18/72 = 1/4 = 0,25 = 25%.",
        },
        {
          id: "5-1-9-e3",
          enunciado: "En un grupo hay 12 niñas y 8 niños. ¿Cuál es la razón de niñas a niños?",
          tipo: "texto",
          respuesta: "3:2",
          pista: "12:8 simplificado (÷4).",
          explicacion: "12:8 = 3:2 (dividiendo ambos por 4). Por cada 3 niñas hay 2 niños.",
        },
        {
          id: "5-1-9-e4",
          enunciado: "Una camiseta cuesta $40.000 y tiene descuento del 15%. ¿Cuánto descuento te dan?",
          tipo: "numero",
          respuesta: "6000",
          pista: "15% de 40.000. Recuerda: 10%=4.000, 5%=2.000.",
          explicacion: "15% de 40.000 = 10% + 5% = 4.000 + 2.000 = 6.000.",
        },
      ],
    },
    {
      id: "5-1-10",
      titulo: "Fracciones en la semirrecta numérica",
      objetivo: "Ubicar y comparar fracciones en la semirrecta numérica.",
      concepto_clave: "Para ubicar n/d en la recta: divide cada unidad en d partes iguales y avanza n partes desde el origen.",
      explicacion: [
        "La semirrecta numérica nos permite visualizar fracciones y compararlas. Para ubicar 3/4, divides el espacio entre 0 y 1 en 4 partes iguales y marcas la tercera división.",
        "Las fracciones equivalentes ocupan el mismo punto: 1/2, 2/4 y 3/6 están todas en el mismo lugar de la recta.",
        "Para comparar fracciones con diferente denominador usando la recta, conviene convertirlas al mismo denominador o estimarlas. La fracción más a la derecha siempre es la mayor.",
      ],
      ejemplos: [
        {
          enunciado: "Ubica 5/3 en la semirrecta",
          pasos: [
            { texto: "5/3 es impropia → convierte: 5÷3 = 1 con residuo 2 → 1 y 2/3" },
            { texto: "Está entre 1 y 2, más cerca del 2" },
            { texto: "Divide el segmento 1-2 en 3 partes, avanza 2" },
          ],
          resultado: "5/3 = 1⅔ se ubica entre 1 y 2 en la recta",
        },
        {
          enunciado: "¿Cuál es mayor: 2/3 o 3/4?",
          pasos: [
            { texto: "Denominador común: 12" },
            { texto: "2/3 = 8/12 y 3/4 = 9/12" },
            { texto: "9/12 > 8/12" },
          ],
          resultado: "3/4 > 2/3 (en la recta, 3/4 queda más a la derecha)",
        },
      ],
      ejercicios: [
        {
          id: "5-1-10-e1",
          enunciado: "¿Entre qué dos números enteros está 7/5?",
          tipo: "texto",
          respuesta: "entre 1 y 2",
          pista: "Convierte 7/5 a número mixto: 7÷5=1 resto 2.",
          explicacion: "7/5 = 1 y 2/5. Está entre 1 y 2.",
        },
        {
          id: "5-1-10-e2",
          enunciado: "Ordena de menor a mayor: 1/2, 1/3, 1/4",
          tipo: "texto",
          respuesta: "1/4, 1/3, 1/2",
          pista: "Cuando el numerador es igual (1), ¿el mayor denominador da la fracción mayor o menor?",
          explicacion: "Con numerador igual, mayor denominador significa partes más pequeñas. 1/4 < 1/3 < 1/2.",
        },
        {
          id: "5-1-10-e3",
          enunciado: "¿Cuál fracción está más cerca del 1: 4/5 o 5/6?",
          tipo: "seleccion",
          opciones: ["4/5", "5/6", "Están igual de cerca"],
          respuesta: "5/6",
          pista: "¿Cuánto le falta a cada una para llegar a 1? 4/5 le falta 1/5 y 5/6 le falta 1/6.",
          explicacion: "Le falta a 4/5: 1/5=0,2. Le falta a 5/6: 1/6≈0,167. Como 1/6<1/5, la fracción 5/6 está más cerca de 1.",
        },
        {
          id: "5-1-10-e4",
          enunciado: "¿Qué fracción está exactamente a la mitad entre 0 y 1/2?",
          tipo: "texto",
          respuesta: "1/4",
          pista: "La mitad de 1/2 es la mitad de la mitad del entero.",
          explicacion: "(0 + 1/2) ÷ 2 = (1/2) ÷ 2 = 1/4. La fracción 1/4 está exactamente entre 0 y 1/2.",
        },
      ],
    },
    {
      id: "5-1-11",
      titulo: "Adición y sustracción de fracciones",
      objetivo: "Sumar y restar fracciones con denominadores diferentes usando el MCM.",
      concepto_clave: "Para sumar/restar fracciones heterogéneas: halla el MCM de los denominadores para obtener el denominador común.",
      explicacion: [
        "Las fracciones HOMOGÉNEAS (mismo denominador) se suman/restan directo: 3/7 + 2/7 = 5/7. Solo sumamos los numeradores.",
        "Las fracciones HETEROGÉNEAS (diferente denominador) necesitan convertirse primero al mismo denominador. Usamos el MCM. Ejemplo: 1/4 + 1/6 → MCM(4,6)=12 → 3/12 + 2/12 = 5/12.",
        "Pasos: 1) Halla el MCM. 2) Convierte cada fracción al nuevo denominador. 3) Suma/resta los numeradores. 4) Simplifica si es posible.",
      ],
      ejemplos: [
        {
          enunciado: "Calcula: 2/3 + 3/4",
          pasos: [
            { texto: "MCM(3,4) = 12" },
            { texto: "2/3 = 8/12 (×4 arriba y abajo)" },
            { texto: "3/4 = 9/12 (×3 arriba y abajo)" },
            { texto: "8/12 + 9/12 = 17/12" },
          ],
          resultado: "2/3 + 3/4 = 17/12 = 1 y 5/12",
        },
        {
          enunciado: "Calcula: 5/6 − 1/4",
          pasos: [
            { texto: "MCM(6,4) = 12" },
            { texto: "5/6 = 10/12 y 1/4 = 3/12" },
            { texto: "10/12 − 3/12 = 7/12" },
          ],
          resultado: "5/6 − 1/4 = 7/12",
        },
      ],
      ejercicios: [
        {
          id: "5-1-11-e1",
          enunciado: "Calcula: 1/2 + 1/3",
          tipo: "texto",
          respuesta: "5/6",
          pista: "MCM(2,3)=6. 1/2=3/6 y 1/3=2/6.",
          explicacion: "3/6 + 2/6 = 5/6.",
        },
        {
          id: "5-1-11-e2",
          enunciado: "Calcula: 3/4 − 1/6",
          tipo: "texto",
          respuesta: "7/12",
          pista: "MCM(4,6)=12. 3/4=9/12 y 1/6=2/12.",
          explicacion: "9/12 − 2/12 = 7/12.",
        },
        {
          id: "5-1-11-e3",
          enunciado: "Ana bebió 1/3 de jugo y Pedro 2/5. ¿Cuánto bebieron entre los dos?",
          tipo: "texto",
          respuesta: "11/15",
          pista: "MCM(3,5)=15. 1/3=5/15 y 2/5=6/15.",
          explicacion: "5/15 + 6/15 = 11/15 del total de jugo.",
        },
        {
          id: "5-1-11-e4",
          enunciado: "¿Cuánto es 1 − 3/8?",
          tipo: "texto",
          respuesta: "5/8",
          pista: "Escribe 1 como 8/8.",
          explicacion: "1 = 8/8. 8/8 − 3/8 = 5/8.",
        },
      ],
    },
    {
      id: "5-1-12",
      titulo: "Multiplicación y división de fracciones",
      objetivo: "Multiplicar y dividir fracciones aplicando los algoritmos y simplificando resultados.",
      concepto_clave: "Multiplicación: numerador × numerador / denominador × denominador. División: multiplica por el recíproco del divisor.",
      explicacion: [
        "Para MULTIPLICAR fracciones: multiplica los numeradores entre sí y los denominadores entre sí. Ejemplo: 2/3 × 3/4 = (2×3)/(3×4) = 6/12 = 1/2.",
        "Truco: puedes SIMPLIFICAR en diagonal antes de multiplicar para trabajar con números más pequeños. 2/3 × 3/4 → simplifica el 2 con el 4 (÷2) y el 3 con el 3 (÷3) → 1/1 × 1/2 = 1/2.",
        "Para DIVIDIR fracciones: voltea la segunda fracción (tomas su recíproco) y multiplicas. Ejemplo: 2/3 ÷ 4/5 = 2/3 × 5/4 = 10/12 = 5/6.",
      ],
      ejemplos: [
        {
          enunciado: "Calcula: 3/5 × 10/9",
          pasos: [
            { texto: "Simplifica en diagonal: 3 y 9 → ÷3: 1 y 3. 10 y 5 → ÷5: 2 y 1" },
            { texto: "1/1 × 2/3 = 2/3" },
          ],
          resultado: "3/5 × 10/9 = 2/3",
        },
        {
          enunciado: "Calcula: 4/5 ÷ 2/3",
          pasos: [
            { texto: "Volteo la segunda fracción: 2/3 → 3/2" },
            { texto: "4/5 × 3/2 = 12/10" },
            { texto: "Simplifica: 12/10 = 6/5 = 1 y 1/5" },
          ],
          resultado: "4/5 ÷ 2/3 = 6/5 = 1 y 1/5",
        },
      ],
      ejercicios: [
        {
          id: "5-1-12-e1",
          enunciado: "Calcula: 2/3 × 3/8",
          tipo: "texto",
          respuesta: "1/4",
          pista: "Simplifica el 3 con el 3 y el 2 con el 8 antes de multiplicar.",
          explicacion: "2/3 × 3/8: simplifica 3÷3=1 y 2÷2=1, 8÷2=4. Queda 1/1 × 1/4 = 1/4.",
        },
        {
          id: "5-1-12-e2",
          enunciado: "Calcula: 5/6 ÷ 5/12",
          tipo: "numero",
          respuesta: "2",
          pista: "Voltea 5/12 → 12/5. Luego 5/6 × 12/5.",
          explicacion: "5/6 × 12/5: simplifica 5÷5=1 y 12÷6=2. Queda 1/1 × 2/1 = 2.",
        },
        {
          id: "5-1-12-e3",
          enunciado: "Un rollo de tela tiene 3/4 de metro. Cortas 1/3 de esa tela. ¿Cuánto cortaste?",
          tipo: "texto",
          respuesta: "1/4",
          pista: "Necesitas 1/3 de 3/4. Multiplica.",
          explicacion: "1/3 × 3/4 = 3/12 = 1/4 de metro.",
        },
        {
          id: "5-1-12-e4",
          enunciado: "¿Cuántas porciones de 1/4 caben en 3/2?",
          tipo: "numero",
          respuesta: "6",
          pista: "¿Cuántas veces cabe 1/4 en 3/2? Divide 3/2 ÷ 1/4.",
          explicacion: "3/2 ÷ 1/4 = 3/2 × 4/1 = 12/2 = 6 porciones.",
        },
      ],
    },
  ],
}

export default unidad1
