import type { Unidad } from "../tipos"

const unidad2: Unidad = {
  id: 2,
  nombre: "Números decimales",
  descripcion: "Lee, escribe, ordena y opera con números decimales y comprende su relación con fracciones y porcentajes.",
  color: "green",
  icono: "🔣",
  lecciones: [
    {
      id: "5-2-1",
      titulo: "Representación decimal de fracciones",
      objetivo: "Convertir fracciones a decimales dividiendo el numerador entre el denominador.",
      concepto_clave: "Fracción → decimal: divide el numerador entre el denominador. 3/4 = 3 ÷ 4 = 0,75.",
      explicacion: [
        "Todo número decimal puede escribirse como fracción y viceversa. Para convertir una fracción a decimal, simplemente divides el numerador entre el denominador.",
        "Algunas fracciones dan decimales EXACTOS (terminan): 1/4 = 0,25. Otras dan decimales PERIÓDICOS (se repiten): 1/3 = 0,333... = 0,3̄.",
        "Fracciones con denominadores que solo tienen factores de 2 y/o 5 siempre dan decimales exactos. Por ejemplo: 1/8 (denominador=2³) → 0,125.",
      ],
      ejemplos: [
        {
          enunciado: "Convierte 7/8 a decimal",
          pasos: [
            { texto: "7 ÷ 8 = ?" },
            { texto: "7,000 ÷ 8: 8 no cabe en 7, ponemos 0," },
            { texto: "70 ÷ 8 = 8 (resto 6) → 0,8" },
            { texto: "60 ÷ 8 = 7 (resto 4) → 0,87" },
            { texto: "40 ÷ 8 = 5 (resto 0) → 0,875" },
          ],
          resultado: "7/8 = 0,875",
        },
        {
          enunciado: "Convierte 2/3 a decimal",
          pasos: [
            { texto: "2 ÷ 3 = 0,666..." },
            { texto: "El 6 se repite infinitamente" },
          ],
          resultado: "2/3 = 0,6̄ (decimal periódico)",
        },
      ],
      ejercicios: [
        {
          id: "5-2-1-e1",
          enunciado: "Convierte 3/5 a decimal",
          tipo: "texto",
          respuesta: "0,6",
          pista: "3 ÷ 5 = ?",
          explicacion: "3 ÷ 5 = 0,6 (exacto).",
        },
        {
          id: "5-2-1-e2",
          enunciado: "Convierte 1/4 a decimal",
          tipo: "texto",
          respuesta: "0,25",
          pista: "1 ÷ 4. Recuerda que 4 no cabe en 1, así que empiezas con 0,",
          explicacion: "1 ÷ 4 = 0,25. También se puede ver como 25/100.",
        },
        {
          id: "5-2-1-e3",
          enunciado: "¿Qué fracción equivale a 0,5?",
          tipo: "texto",
          respuesta: "1/2",
          pista: "0,5 = 5/10. Simplifica dividiendo entre 5.",
          explicacion: "0,5 = 5/10 = 1/2.",
        },
        {
          id: "5-2-1-e4",
          enunciado: "¿Cuál es mayor: 5/8 o 3/5?",
          tipo: "seleccion",
          opciones: ["5/8", "3/5", "Son iguales"],
          respuesta: "5/8",
          pista: "Convierte ambas a decimal: 5÷8=? y 3÷5=0,6",
          explicacion: "5/8=0,625 y 3/5=0,6. Como 0,625>0,6, entonces 5/8 > 3/5.",
        },
      ],
    },
    {
      id: "5-2-2",
      titulo: "Lectura y escritura de números decimales",
      objetivo: "Leer y escribir correctamente números decimales identificando el valor de cada cifra.",
      concepto_clave: "Décimas (1/10), centésimas (1/100), milésimas (1/1000). El punto (o coma) separa la parte entera de la decimal.",
      explicacion: [
        "Los números decimales tienen una parte ENTERA (a la izquierda del punto) y una parte DECIMAL (a la derecha). Cada posición tiene un nombre: la primera cifra decimal es la DÉCIMA (1/10), la segunda es la CENTÉSIMA (1/100), la tercera es la MILÉSIMA (1/1000).",
        "Para LEER un decimal: lee la parte entera, di 'punto' o 'coma', y lee la parte decimal indicando el valor de la última cifra. 5,34 = 'cinco coma treinta y cuatro centésimos'.",
        "Para ESCRIBIR un decimal a partir de su nombre: 'doce milésimos' = 0,012 (tres cifras decimales, la última es milésimos).",
      ],
      ejemplos: [
        {
          enunciado: "¿Cómo se lee 3,047?",
          pasos: [
            { texto: "Parte entera: 3 → 'tres'" },
            { texto: "Parte decimal: 047 → la última cifra (7) es milésimos" },
            { texto: "Se lee: 'cuarenta y siete milésimos'" },
          ],
          resultado: "3,047 = 'tres coma cuarenta y siete milésimos'",
        },
        {
          enunciado: "Escribe en número: 'cinco décimas'",
          pasos: [
            { texto: "Décimas = primera posición decimal" },
            { texto: "5 en la posición de décimas" },
          ],
          resultado: "Cinco décimas = 0,5",
        },
      ],
      ejercicios: [
        {
          id: "5-2-2-e1",
          enunciado: "¿Cuánto vale el dígito 6 en 4,263?",
          tipo: "texto",
          respuesta: "6 centésimas",
          pista: "Cuenta las posiciones decimales: primera=décimas, segunda=centésimas.",
          explicacion: "En 4,263: el 2 es décimas, el 6 es centésimas, el 3 es milésimas. El 6 vale 6/100 = 6 centésimas.",
        },
        {
          id: "5-2-2-e2",
          enunciado: "Escribe en número: 'veintitrés centésimas'",
          tipo: "texto",
          respuesta: "0,23",
          pista: "Centésimas: necesitas dos cifras decimales.",
          explicacion: "Veintitrés centésimas = 23/100 = 0,23.",
        },
        {
          id: "5-2-2-e3",
          enunciado: "¿Cuál es el valor posicional de la cifra 8 en 12,038?",
          tipo: "seleccion",
          opciones: ["Décimas", "Centésimas", "Milésimas"],
          respuesta: "Milésimas",
          pista: "Cuenta desde el punto: 0 es décimas, 3 es centésimas, 8 es...",
          explicacion: "En 12,038: el 0 está en décimas, el 3 en centésimas, el 8 en milésimas.",
        },
        {
          id: "5-2-2-e4",
          enunciado: "Ordena de mayor a menor: 0,5 / 0,45 / 0,509",
          tipo: "texto",
          respuesta: "0,509, 0,5, 0,45",
          pista: "Compara cifra a cifra. Primero la parte entera (igual), luego décimas, centésimas...",
          explicacion: "Décimas: 5=5>4. Entre 0,5 y 0,509: en centésimas 0=0, en milésimas 0<9. Orden: 0,509>0,5>0,45.",
        },
      ],
    },
    {
      id: "5-2-3",
      titulo: "Números decimales y porcentajes",
      objetivo: "Convertir entre decimales y porcentajes y usar porcentajes en problemas del cotidiano.",
      concepto_clave: "Decimal → %: multiplica por 100. % → decimal: divide entre 100. 0,35 = 35% y 72% = 0,72.",
      explicacion: [
        "El porcentaje y el decimal son dos formas de expresar la misma cantidad. La conversión es sencilla: para pasar de decimal a porcentaje multiplicas por 100 (o mueves el punto dos lugares a la derecha). Para pasar de porcentaje a decimal divides entre 100 (mueves el punto dos lugares a la izquierda).",
        "Ejemplos: 0,7 = 70%, 0,05 = 5%, 1,25 = 125%, 0,003 = 0,3%.",
        "Los porcentajes mayores del 100% son posibles: 150% = 1,5 (una cantidad y media del total).",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuánto es el 35% de 200?",
          pasos: [
            { texto: "35% = 0,35" },
            { texto: "0,35 × 200 = 70" },
          ],
          resultado: "El 35% de 200 es 70",
        },
        {
          enunciado: "Convierte 0,625 a porcentaje",
          pasos: [
            { texto: "0,625 × 100 = 62,5" },
          ],
          resultado: "0,625 = 62,5%",
        },
      ],
      ejercicios: [
        {
          id: "5-2-3-e1",
          enunciado: "Convierte 45% a decimal",
          tipo: "texto",
          respuesta: "0,45",
          pista: "Divide entre 100: mueve el punto dos lugares a la izquierda.",
          explicacion: "45% = 45 ÷ 100 = 0,45.",
        },
        {
          id: "5-2-3-e2",
          enunciado: "¿Cuánto es el 60% de 150?",
          tipo: "numero",
          respuesta: "90",
          pista: "60% = 0,60. Multiplica 0,60 × 150.",
          explicacion: "0,60 × 150 = 90.",
        },
        {
          id: "5-2-3-e3",
          enunciado: "Una camisa cuesta $80.000. Está en descuento del 20%. ¿Cuánto pagas?",
          tipo: "numero",
          respuesta: "64000",
          pista: "Descuento = 20% de 80.000. Precio final = 80.000 − descuento.",
          explicacion: "20% de 80.000 = 0,20 × 80.000 = 16.000. Pagas 80.000 − 16.000 = 64.000.",
        },
        {
          id: "5-2-3-e4",
          enunciado: "Si el IVA es del 19%, ¿cuánto IVA tiene un producto de $50.000?",
          tipo: "numero",
          respuesta: "9500",
          pista: "19% de 50.000 = 0,19 × 50.000.",
          explicacion: "0,19 × 50.000 = 9.500.",
        },
      ],
    },
    {
      id: "5-2-4",
      titulo: "Decimales en la semirrecta numérica",
      objetivo: "Ubicar y comparar números decimales en la semirrecta numérica.",
      concepto_clave: "Los decimales llenan los espacios entre los enteros. Entre 0 y 1 hay infinitos decimales.",
      explicacion: [
        "La semirrecta numérica permite visualizar la posición exacta de los decimales. Entre cada par de enteros consecutivos hay infinitos números decimales.",
        "Para ubicar 2,3: vai al 2 y avanza 3 décimas hacia el 3. Para ubicar 1,75: vai al 1 y avanza 7,5 décimas (o 75 centésimas).",
        "Los decimales nos permiten afinar la precisión de las medidas: entre 2,4 y 2,5 hay 2,41, 2,42... 2,49. ¡Siempre hay más números entre dos decimales!",
      ],
      ejemplos: [
        {
          enunciado: "Ubica 0,7 y 0,25 en la recta entre 0 y 1",
          pasos: [
            { texto: "0,7 está en 7 décimas → cerca del 1" },
            { texto: "0,25 está en 25 centésimas → cerca del 0, entre 0,2 y 0,3" },
          ],
          resultado: "0 ... 0,25 ... 0,7 ... 1",
        },
        {
          enunciado: "¿Qué número está exactamente entre 0,4 y 0,6?",
          pasos: [
            { texto: "Suma y divide entre 2: (0,4 + 0,6) ÷ 2" },
            { texto: "= 1,0 ÷ 2 = 0,5" },
          ],
          resultado: "0,5 está exactamente entre 0,4 y 0,6",
        },
      ],
      ejercicios: [
        {
          id: "5-2-4-e1",
          enunciado: "Ordena de menor a mayor: 0,3 / 0,25 / 0,305",
          tipo: "texto",
          respuesta: "0,25, 0,3, 0,305",
          pista: "Compara cifra a cifra o expresa con el mismo número de decimales: 0,300 / 0,250 / 0,305.",
          explicacion: "0,250 < 0,300 < 0,305.",
        },
        {
          id: "5-2-4-e2",
          enunciado: "¿Qué número está entre 1,2 y 1,3?",
          tipo: "texto",
          respuesta: "1,25",
          pista: "Cualquier número con dos cifras decimales entre 1,20 y 1,30 es válido.",
          explicacion: "Por ejemplo 1,25. Entre 1,2 y 1,3 hay infinitos decimales como 1,21, 1,25, 1,29...",
        },
        {
          id: "5-2-4-e3",
          enunciado: "¿Cuánto es el punto medio entre 3,5 y 4?",
          tipo: "texto",
          respuesta: "3,75",
          pista: "(3,5 + 4) ÷ 2 = ?",
          explicacion: "(3,5 + 4) ÷ 2 = 7,5 ÷ 2 = 3,75.",
        },
        {
          id: "5-2-4-e4",
          enunciado: "¿Cuál es el decimal más grande con dos cifras decimales que sea menor que 0,5?",
          tipo: "texto",
          respuesta: "0,49",
          pista: "Busca el número más cercano a 0,5 por debajo con exactamente 2 cifras decimales.",
          explicacion: "0,49 es el mayor decimal con 2 cifras que aún es menor que 0,5.",
        },
      ],
    },
    {
      id: "5-2-5",
      titulo: "Aproximación de números decimales",
      objetivo: "Redondear números decimales al entero, décima o centésima más cercana.",
      concepto_clave: "Redondeo: si el dígito siguiente ≥ 5 sube 1, si < 5 queda igual. Se aplica igual que con enteros.",
      explicacion: [
        "Redondear decimales sigue la misma regla que redondear enteros: miras el dígito a la derecha de la posición a la que quieres redondear. Si es ≥ 5 subes, si es < 5 dejas igual.",
        "Ejemplo: 3,748 redondeado a la décima más cercana. Miro la centésima (4): 4<5 → 3,7.",
        "Redondear a la centésima más cercana: 3,748 → miro la milésima (8): 8≥5 → sube → 3,75.",
      ],
      ejemplos: [
        {
          enunciado: "Redondea 2,364 a la décima más cercana",
          pasos: [
            { texto: "La décima tiene un 3. Miro la siguiente cifra: 6" },
            { texto: "6 ≥ 5 → el 3 sube a 4" },
          ],
          resultado: "2,364 ≈ 2,4",
        },
        {
          enunciado: "Redondea 7,995 al entero más cercano",
          pasos: [
            { texto: "La parte entera es 7. Miro la décima: 9" },
            { texto: "9 ≥ 5 → el 7 sube a 8" },
          ],
          resultado: "7,995 ≈ 8",
        },
      ],
      ejercicios: [
        {
          id: "5-2-5-e1",
          enunciado: "Redondea 5,736 a la centésima más cercana",
          tipo: "texto",
          respuesta: "5,74",
          pista: "Miro la milésima (6): 6≥5, la centésima (3) sube a 4.",
          explicacion: "5,736 → centésima es 3, milésima es 6≥5 → 3 sube a 4 → 5,74.",
        },
        {
          id: "5-2-5-e2",
          enunciado: "Redondea 0,845 a la décima más cercana",
          tipo: "texto",
          respuesta: "0,8",
          pista: "Miro la centésima (4): 4<5, la décima (8) queda igual.",
          explicacion: "0,845 → décima es 8, centésima es 4<5 → queda 0,8.",
        },
        {
          id: "5-2-5-e3",
          enunciado: "¿Cuánto es π ≈ 3,14159 redondeado a dos decimales?",
          tipo: "texto",
          respuesta: "3,14",
          pista: "Miro la milésima (1): 1<5, la centésima (4) queda igual.",
          explicacion: "3,14159 → centésima es 4, milésima es 1<5 → queda 3,14.",
        },
        {
          id: "5-2-5-e4",
          enunciado: "Un estudiante mide 1,574 m. ¿Cuánto mide redondeado al centímetro (2 decimales)?",
          tipo: "texto",
          respuesta: "1,57",
          pista: "Redondea a la centésima. Mira la milésima: 4<5.",
          explicacion: "1,574 → milésima es 4<5 → queda 1,57 m = 1 metro y 57 centímetros.",
        },
      ],
    },
    {
      id: "5-2-6",
      titulo: "Estimación de operaciones con números decimales",
      objetivo: "Estimar resultados de operaciones con decimales para verificar la razonabilidad de los cálculos.",
      concepto_clave: "Redondea cada decimal al entero o décima más cercana antes de operar. La estimación detecta errores grandes.",
      explicacion: [
        "La estimación con decimales funciona igual que con enteros: redondeamos para simplificar el cálculo y obtenemos un resultado aproximado que nos dice si el resultado exacto es razonable.",
        "Por ejemplo, antes de calcular 4,87 × 3,2, estimamos: 5 × 3 = 15. Si el resultado exacto da 1,5 o 150, sabemos que algo está mal.",
        "La estimación es una herramienta de verificación: no reemplaza el cálculo exacto, sino que lo acompaña.",
      ],
      ejemplos: [
        {
          enunciado: "Estima: 9,87 + 5,14 + 2,96",
          pasos: [
            { texto: "9,87 ≈ 10, 5,14 ≈ 5, 2,96 ≈ 3" },
            { texto: "10 + 5 + 3 = 18" },
          ],
          resultado: "La suma es aproximadamente 18 (exacto: 17,97)",
        },
        {
          enunciado: "Estima: 6,3 × 4,8",
          pasos: [
            { texto: "6,3 ≈ 6 y 4,8 ≈ 5" },
            { texto: "6 × 5 = 30" },
          ],
          resultado: "6,3 × 4,8 ≈ 30 (exacto: 30,24)",
        },
      ],
      ejercicios: [
        {
          id: "5-2-6-e1",
          enunciado: "Estima: 7,9 × 3,1",
          tipo: "numero",
          respuesta: "24",
          pista: "7,9 ≈ 8 y 3,1 ≈ 3.",
          explicacion: "8 × 3 = 24. El resultado exacto es 24,49.",
        },
        {
          id: "5-2-6-e2",
          enunciado: "Un alumno calculó 2,5 × 1,8 = 45. ¿Tiene sentido?",
          tipo: "seleccion",
          opciones: ["Sí, parece correcto", "No, parece demasiado grande"],
          respuesta: "No, parece demasiado grande",
          pista: "Estima: 2,5 ≈ 3 y 1,8 ≈ 2. ¿Cuánto es 3×2?",
          explicacion: "3 × 2 = 6. El resultado debería ser cercano a 6, no 45. El error fue no poner la coma: 2,5 × 1,8 = 4,5.",
        },
        {
          id: "5-2-6-e3",
          enunciado: "Estima la división: 19,8 ÷ 3,9",
          tipo: "numero",
          respuesta: "5",
          pista: "19,8 ≈ 20 y 3,9 ≈ 4. ¿Cuánto es 20÷4?",
          explicacion: "20 ÷ 4 = 5. El resultado exacto es ≈ 5,08.",
        },
        {
          id: "5-2-6-e4",
          enunciado: "Estima cuánto cuestan 4 cuadernos a $3.750 cada uno",
          tipo: "numero",
          respuesta: "16000",
          pista: "$3.750 ≈ $4.000. 4 × $4.000 = ?",
          explicacion: "4 × 4.000 = 16.000. El precio exacto es 4 × 3.750 = 15.000.",
        },
      ],
    },
    {
      id: "5-2-7",
      titulo: "Adición y sustracción de números decimales",
      objetivo: "Sumar y restar números decimales alineando correctamente las comas.",
      concepto_clave: "Para sumar/restar decimales: alinea las comas (los puntos decimales deben estar en columna), luego opera igual que con enteros.",
      explicacion: [
        "La clave de las operaciones con decimales es ALINEAR LA COMA. Si los números tienen diferente cantidad de cifras decimales, agregas ceros a la derecha para igualarlos. Un cero al final de un decimal no cambia su valor: 3,5 = 3,50.",
        "Una vez alineadas las comas, sumas o restas igual que con números enteros, columna por columna de derecha a izquierda, llevando cuando es necesario.",
        "La coma del resultado va exactamente debajo de las comas de los sumandos.",
      ],
      ejemplos: [
        {
          enunciado: "Calcula: 5,37 + 2,8",
          pasos: [
            { texto: "Igualo decimales: 5,37 + 2,80" },
            { texto: "  5,37\n+ 2,80\n------" },
            { texto: "7+0=7, 3+8=11 (escribo 1, llevo 1), 5+2+1=8, coma" },
          ],
          resultado: "5,37 + 2,8 = 8,17",
        },
        {
          enunciado: "Calcula: 10 − 3,45",
          pasos: [
            { texto: "10 = 10,00 (agrego decimales)" },
            { texto: "  10,00\n−  3,45\n-------" },
            { texto: "Resto de derecha a izquierda con préstamos: 6,55" },
          ],
          resultado: "10 − 3,45 = 6,55",
        },
      ],
      ejercicios: [
        {
          id: "5-2-7-e1",
          enunciado: "Calcula: 4,6 + 3,75",
          tipo: "texto",
          respuesta: "8,35",
          pista: "Iguala: 4,60 + 3,75. Alinea las comas y suma.",
          explicacion: "4,60 + 3,75: 0+5=5, 6+7=13 (1 llevo 1), 4+3+1=8. Resultado: 8,35.",
        },
        {
          id: "5-2-7-e2",
          enunciado: "Calcula: 7,2 − 4,58",
          tipo: "texto",
          respuesta: "2,62",
          pista: "7,2 = 7,20. Resta 7,20 − 4,58.",
          explicacion: "7,20 − 4,58: 0<8, pido prestado → 10−8=2, 1<5+1=6 pido prestado → 11−6=5... queda 2,62.",
        },
        {
          id: "5-2-7-e3",
          enunciado: "Un atleta corrió 4,35 km en la mañana y 2,8 km en la tarde. ¿Cuánto corrió en total?",
          tipo: "texto",
          respuesta: "7,15",
          pista: "4,35 + 2,80 = ?",
          explicacion: "4,35 + 2,80 = 7,15 km.",
        },
        {
          id: "5-2-7-e4",
          enunciado: "Si tengo $15.000 y gasto $8.750, ¿cuánto me queda?",
          tipo: "numero",
          respuesta: "6250",
          pista: "15.000,00 − 8.750,00.",
          explicacion: "15.000 − 8.750 = 6.250.",
        },
      ],
    },
    {
      id: "5-2-8",
      titulo: "Multiplicación de decimales por potencias de 10",
      objetivo: "Multiplicar y dividir números decimales por 10, 100, 1000 usando el desplazamiento del punto.",
      concepto_clave: "Multiplicar por 10ⁿ: mueve el punto n lugares a la derecha. Dividir por 10ⁿ: mueve el punto n lugares a la izquierda.",
      explicacion: [
        "Multiplicar por 10, 100, 1000 es equivalente a mover el punto decimal hacia la DERECHA el mismo número de ceros. 3,45 × 10 = 34,5 (moví el punto 1 lugar a la derecha).",
        "Dividir por 10, 100, 1000 es mover el punto hacia la IZQUIERDA. 3,45 ÷ 100 = 0,0345 (moví el punto 2 lugares a la izquierda).",
        "Este truco es muy útil para conversiones de unidades: pasar de metros a centímetros es multiplicar por 100 (mover punto 2 a la derecha).",
      ],
      ejemplos: [
        {
          enunciado: "Calcula: 0,047 × 1000",
          pasos: [
            { texto: "Multiplico por 1000 → muevo el punto 3 lugares a la derecha" },
            { texto: "0,047 → 0,47 → 4,7 → 47" },
          ],
          resultado: "0,047 × 1000 = 47",
        },
        {
          enunciado: "Calcula: 58,3 ÷ 100",
          pasos: [
            { texto: "Divido entre 100 → muevo el punto 2 lugares a la izquierda" },
            { texto: "58,3 → 5,83 → 0,583" },
          ],
          resultado: "58,3 ÷ 100 = 0,583",
        },
      ],
      ejercicios: [
        {
          id: "5-2-8-e1",
          enunciado: "Calcula: 2,5 × 100",
          tipo: "numero",
          respuesta: "250",
          pista: "Mueve el punto 2 lugares a la derecha.",
          explicacion: "2,5 × 100 = 250.",
        },
        {
          id: "5-2-8-e2",
          enunciado: "Calcula: 4300 ÷ 1000",
          tipo: "texto",
          respuesta: "4,3",
          pista: "Mueve el punto 3 lugares a la izquierda: 4300 → 430 → 43 → 4,3.",
          explicacion: "4300 ÷ 1000 = 4,3.",
        },
        {
          id: "5-2-8-e3",
          enunciado: "1 metro = 100 cm. Si una tela mide 2,35 m, ¿cuántos centímetros son?",
          tipo: "numero",
          respuesta: "235",
          pista: "Multiplica por 100: mueve el punto 2 a la derecha.",
          explicacion: "2,35 × 100 = 235 cm.",
        },
        {
          id: "5-2-8-e4",
          enunciado: "¿Cuánto es 0,08 × 10.000?",
          tipo: "numero",
          respuesta: "800",
          pista: "10.000 = 10⁴. Mueve el punto 4 lugares a la derecha.",
          explicacion: "0,08 × 10.000: 0,08 → 0,8 → 8 → 80 → 800.",
        },
      ],
    },
    {
      id: "5-2-9",
      titulo: "Multiplicación de números decimales",
      objetivo: "Multiplicar números decimales contando y colocando correctamente el punto decimal en el resultado.",
      concepto_clave: "Multiplica como si fueran enteros, luego cuenta el total de cifras decimales de ambos factores y coloca la coma en el resultado.",
      explicacion: [
        "Para multiplicar decimales: 1) Multiplica ignorando las comas (como si fueran enteros). 2) Cuenta las cifras decimales de AMBOS factores. 3) Coloca la coma en el resultado contando desde la derecha esa cantidad de cifras.",
        "Ejemplo: 1,2 × 0,4. Ignora comas: 12 × 4 = 48. Cifras decimales: 1 + 1 = 2. Resultado: 0,48.",
        "Si el resultado tiene menos cifras que la cantidad de decimales, agrega ceros a la izquierda: 0,02 × 0,3: 2×3=6, cifras decimales=3 → 0,006.",
      ],
      ejemplos: [
        {
          enunciado: "Calcula: 2,5 × 1,4",
          pasos: [
            { texto: "Sin comas: 25 × 14 = 350" },
            { texto: "Decimales: 1 (de 2,5) + 1 (de 1,4) = 2" },
            { texto: "Coloca la coma: 3,50" },
          ],
          resultado: "2,5 × 1,4 = 3,50 = 3,5",
        },
        {
          enunciado: "Calcula: 0,12 × 0,5",
          pasos: [
            { texto: "Sin comas: 12 × 5 = 60" },
            { texto: "Decimales: 2 + 1 = 3" },
            { texto: "Coloca la coma (3 desde la derecha): 0,060 = 0,06" },
          ],
          resultado: "0,12 × 0,5 = 0,06",
        },
      ],
      ejercicios: [
        {
          id: "5-2-9-e1",
          enunciado: "Calcula: 3,2 × 2,5",
          tipo: "numero",
          respuesta: "8",
          pista: "32×25=800. Cifras decimales: 1+1=2. Pon la coma: 8,00=8.",
          explicacion: "32×25=800. 2 decimales → 8,00 = 8.",
        },
        {
          id: "5-2-9-e2",
          enunciado: "Calcula: 0,4 × 0,7",
          tipo: "texto",
          respuesta: "0,28",
          pista: "4×7=28. Decimales: 1+1=2. Pon la coma.",
          explicacion: "4×7=28. 2 decimales → 0,28.",
        },
        {
          id: "5-2-9-e3",
          enunciado: "Una manzana pesa 0,25 kg. ¿Cuánto pesan 6 manzanas?",
          tipo: "texto",
          respuesta: "1,5",
          pista: "6 × 0,25 = ?",
          explicacion: "6 × 25 = 150. 2 decimales → 1,50 = 1,5 kg.",
        },
        {
          id: "5-2-9-e4",
          enunciado: "Calcula: 0,03 × 0,4",
          tipo: "texto",
          respuesta: "0,012",
          pista: "3×4=12. Decimales: 2+1=3. ¿Cuántos ceros necesitas agregar?",
          explicacion: "3×4=12. 3 decimales → 0,012.",
        },
      ],
    },
    {
      id: "5-2-10",
      titulo: "División de números decimales",
      objetivo: "Dividir números decimales entre enteros y entre decimales con método sistemático.",
      concepto_clave: "Para dividir decimales: convierte en divisiones de enteros multiplicando ambos por una potencia de 10 hasta eliminar los decimales del divisor.",
      explicacion: [
        "Hay dos casos: dividir un decimal entre un entero, y dividir entre un decimal.",
        "Decimal ÷ entero: divide normalmente. Cuando llegues al punto decimal en el dividendo, pon el punto en el cociente y sigue dividiendo. Ejemplo: 7,5 ÷ 3 → el 3 cabe en 7 dos veces (resto 1), baja el 5 → 15 ÷ 3 = 5. Resultado: 2,5.",
        "Decimal ÷ decimal: multiplica ambos por la potencia de 10 que elimine los decimales del divisor. 4,8 ÷ 0,6 = 48 ÷ 6 = 8. (Multiplicamos ambos por 10.)",
      ],
      ejemplos: [
        {
          enunciado: "Calcula: 3,6 ÷ 4",
          pasos: [
            { texto: "4 no cabe en 3, escribo 0," },
            { texto: "36 ÷ 4 = 9" },
          ],
          resultado: "3,6 ÷ 4 = 0,9",
        },
        {
          enunciado: "Calcula: 2,4 ÷ 0,3",
          pasos: [
            { texto: "Multiplico ambos por 10: 24 ÷ 3" },
            { texto: "24 ÷ 3 = 8" },
          ],
          resultado: "2,4 ÷ 0,3 = 8",
        },
      ],
      ejercicios: [
        {
          id: "5-2-10-e1",
          enunciado: "Calcula: 5,4 ÷ 6",
          tipo: "texto",
          respuesta: "0,9",
          pista: "6 no cabe en 5, pon 0, luego 54÷6=9. Resultado: 0,9.",
          explicacion: "5,4 ÷ 6 = 0,9.",
        },
        {
          id: "5-2-10-e2",
          enunciado: "Calcula: 1,8 ÷ 0,6",
          tipo: "numero",
          respuesta: "3",
          pista: "Multiplica ambos por 10: 18 ÷ 6.",
          explicacion: "18 ÷ 6 = 3.",
        },
        {
          id: "5-2-10-e3",
          enunciado: "Reparto 4,5 litros de jugo en vasos de 0,75 litros. ¿Cuántos vasos lleno?",
          tipo: "numero",
          respuesta: "6",
          pista: "4,5 ÷ 0,75. Multiplica ambos por 100: 450 ÷ 75.",
          explicacion: "450 ÷ 75 = 6 vasos.",
        },
        {
          id: "5-2-10-e4",
          enunciado: "¿Cuánto es 0,08 ÷ 0,4?",
          tipo: "texto",
          respuesta: "0,2",
          pista: "Multiplica ambos por 10: 0,8 ÷ 4.",
          explicacion: "0,8 ÷ 4 = 0,2.",
        },
      ],
    },
    {
      id: "5-2-11",
      titulo: "Equivalencias numéricas",
      objetivo: "Reconocer y usar las equivalencias entre fracciones, decimales y porcentajes.",
      concepto_clave: "1/2 = 0,5 = 50%. 1/4 = 0,25 = 25%. 1/5 = 0,2 = 20%. 1/10 = 0,1 = 10%.",
      explicacion: [
        "Fracciones, decimales y porcentajes son tres formas de expresar la misma cantidad. Conocer las equivalencias más comunes te permite hacer conversiones mentalmente y resolver problemas rápido.",
        "Tabla de equivalencias básicas: 1/2=0,5=50%, 1/4=0,25=25%, 3/4=0,75=75%, 1/5=0,2=20%, 2/5=0,4=40%, 3/5=0,6=60%, 4/5=0,8=80%, 1/10=0,1=10%, 1/100=0,01=1%.",
        "Con estas equivalencias puedes calcular porcentajes mentalmente. Por ejemplo, para calcular el 25% de 80: como 25%=1/4, calcula 80÷4=20.",
      ],
      ejemplos: [
        {
          enunciado: "¿A qué fracción y decimal equivale el 40%?",
          pasos: [
            { texto: "40% = 40/100 = 2/5 (simplificando ÷20)" },
            { texto: "2/5 = 2 ÷ 5 = 0,4" },
          ],
          resultado: "40% = 2/5 = 0,4",
        },
        {
          enunciado: "Calcula el 75% de 120 usando equivalencias",
          pasos: [
            { texto: "75% = 3/4" },
            { texto: "3/4 de 120: 120 ÷ 4 = 30, 30 × 3 = 90" },
          ],
          resultado: "75% de 120 = 90",
        },
      ],
      ejercicios: [
        {
          id: "5-2-11-e1",
          enunciado: "¿A qué porcentaje equivale 0,35?",
          tipo: "numero",
          respuesta: "35",
          pista: "Multiplica por 100.",
          explicacion: "0,35 × 100 = 35%.",
        },
        {
          id: "5-2-11-e2",
          enunciado: "¿Cuál es la fracción equivalente a 0,6?",
          tipo: "texto",
          respuesta: "3/5",
          pista: "0,6 = 6/10. Simplifica dividiendo entre 2.",
          explicacion: "6/10 ÷ 2/2 = 3/5.",
        },
        {
          id: "5-2-11-e3",
          enunciado: "Un libro tiene 200 páginas. Has leído el 60%. ¿Cuántas páginas has leído?",
          tipo: "numero",
          respuesta: "120",
          pista: "60% = 3/5. Halla 3/5 de 200.",
          explicacion: "200 ÷ 5 = 40. 40 × 3 = 120 páginas.",
        },
        {
          id: "5-2-11-e4",
          enunciado: "Ordena de menor a mayor: 3/4, 0,7, 72%",
          tipo: "texto",
          respuesta: "0,7, 72%, 3/4",
          pista: "Convierte todo a decimal: 3/4=0,75, 0,7=0,7, 72%=0,72.",
          explicacion: "0,70 < 0,72 < 0,75. Orden: 0,7 < 72% < 3/4.",
        },
      ],
    },
  ],
}

export default unidad2
