import type { Unidad } from "../tipos"

const unidad3: Unidad = {
  id: 3,
  nombre: "Geometría",
  descripcion: "Clasifica triángulos y cuadriláteros, trabaja con ángulos, coordenadas y figuras tridimensionales.",
  color: "purple",
  icono: "📐",
  lecciones: [
    {
      id: "5-3-1",
      titulo: "Ángulos",
      objetivo: "Clasificar ángulos por su medida y calcular ángulos complementarios y suplementarios.",
      concepto_clave: "Agudo: <90°. Recto: =90°. Obtuso: entre 90° y 180°. Llano: =180°. Complementarios suman 90°. Suplementarios suman 180°.",
      explicacion: [
        "Un ÁNGULO es la abertura formada por dos rayos que salen del mismo punto (vértice). Se mide en grados (°).",
        "Clasificación: AGUDO (entre 0° y 90°), RECTO (exactamente 90°, se indica con un cuadradito), OBTUSO (entre 90° y 180°), LLANO (exactamente 180°, forma una línea recta).",
        "Ángulos COMPLEMENTARIOS: dos ángulos que suman 90°. Ángulos SUPLEMENTARIOS: dos ángulos que suman 180°. Si un ángulo es α, su complementario es (90°−α) y su suplementario es (180°−α).",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuánto mide el complementario de 37°?",
          pasos: [
            { texto: "Complementario = 90° − 37°" },
            { texto: "= 53°" },
          ],
          resultado: "El complementario de 37° mide 53°",
        },
        {
          enunciado: "¿Cuánto mide el suplementario de 110°?",
          pasos: [
            { texto: "Suplementario = 180° − 110°" },
            { texto: "= 70°" },
          ],
          resultado: "El suplementario de 110° mide 70°",
        },
      ],
      ejercicios: [
        {
          id: "5-3-1-e1",
          enunciado: "¿Cómo se clasifica un ángulo de 145°?",
          tipo: "seleccion",
          opciones: ["Agudo", "Recto", "Obtuso", "Llano"],
          respuesta: "Obtuso",
          pista: "¿Está entre 90° y 180°?",
          explicacion: "145° está entre 90° y 180°, por lo tanto es un ángulo obtuso.",
        },
        {
          id: "5-3-1-e2",
          enunciado: "¿Cuánto mide el suplementario de 65°?",
          tipo: "numero",
          respuesta: "115",
          pista: "Suplementario = 180° − 65°.",
          explicacion: "180° − 65° = 115°.",
        },
        {
          id: "5-3-1-e3",
          enunciado: "Dos ángulos complementarios miden lo mismo. ¿Cuánto mide cada uno?",
          tipo: "numero",
          respuesta: "45",
          pista: "Si son iguales y suman 90°, cada uno es 90° ÷ 2.",
          explicacion: "90° ÷ 2 = 45°. Cada ángulo mide 45°.",
        },
        {
          id: "5-3-1-e4",
          enunciado: "¿Puede un ángulo ser a la vez complementario y suplementario de otro?",
          tipo: "seleccion",
          opciones: ["Sí, si ambos miden 0°", "No, es imposible", "Sí, si el ángulo mide 45°"],
          respuesta: "No, es imposible",
          pista: "Los complementarios suman 90° y los suplementarios suman 180°. ¿Puede un par de ángulos cumplir ambas cosas?",
          explicacion: "Para ser complementarios deben sumar 90° Y para ser suplementarios deben sumar 180°. Un par de ángulos no puede sumar 90° y 180° al mismo tiempo.",
        },
      ],
    },
    {
      id: "5-3-2",
      titulo: "Coordenadas de puntos en el plano",
      objetivo: "Ubicar e identificar puntos en el plano cartesiano usando pares ordenados (x, y).",
      concepto_clave: "Par ordenado (x, y): x indica la posición horizontal (eje X), y indica la posición vertical (eje Y). El origen es (0,0).",
      explicacion: [
        "El PLANO CARTESIANO es una cuadrícula formada por dos ejes perpendiculares: el eje horizontal X y el eje vertical Y. Se cruzan en el ORIGEN (0,0).",
        "Cada punto se ubica con un PAR ORDENADO (x, y). El primer número indica cuánto se mueve horizontalmente (derecha: positivo, izquierda: negativo) y el segundo cuánto se mueve verticalmente (arriba: positivo, abajo: negativo).",
        "Para ubicar el punto (3, 2): empieza en el origen, ve 3 unidades a la derecha, luego 2 unidades arriba.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cómo se ubica el punto (4, −2)?",
          pasos: [
            { texto: "Empieza en el origen (0,0)" },
            { texto: "x=4: muévete 4 unidades a la derecha" },
            { texto: "y=−2: muévete 2 unidades hacia abajo" },
          ],
          resultado: "(4, −2) está 4 unidades a la derecha y 2 abajo del origen",
        },
        {
          enunciado: "¿Qué coordenadas tiene el origen?",
          pasos: [
            { texto: "El origen no se mueve ni en x ni en y" },
          ],
          resultado: "El origen tiene coordenadas (0, 0)",
        },
      ],
      ejercicios: [
        {
          id: "5-3-2-e1",
          enunciado: "¿Cuál es la coordenada x del punto (5, 3)?",
          tipo: "numero",
          respuesta: "5",
          pista: "El primer número del par ordenado es x.",
          explicacion: "En (5, 3), la coordenada x = 5 (posición horizontal).",
        },
        {
          id: "5-3-2-e2",
          enunciado: "Ubica el punto (0, 4). ¿En qué eje está?",
          tipo: "seleccion",
          opciones: ["En el eje X", "En el eje Y", "En el origen"],
          respuesta: "En el eje Y",
          pista: "x=0 significa que no se mueve horizontalmente. ¿Dónde queda?",
          explicacion: "Como x=0, el punto no se desplaza horizontalmente. Está sobre el eje Y a 4 unidades del origen.",
        },
        {
          id: "5-3-2-e3",
          enunciado: "Un mapa usa coordenadas. El colegio está en (3, 5) y la tienda en (3, 1). ¿Cuántas unidades los separan?",
          tipo: "numero",
          respuesta: "4",
          pista: "Tienen el mismo x. Solo cambia y: |5 − 1| = ?",
          explicacion: "Como tienen el mismo x (3), solo hay distancia vertical: |5 − 1| = 4 unidades.",
        },
        {
          id: "5-3-2-e4",
          enunciado: "Describe cómo llegar del punto (1, 2) al punto (4, 5) moviéndote solo horizontal o verticalmente",
          tipo: "texto",
          respuesta: "3 unidades a la derecha y 3 unidades hacia arriba",
          pista: "Diferencia en x: 4−1=3. Diferencia en y: 5−2=3.",
          explicacion: "Δx = 4−1 = 3 (derecha). Δy = 5−2 = 3 (arriba). Muévete 3 a la derecha y 3 arriba.",
        },
      ],
    },
    {
      id: "5-3-3",
      titulo: "Triángulos: clasificación",
      objetivo: "Clasificar triángulos por sus lados (equilátero, isósceles, escaleno) y por sus ángulos.",
      concepto_clave: "Por lados: equilátero (3=), isósceles (2=), escaleno (0=). Por ángulos: acutángulo (<90° todos), rectángulo (un 90°), obtusángulo (un >90°).",
      explicacion: [
        "Por sus LADOS: equilátero (los 3 lados iguales), isósceles (exactamente 2 lados iguales), escaleno (todos los lados diferentes).",
        "Por sus ÁNGULOS: acutángulo (los 3 ángulos son agudos, menores de 90°), rectángulo (tiene un ángulo recto de exactamente 90°), obtusángulo (tiene un ángulo obtuso, mayor de 90°).",
        "Propiedad fundamental: la suma de los ángulos interiores de cualquier triángulo es siempre 180°. Si dos ángulos son 60° y 70°, el tercero es 180°−60°−70° = 50°.",
      ],
      ejemplos: [
        {
          enunciado: "Clasifica el triángulo de lados 5, 5, 8 cm y ángulos 29°, 29°, 122°",
          pasos: [
            { texto: "Por lados: dos lados iguales (5 y 5) → isósceles" },
            { texto: "Por ángulos: 122° > 90° → obtusángulo" },
          ],
          resultado: "Triángulo isósceles y obtusángulo",
        },
        {
          enunciado: "Un triángulo tiene ángulos de 90° y 35°. ¿Cuánto mide el tercer ángulo?",
          pasos: [
            { texto: "Suma de ángulos = 180°" },
            { texto: "Tercer ángulo = 180° − 90° − 35° = 55°" },
          ],
          resultado: "El tercer ángulo mide 55°",
        },
      ],
      ejercicios: [
        {
          id: "5-3-3-e1",
          enunciado: "Un triángulo tiene lados de 6, 8 y 10 cm. ¿Cómo se clasifica por sus lados?",
          tipo: "seleccion",
          opciones: ["Equilátero", "Isósceles", "Escaleno"],
          respuesta: "Escaleno",
          pista: "¿Hay algún par de lados iguales?",
          explicacion: "6 ≠ 8 ≠ 10: todos los lados son diferentes, es un triángulo escaleno.",
        },
        {
          id: "5-3-3-e2",
          enunciado: "Un triángulo tiene ángulos de 60°, 60° y 60°. ¿Cómo se clasifica por sus ángulos y lados?",
          tipo: "texto",
          respuesta: "acutángulo y equilátero",
          pista: "Todos los ángulos son iguales y menores de 90°. Los lados también son iguales.",
          explicacion: "60°+60°+60°=180°✓. Todos los ángulos son agudos (acutángulo). Si los 3 ángulos son iguales, los 3 lados también son iguales (equilátero).",
        },
        {
          id: "5-3-3-e3",
          enunciado: "Un triángulo tiene ángulos de 45° y 90°. ¿Cuánto mide el tercer ángulo?",
          tipo: "numero",
          respuesta: "45",
          pista: "180° − 45° − 90° = ?",
          explicacion: "180° − 45° − 90° = 45°.",
        },
        {
          id: "5-3-3-e4",
          enunciado: "¿Puede existir un triángulo con ángulos de 90°, 90° y 0°?",
          tipo: "seleccion",
          opciones: ["Sí", "No, porque la suma no da 180°", "No, porque un ángulo no puede medir 0°"],
          respuesta: "No, porque un ángulo no puede medir 0°",
          pista: "Aunque 90+90+0=180, ¿tiene sentido un ángulo de 0°?",
          explicacion: "90°+90°+0°=180° sí suma, pero un ángulo de 0° no existe (los rayos coincidirían, no formarían un triángulo). Los ángulos deben ser mayores que 0°.",
        },
      ],
    },
    {
      id: "5-3-4",
      titulo: "Cuadriláteros: clasificación",
      objetivo: "Identificar y clasificar cuadriláteros según sus lados, ángulos y diagonales.",
      concepto_clave: "Cuadrilátero: polígono de 4 lados. Suma de ángulos interiores = 360°. Tipos: cuadrado, rectángulo, rombo, romboide, trapecio.",
      explicacion: [
        "Un CUADRILÁTERO es un polígono con exactamente 4 lados y 4 ángulos. La suma de sus ángulos interiores siempre es 360°.",
        "PARALELOGRAMOS (dos pares de lados paralelos): cuadrado (4 lados iguales y 4 ángulos rectos), rectángulo (4 ángulos rectos), rombo (4 lados iguales), romboide (forma general).",
        "TRAPECIO: solo un par de lados paralelos (las bases). TRAPEZOIDE: ningún par de lados paralelos. El cuadrado es el cuadrilátero más especial: es rectángulo Y rombo al mismo tiempo.",
      ],
      ejemplos: [
        {
          enunciado: "¿Por qué un cuadrado también es un rectángulo?",
          pasos: [
            { texto: "Rectángulo: 4 ángulos rectos y lados opuestos iguales" },
            { texto: "Cuadrado: 4 ángulos rectos y los 4 lados iguales" },
            { texto: "El cuadrado cumple todas las condiciones del rectángulo" },
          ],
          resultado: "Todo cuadrado es un rectángulo (pero no todo rectángulo es un cuadrado)",
        },
        {
          enunciado: "Un cuadrilátero tiene ángulos de 80°, 100° y 90°. ¿Cuánto mide el cuarto?",
          pasos: [
            { texto: "Suma de ángulos = 360°" },
            { texto: "Cuarto ángulo = 360° − 80° − 100° − 90° = 90°" },
          ],
          resultado: "El cuarto ángulo mide 90°",
        },
      ],
      ejercicios: [
        {
          id: "5-3-4-e1",
          enunciado: "¿Cuánto suman los ángulos interiores de cualquier cuadrilátero?",
          tipo: "numero",
          respuesta: "360",
          pista: "Un cuadrilátero se puede dividir en 2 triángulos, cada uno con 180°.",
          explicacion: "2 × 180° = 360°. La suma de los ángulos interiores de cualquier cuadrilátero es 360°.",
        },
        {
          id: "5-3-4-e2",
          enunciado: "¿Qué cuadrilátero tiene 4 lados iguales pero NO tiene necesariamente 4 ángulos rectos?",
          tipo: "seleccion",
          opciones: ["Rectángulo", "Cuadrado", "Rombo"],
          respuesta: "Rombo",
          pista: "El cuadrado tiene lados iguales Y ángulos rectos. ¿Cuál tiene solo lados iguales?",
          explicacion: "El rombo tiene los 4 lados iguales pero sus ángulos pueden no ser rectos (a menos que sea un cuadrado).",
        },
        {
          id: "5-3-4-e3",
          enunciado: "Un trapecio tiene bases de 8 cm y 5 cm y lados de 4 cm y 4 cm. ¿Cuánto mide su perímetro?",
          tipo: "numero",
          respuesta: "21",
          pista: "Perímetro = suma de todos los lados.",
          explicacion: "8 + 5 + 4 + 4 = 21 cm.",
        },
        {
          id: "5-3-4-e4",
          enunciado: "¿Cuál de estas afirmaciones es verdadera?",
          tipo: "seleccion",
          opciones: [
            "Todo rectángulo es un cuadrado",
            "Todo cuadrado es un rombo",
            "Todo rombo es un rectángulo",
          ],
          respuesta: "Todo cuadrado es un rombo",
          pista: "¿El cuadrado tiene los 4 lados iguales? ¿Eso es lo que define al rombo?",
          explicacion: "Un rombo tiene 4 lados iguales. El cuadrado también los tiene, así que todo cuadrado es un rombo. Pero no al revés.",
        },
      ],
    },
    {
      id: "5-3-5",
      titulo: "Congruencia de figuras",
      objetivo: "Identificar figuras congruentes y aplicar los criterios de congruencia de triángulos.",
      concepto_clave: "Congruentes: misma forma y mismo tamaño (se superponen perfectamente). Criterios: LLL, LAL, ALA.",
      explicacion: [
        "Dos figuras son CONGRUENTES si tienen exactamente la misma forma y el mismo tamaño. Si las recortas y las pones una encima de la otra, coinciden perfectamente.",
        "Para triángulos hay criterios que permiten confirmar congruencia con solo verificar 3 elementos: LLL (tres lados iguales), LAL (dos lados iguales con el ángulo entre ellos), ALA (dos ángulos iguales con el lado entre ellos).",
        "Los movimientos que no cambian la forma ni el tamaño son: traslación, rotación y reflexión. Si uno se obtiene del otro por alguno de estos movimientos, son congruentes.",
      ],
      ejemplos: [
        {
          enunciado: "¿Son congruentes por criterio LLL los triángulos con lados (3,4,5) y (4,3,5)?",
          pasos: [
            { texto: "Ordeno los lados: {3,4,5} y {3,4,5}" },
            { texto: "Los tres pares de lados son iguales" },
          ],
          resultado: "Sí son congruentes (criterio LLL)",
        },
        {
          enunciado: "¿Qué criterio usar si conozco dos lados (5 y 7 cm) y el ángulo entre ellos (60°)?",
          pasos: [
            { texto: "Tengo dos Lados y el Ángulo entre ellos" },
          ],
          resultado: "Criterio LAL (Lado-Ángulo-Lado)",
        },
      ],
      ejercicios: [
        {
          id: "5-3-5-e1",
          enunciado: "¿Cuántos elementos mínimos de un triángulo necesitas conocer para aplicar el criterio ALA?",
          tipo: "numero",
          respuesta: "3",
          pista: "ALA = Ángulo-Lado-Ángulo. ¿Cuántos elementos son?",
          explicacion: "ALA = 2 ángulos + 1 lado = 3 elementos.",
        },
        {
          id: "5-3-5-e2",
          enunciado: "Una figura se traslada 5 unidades a la derecha. ¿La figura resultante es congruente con la original?",
          tipo: "seleccion",
          opciones: ["Sí, la traslación conserva forma y tamaño", "No, cambia el tamaño", "Depende de la figura"],
          respuesta: "Sí, la traslación conserva forma y tamaño",
          pista: "La traslación solo mueve la figura, no la deforma.",
          explicacion: "La traslación es un movimiento rígido: conserva longitudes y ángulos, por lo que la figura resultante es congruente con la original.",
        },
        {
          id: "5-3-5-e3",
          enunciado: "¿Es lo mismo congruente que semejante?",
          tipo: "seleccion",
          opciones: ["Sí, son sinónimos", "No: congruente = igual forma y tamaño; semejante = solo igual forma", "No: congruente = igual tamaño; semejante = igual forma y tamaño"],
          respuesta: "No: congruente = igual forma y tamaño; semejante = solo igual forma",
          pista: "¿Puede una figura pequeña ser congruente con una grande del mismo diseño?",
          explicacion: "Congruente: forma Y tamaño iguales. Semejante: forma igual, tamaño puede variar. Una foto y su ampliación son semejantes pero no congruentes.",
        },
        {
          id: "5-3-5-e4",
          enunciado: "Triángulo A tiene lados 3, 4, 5 y triángulo B tiene lados 6, 8, 10. ¿Qué relación tienen?",
          tipo: "seleccion",
          opciones: ["Son congruentes", "Son semejantes", "No tienen relación"],
          respuesta: "Son semejantes",
          pista: "B es el doble de A. ¿Tienen la misma forma?",
          explicacion: "Los lados de B son el doble de A (3×2=6, 4×2=8, 5×2=10). Misma forma, diferente tamaño: son semejantes.",
        },
      ],
    },
    {
      id: "5-3-6",
      titulo: "Semejanza de figuras",
      objetivo: "Identificar figuras semejantes, hallar la razón de semejanza y calcular longitudes desconocidas.",
      concepto_clave: "Figuras semejantes: misma forma, tamaños proporcionales. Razón de semejanza = longitud nueva ÷ longitud original.",
      explicacion: [
        "Dos figuras son SEMEJANTES si tienen la misma forma pero pueden tener diferente tamaño. Los ángulos correspondientes son iguales y los lados correspondientes son proporcionales.",
        "La RAZÓN DE SEMEJANZA (o escala) es el cociente entre las longitudes correspondientes. Si razón=2, la figura nueva es el doble de la original. Si razón=1/3, es la tercera parte.",
        "Para calcular una longitud desconocida en figuras semejantes: plantea una proporción. Si el lado A1=4 corresponde a A2=6, y B1=5, entonces B2 = 5 × (6/4) = 7,5.",
      ],
      ejemplos: [
        {
          enunciado: "Un rectángulo de 4×6 cm y otro de 6×9 cm. ¿Son semejantes?",
          pasos: [
            { texto: "Razón de lados cortos: 6/4 = 1,5" },
            { texto: "Razón de lados largos: 9/6 = 1,5" },
            { texto: "Las razones son iguales → los lados son proporcionales" },
          ],
          resultado: "Sí son semejantes, con razón de semejanza 3/2 = 1,5",
        },
        {
          enunciado: "En dos triángulos semejantes, un lado mide 5 cm en el pequeño y 8 cm en el grande. Si otro lado del pequeño mide 3 cm, ¿cuánto mide el correspondiente en el grande?",
          pasos: [
            { texto: "Razón = 8/5 = 1,6" },
            { texto: "Lado grande = 3 × 1,6 = 4,8 cm" },
          ],
          resultado: "El lado correspondiente mide 4,8 cm",
        },
      ],
      ejercicios: [
        {
          id: "5-3-6-e1",
          enunciado: "Dos triángulos semejantes tienen lados correspondientes de 3 y 9 cm. ¿Cuál es la razón de semejanza?",
          tipo: "numero",
          respuesta: "3",
          pista: "Razón = lado mayor ÷ lado menor.",
          explicacion: "9 ÷ 3 = 3. La razón de semejanza es 3 (el segundo triángulo es el triple del primero).",
        },
        {
          id: "5-3-6-e2",
          enunciado: "Un mapa tiene escala 1:100.000. Si en el mapa hay 3 cm entre dos ciudades, ¿cuántos metros hay en realidad?",
          tipo: "numero",
          respuesta: "300000",
          pista: "3 cm en el mapa = 3 × 100.000 cm en la realidad. Luego convierte a metros.",
          explicacion: "3 × 100.000 = 300.000 cm = 3.000 m = 3 km. En realidad hay 300.000 cm = 3.000 metros.",
        },
        {
          id: "5-3-6-e3",
          enunciado: "¿Son semejantes todos los cuadrados?",
          tipo: "seleccion",
          opciones: ["Sí, siempre", "No, depende del tamaño"],
          respuesta: "Sí, siempre",
          pista: "Todos los cuadrados tienen la misma forma (4 ángulos de 90° y lados iguales). Solo varían en tamaño.",
          explicacion: "Todos los cuadrados tienen exactamente la misma forma. Los lados de cualquier cuadrado son proporcionales a los de cualquier otro. Siempre son semejantes.",
        },
        {
          id: "5-3-6-e4",
          enunciado: "Una foto de 10×15 cm se amplía manteniendo las proporciones hasta que el lado corto mide 25 cm. ¿Cuánto mide el lado largo?",
          tipo: "numero",
          respuesta: "37",
          pista: "Razón = 25/10 = 2,5. Lado largo = 15 × 2,5.",
          explicacion: "Razón = 25/10 = 2,5. Lado largo = 15 × 2,5 = 37,5 cm ≈ 37,5 cm.",
        },
      ],
    },
    {
      id: "5-3-7",
      titulo: "Prismas: generalidades y propiedades",
      objetivo: "Identificar prismas, reconocer sus elementos (caras, aristas, vértices) y aplicar la fórmula de Euler.",
      concepto_clave: "Prisma: dos bases poligonales iguales y paralelas, unidas por rectángulos laterales. Euler: C + V − A = 2.",
      explicacion: [
        "Un PRISMA es un sólido con dos bases que son polígonos iguales y paralelos, unidos por caras laterales rectangulares. Se nombra según la forma de su base: prisma triangular, cuadrangular, pentagonal...",
        "Elementos: CARAS (superficies planas), ARISTAS (segmentos donde se unen dos caras), VÉRTICES (puntos donde se unen 3 o más aristas).",
        "La fórmula de EULER relaciona estos elementos: C + V − A = 2, donde C=caras, V=vértices, A=aristas. Sirve para verificar si una figura es posible.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuántas caras, aristas y vértices tiene un prisma triangular?",
          pasos: [
            { texto: "Bases: 2 triángulos (2 caras)" },
            { texto: "Caras laterales: 3 rectángulos (3 caras). Total caras C = 5" },
            { texto: "Vértices: 3 por base × 2 bases = V = 6" },
            { texto: "Aristas: 3 por base × 2 bases + 3 laterales = A = 9" },
            { texto: "Verifico Euler: 5 + 6 − 9 = 2 ✓" },
          ],
          resultado: "Prisma triangular: 5 caras, 6 vértices, 9 aristas",
        },
      ],
      ejercicios: [
        {
          id: "5-3-7-e1",
          enunciado: "¿Cuántas caras tiene un prisma pentagonal?",
          tipo: "numero",
          respuesta: "7",
          pista: "2 bases pentagonales + 5 caras laterales rectangulares.",
          explicacion: "2 bases + 5 laterales = 7 caras.",
        },
        {
          id: "5-3-7-e2",
          enunciado: "Un prisma tiene 6 caras, 8 vértices. ¿Cuántas aristas tiene? (usa Euler)",
          tipo: "numero",
          respuesta: "12",
          pista: "C + V − A = 2 → A = C + V − 2.",
          explicacion: "A = 6 + 8 − 2 = 12 aristas. Es un prisma cuadrangular (caja).",
        },
        {
          id: "5-3-7-e3",
          enunciado: "¿Qué forma tienen las bases de un prisma cuadrangular?",
          tipo: "seleccion",
          opciones: ["Triángulos", "Cuadriláteros", "Pentágonos"],
          respuesta: "Cuadriláteros",
          pista: "Cuadrangular = cuatro lados.",
          explicacion: "Un prisma cuadrangular tiene bases con forma de cuadrilátero (4 lados). Ejemplo: una caja de cartón.",
        },
        {
          id: "5-3-7-e4",
          enunciado: "¿El cubo es un tipo de prisma?",
          tipo: "seleccion",
          opciones: ["Sí, es un prisma cuadrangular con bases cuadradas", "No, el cubo no es un prisma"],
          respuesta: "Sí, es un prisma cuadrangular con bases cuadradas",
          pista: "¿El cubo tiene dos bases iguales y paralelas unidas por rectángulos?",
          explicacion: "El cubo tiene bases cuadradas (cuadriláteros) y las caras laterales también son cuadrados (rectángulos especiales). Es un prisma cuadrangular especial.",
        },
      ],
    },
    {
      id: "5-3-8",
      titulo: "Poliedros regulares: clasificación y construcción",
      objetivo: "Identificar los 5 poliedros regulares (sólidos platónicos) y sus características.",
      concepto_clave: "Poliedro regular: todas las caras son polígonos regulares iguales. Solo hay 5: tetraedro, cubo, octaedro, dodecaedro, icosaedro.",
      explicacion: [
        "Un POLIEDRO REGULAR tiene todas sus caras con la misma forma de polígono regular y el mismo número de caras se unen en cada vértice.",
        "Los 5 SÓLIDOS PLATÓNICOS: Tetraedro (4 triángulos equiláteros), Cubo/Hexaedro (6 cuadrados), Octaedro (8 triángulos equiláteros), Dodecaedro (12 pentágonos regulares), Icosaedro (20 triángulos equiláteros).",
        "Todos cumplen la fórmula de Euler C + V − A = 2. Se pueden construir desde sus redes (desarrollos planos).",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuántas caras, vértices y aristas tiene un octaedro?",
          pasos: [
            { texto: "Caras: 8 triángulos equiláteros" },
            { texto: "Vértices: 6" },
            { texto: "Verifico Euler: 8 + 6 − A = 2 → A = 12" },
          ],
          resultado: "Octaedro: 8 caras, 6 vértices, 12 aristas",
        },
      ],
      ejercicios: [
        {
          id: "5-3-8-e1",
          enunciado: "¿Cuántas caras tiene un tetraedro?",
          tipo: "numero",
          respuesta: "4",
          pista: "Tetra = cuatro.",
          explicacion: "Un tetraedro tiene 4 caras triangulares.",
        },
        {
          id: "5-3-8-e2",
          enunciado: "Un dodecaedro tiene 12 caras pentagonales y 20 vértices. ¿Cuántas aristas tiene?",
          tipo: "numero",
          respuesta: "30",
          pista: "Usa la fórmula de Euler: A = C + V − 2.",
          explicacion: "A = 12 + 20 − 2 = 30 aristas.",
        },
        {
          id: "5-3-8-e3",
          enunciado: "¿Cuál sólido platónico tiene el mayor número de caras?",
          tipo: "seleccion",
          opciones: ["Dodecaedro (12 caras)", "Icosaedro (20 caras)", "Octaedro (8 caras)"],
          respuesta: "Icosaedro (20 caras)",
          pista: "Icosa = veinte.",
          explicacion: "El icosaedro tiene 20 caras triangulares, siendo el sólido platónico con más caras.",
        },
        {
          id: "5-3-8-e4",
          enunciado: "¿Por qué solo existen exactamente 5 poliedros regulares?",
          tipo: "texto",
          respuesta: "Porque para que un poliedro exista deben reunirse al menos 3 polígonos en cada vértice y la suma de sus ángulos debe ser menor de 360°. Solo hay 5 combinaciones que lo cumplen.",
          pista: "Piensa en cuántos triángulos, cuadrados o pentágonos pueden 'cerrarse' alrededor de un vértice.",
          explicacion: "En cada vértice, la suma de los ángulos de las caras debe ser menor de 360° para que la figura se 'cierre'. Eso solo permite 5 combinaciones posibles.",
        },
      ],
    },
    {
      id: "5-3-9",
      titulo: "Cuerpos redondos: clasificación y construcción",
      objetivo: "Identificar cilindros, conos y esferas, y reconocer sus elementos.",
      concepto_clave: "Cilindro: 2 bases circulares + cara lateral curva. Cono: 1 base circular + cara lateral curva + vértice. Esfera: todos los puntos a igual distancia del centro.",
      explicacion: [
        "Los CUERPOS REDONDOS son sólidos que tienen al menos una superficie curva (a diferencia de los poliedros). Los tres principales son cilindro, cono y esfera.",
        "CILINDRO: dos bases circulares iguales y paralelas, unidas por una superficie lateral curva. Como una lata de gaseosa. Elementos: radio (r), altura (h).",
        "CONO: una base circular y una superficie lateral curva que termina en un punto (vértice o ápice). Como un embudo. ESFERA: todos sus puntos están a la misma distancia (radio) de su centro. Como un balón.",
      ],
      ejemplos: [
        {
          enunciado: "¿Cuántas caras planas y curvas tiene un cono?",
          pasos: [
            { texto: "Cara plana: 1 base circular" },
            { texto: "Cara curva: 1 superficie lateral" },
            { texto: "Vértice: 1 punto (el ápice)" },
          ],
          resultado: "El cono tiene 1 cara plana, 1 cara curva y 1 vértice",
        },
        {
          enunciado: "¿Cómo se desarrolla un cilindro en plano?",
          pasos: [
            { texto: "Dos círculos (las bases)" },
            { texto: "Un rectángulo (la cara lateral desarrollada)" },
          ],
          resultado: "La red del cilindro es: 2 círculos + 1 rectángulo",
        },
      ],
      ejercicios: [
        {
          id: "5-3-9-e1",
          enunciado: "¿Cuántas caras planas tiene una esfera?",
          tipo: "numero",
          respuesta: "0",
          pista: "La esfera es completamente redonda, sin partes planas.",
          explicacion: "La esfera no tiene ninguna cara plana. Toda su superficie es curva.",
        },
        {
          id: "5-3-9-e2",
          enunciado: "¿Qué objeto cotidiano es un ejemplo de cilindro?",
          tipo: "seleccion",
          opciones: ["Un dado", "Una pelota de tenis", "Una lata de atún"],
          respuesta: "Una lata de atún",
          pista: "¿Cuál tiene dos bases circulares y una superficie lateral curva?",
          explicacion: "Una lata de atún tiene la forma de un cilindro: dos bases circulares y la cara lateral curva.",
        },
        {
          id: "5-3-9-e3",
          enunciado: "¿Cuántos vértices tiene un cilindro?",
          tipo: "numero",
          respuesta: "0",
          pista: "Un vértice es un punto donde se unen aristas. ¿Tiene el cilindro aristas o esquinas?",
          explicacion: "El cilindro no tiene vértices ni aristas. Sus superficies se unen en curvas, no en puntos.",
        },
        {
          id: "5-3-9-e4",
          enunciado: "¿Cuál es la diferencia entre un cono y una pirámide?",
          tipo: "texto",
          respuesta: "El cono tiene base circular y superficie lateral curva. La pirámide tiene base poligonal y caras laterales triangulares planas.",
          pista: "Piensa en la forma de la base y si las caras son curvas o planas.",
          explicacion: "Cono: base circular + cara lateral curva. Pirámide: base poligonal (triángulo, cuadrado...) + caras laterales triangulares planas.",
        },
      ],
    },
  ],
}

export default unidad3
